export default {
  treeselect: {
    props: {
      options: 'Tree data array.',
      value: 'Selected leaf value array.',
      defaultValue: 'Default selected values.',
      onChange: 'Selection change callback.',
      max: 'Max selection count. 0 = unlimited.',
      mode: "Click behavior: 'select' (click to select, arrow to expand) or 'expand' (click to expand, arrow to select).",
      searchable: 'Show a search bar at the top of each level.',
      searchMode: "'local' filters current level, 'global' searches entire tree with result dropdown.",
      renderItem: 'Custom render for each option. (node, selected, expand) => JSX.Element.',
      placeholder: 'Placeholder text when empty.',
      title: 'Overlay title.',
      disabled: 'Disable the component.',
      onLoadChildren: 'Async children loader.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      triggerPadding: 'Trigger padding.',
      triggerHeight: 'Trigger min height.',
      zIndex: 'Overlay z-index.',
      bg: 'Overlay content background.',
      itemPadding: 'Item padding.',
    },
    demo: {
      basic: 'Basic Usage',
      maxLimit: 'Max Selection',
      modeExpand: 'Expand Mode',
      customRender: 'Custom Render',
      asyncLoad: 'Async Load',
    },
    demoDesc: {
      basic: 'Two-level tree with multi-select. Click row to select, arrow to expand.',
      maxLimit: 'Limit max selections to 3 items.',
      modeExpand: "mode='expand': click row to expand into children, right arrow to select.",
      customRender: 'renderItem gives full control over each row layout.',
      asyncLoad: 'Load children dynamically on first expand.',
    },
    intro: 'Push-based multi-select tree component. Navigate through levels, select leaf nodes, view count per parent.',
  },
};