export default {
  treeselect: {
    props: {
      options: '树形数据。',
      value: '已选叶子节点值数组。',
      defaultValue: '默认选中值。',
      onChange: '选中值变化回调。',
      onConfirm: '点击头部"确定"时触发，携带当前选中值。',
      onCancel: '通过遮罩或关闭按钮关闭弹窗时触发。',
      max: '最大可选数量，0 = 不限制。',
      mode: "点击行为：'select'（点行选中，箭头展开）或 'expand'（点行展开，箭头选中）。",
      checkStrictly: '严格勾选：勾选父节点只选中父节点本身，不再级联到其所有叶子节点。',
      onlyLeafCheckable: '只允许勾选叶子节点。点击父节点行变为展开导航（select 模式同样生效）。',
      searchable: '在每层顶部显示搜索框。',
      searchMode: "'local' 过滤当前层，'global' 搜索整棵树并显示结果下拉。",
      onSearch: '异步搜索回调。提供时输入内容改为调用该回调拉取结果。',
      renderItem:
        '自定义渲染每个选项。(node, selected, expand, toggle) => JSX.Element，toggle 用于切换选中。',
      placeholder: '未选时的占位文字。',
      title: '弹窗标题。',
      disabled: '禁用组件。',
      onLoadChildren:
        '异步加载子节点。节点无 children 但提供此回调时视为可展开，点击箭头触发加载。',
      emptyText: '无数据或搜索无结果时的占位文字。',
      loadErrorText: '异步加载子节点失败时，重试控件的显示文字。',
      show: '受控展开弹窗。',
      onUpdateShow: '弹窗开关状态变化回调（受控）。',
      onClose: '弹窗关闭回调。',
      closeable: '头部显示关闭按钮。',
      swipeable: '启用手势导航：左滑进入子级，右滑返回上一级。',
      checkboxPosition: "复选框位置，expand 模式下生效。'left' 或 'right'。",
      teleport: 'Portal 挂载目标。',
      zIndex: '弹窗层级。',
      maxHeight: '弹窗内容最大高度。',
      format: '自定义触发区已选文字的格式化函数。(value, options) => string',
      clearable: '有选中值时在触发区显示清空按钮。',
      readonly: '只读模式：可打开弹窗查看，但不能修改选择。',
      renderTrigger: '完全自定义触发区渲染，需要自行调用 open / clear。',
      ref: 'ref 回调，挂载时注入命令式句柄，卸载时传入 null。用于非受控场景（编程打开/关闭、设置/读取/清空选中值、重置导航）。受控 props（value/show）仍是首选。可用方法见下方 "Ref Methods" 表格。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    refMethods: {
      open: '打开面板。disabled/readonly 时不生效；show 受控时改为调用 onUpdateShow(true)。',
      close: '关闭面板。show 受控时改为调用 onUpdateShow(false)。不触发 onCancel。',
      setValue: '编程设置选中值。受控时触发 onChange，非受控时更新内部状态。',
      getValue: '读取当前选中值。',
      clear: '清空选中值。disabled/readonly 时不生效。',
      resetNavigation: '回到根层级并清空搜索关键词。',
    },
    cssVars: {
      triggerPadding: '触发器内边距。',
      triggerHeight: '触发器最小高度。',
      zIndex: '弹窗层级。',
      bg: '弹窗内容背景。',
      itemPadding: '列表项内边距。',
      checkboxLeftMargin: '左侧复选框与标签文字的间距。仅 checkboxPosition="left" 时生效。',
    },
    demo: {
      basic: '基础用法',
      maxLimit: '最大选择数',
      modeExpand: '展开模式',
      customRender: '自定义渲染',
      asyncLoad: '异步加载',
      bigData: '海量数据 + 搜索',
      checkStrictly: '严格勾选',
      trigger: '触发区定制',
      ref: 'Ref API',
    },
    demoDesc: {
      basic: '两级树形多选，点行选中、箭头展开。父节点自动统计子节点选中数量。',
      maxLimit: '限制最多选择 3 项。',
      modeExpand: "mode='expand'：点行展开进入子级，右侧箭头选中。",
      customRender: 'renderItem 完全控制每行的渲染。',
      asyncLoad: '展开时动态加载子节点。',
      bigData:
        '1800 个选项，配合 global 搜索，输入关键词即可从整棵树中快速定位。结果最多展示 100 条。',
      checkStrictly: 'checkStrictly：勾选父节点只选中父节点本身，不再级联到其所有叶子。',
      trigger: 'clearable 在触发区提供清空按钮，format 自定义已选文字展示。',
      ref: '通过 ref 在外部命令式操作组件：打开面板、清空选中值等。受控 props 仍是首选，ref 适合非受控场景。',
    },
    intro: 'Push 式多选树组件。逐层导航，勾选叶子节点，父级自动显示已选计数。',
  },
};
