export default {
  calendar: {
    props: {
      type: 'Selection mode: single, multiple, or range.',
      value: 'Current value: Date (single), Date[] (multiple), [Date, Date] (range).',
      onChange: 'Value change callback.',
      minDate: 'Minimum selectable date.',
      maxDate: 'Maximum selectable date.',
      defaultDate: 'Default displayed month, defaults to today.',
      firstDayOfWeek: 'First day of week, 0=Sunday, 1=Monday.',
      weekdays: 'Custom weekday labels, default ["Sun","Mon",...] or ["日","一",...].',
      titleFormatter: 'Month title formatter: (year, month) => string.',
      activeColor: 'Active/selected color, default #1677ff.',
      dayRender: 'Custom day cell render: (day: DayInfo) => JSX.Element.',
      maxCount: 'Max selectable days for multiple mode.',
      maxRange: 'Max span in days for range mode.',
      formatter: 'Custom date formatter: (date: Date) => string.',
      showConfirm: 'Show confirm button for range mode.',
      confirmText: 'Confirm button text.',
      confirmDisabledText: 'Confirm button text when disabled.',
      readonly: 'Readonly, no selection.',
      lunar: 'Show lunar calendar info (month name, solar terms, day names).',
      popup: 'Popup mode, default true. Set false to embed inline.',
      show: 'Controlled popup visibility.',
      onUpdateShow: 'Popup show state change callback.',
      title: 'Popup title. Auto-follows scroll month if not set.',
      onClose: 'Popup close callback.',
      closeable: 'Show close button on popup.',
      round: 'Popup round corners.',
      teleport: 'Portal mount target.',
      zIndex: 'Custom z-index.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-calendar-bg': 'Calendar background color.',
      '--sc-calendar-text': 'Date text color.',
      '--sc-calendar-title-height': 'Month title height.',
      '--sc-calendar-weekday-height': 'Weekday row height.',
      '--sc-calendar-day-size': 'Day cell height.',
      '--sc-calendar-month-gap': 'Month spacing.',
      '--sc-calendar-active-bg': 'Selected date background.',
      '--sc-calendar-active-color': 'Selected date text color.',
      '--sc-calendar-today-border': 'Today marker dot color.',
      '--sc-calendar-other-month': 'Non-current month text color.',
      '--sc-calendar-disabled-opacity': 'Disabled state opacity.',
      '--sc-calendar-mark-color': 'Month watermark number color.',
      '--sc-calendar-header-shadow': 'Header shadow.',
      '--sc-calendar-confirm-height': 'Confirm button area height.',
      '--sc-calendar-confirm-color': 'Confirm button color.',
      '--sc-calendar-weekday-color': 'Weekday label color.',
    },
    demo: {
      single: 'Single (Popup)',
      range: 'Range Selection',
      customRender: 'Custom Render',
      holiday: 'Holiday Markers',
      inline: 'Inline Mode',
      lunar: 'Lunar Display',
      multiple: 'Multiple Select',
    },
    demoDesc: {
      single: 'Default popup mode with auto-following month title.',
      range: 'type=range + showConfirm. Select start & end, then confirm.',
      customRender: 'Pink activeColor + fancy dayRender with emoji, colored circles, and event badges on each day.',
      holiday: 'Use dayRender to mark weekends and special dates.',
      inline: 'popup=false embeds the calendar directly in the page.',
      lunar: 'lunar=true shows lunar month names, solar terms, and day names.',
      multiple: 'type=multiple with maxCount=3. Click to toggle selection.',
    },
    optionProps: {
      year: 'Year.',
      month: 'Month.',
      day: 'Day.',
      date: 'Date object.',
      isCurrentMonth: 'Whether this day belongs to the current month.',
      isToday: 'Whether this day is today.',
      isDisabled: 'Whether this day is disabled (outside min/max range).',
      lunarText: 'Lunar info text, only when lunar=true. e.g. "初一", "清明".',
    },
    intro: 'Calendar picker with single, multiple, and range selection modes. Supports popup and inline display, lunar calendar, and custom day rendering.',
  },
};
