export default {
  calendar: {
    props: {
      type: '选择模式：single（单选）、multiple（多选）、range（范围选择）。',
      value: '当前选中值。single 对应 Date，multiple 对应 Date[]，range 对应 [Date, Date]。',
      onChange: '值变化回调。',
      minDate: '最小可选日期。',
      maxDate: '最大可选日期。',
      defaultDate: '默认展示的月份，默认当天。',
      firstDayOfWeek: '一周起始日，0=周日，1=周一。',
      weekdays: '自定义星期标题数组，默认中文为 ["日","一",...,"六"]，英文为 ["Sun","Mon",...]。',
      titleFormatter: '月份标题格式化函数，(year, month) => string。',
      activeColor: '选中态颜色，默认 #1677ff。',
      dayRender: '自定义日期格子渲染，(day: DayInfo) => JSX.Element。',
      maxCount: '多选模式下最多可选天数。',
      maxRange: '范围选择最大跨度（天）。',
      formatter: '自定义日期格式化函数，(date: Date) => string。',
      showConfirm: '范围模式是否显示确认按钮。',
      confirmText: '确认按钮文字。',
      confirmDisabledText: '确认按钮禁用时文字。',
      readonly: '只读模式，不可选择。',
      lunar: '显示农历信息。月初显示月名，节气日显示节气名，其他显示日名。',
      popup: '弹出模式，默认 true。设为 false 则平铺展示。',
      show: '弹出层显示（受控）。',
      onUpdateShow: '弹出层显示状态变化回调。',
      title: '弹出层标题。不传则自动跟随滚动月份。',
      onClose: '弹出层关闭回调。',
      closeable: '显示关闭按钮。',
      round: '弹出层圆角。',
      teleport: 'Portal 挂载目标。',
      zIndex: '自定义层级。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-calendar-bg': '日历背景色。',
      '--sc-calendar-text': '日期文字颜色。',
      '--sc-calendar-title-height': '月份标题高度。',
      '--sc-calendar-weekday-height': '星期栏高度。',
      '--sc-calendar-day-size': '日期格子高度。',
      '--sc-calendar-month-gap': '月份间距。',
      '--sc-calendar-active-bg': '选中态背景色。',
      '--sc-calendar-active-color': '选中态文字色。',
      '--sc-calendar-today-border': '今天标记颜色。',
      '--sc-calendar-other-month': '非当月日期文字色。',
      '--sc-calendar-disabled-opacity': '禁用态透明度。',
      '--sc-calendar-mark-color': '月份水印数字颜色。',
      '--sc-calendar-header-shadow': '标题栏阴影。',
      '--sc-calendar-confirm-height': '确认按钮区高度。',
      '--sc-calendar-confirm-color': '确认按钮颜色。',
      '--sc-calendar-weekday-color': '星期栏文字颜色。',
    },
    demo: {
      single: '单选（弹出）',
      range: '范围选择',
      customRender: '自定义渲染',
      holiday: '节假日标记',
      inline: '内联模式',
      lunar: '农历显示',
      multiple: '多选模式',
    },
    demoDesc: {
      single: 'popup 模式，标题自动跟随滚动月份。点击触发弹出层，选中后自动关闭。',
      range: 'type=range + showConfirm，选择起止日期后点确认。',
      customRender: 'activeColor 粉色选中色 + dayRender 用 emoji、彩色圆形背景、事件标签装饰日期格子。',
      holiday: '通过 dayRender 自定义格子，标记周末和节假日，适合做日程标记。',
      inline: 'popup=false 直接嵌入页面。',
      lunar: 'lunar=true 启用农历，月初显示月名、节气日显示节气名。',
      multiple: 'type=multiple，点击切换选中/取消，maxCount 限制最多天数。',
    },
    optionProps: {
      year: '年。',
      month: '月。',
      day: '日。',
      date: 'Date 对象。',
      isCurrentMonth: '是否为当月日期。',
      isToday: '是否为今天。',
      isDisabled: '是否被禁用（超出 min/max 范围）。',
      lunarText: '农历信息文本，仅 lunar=true 时有值，如"初一""清明"。',
    },
    intro: '日历选择器，支持单选、多选、范围选择三种模式。默认弹出层展示，也可内联嵌入。支持农历、自定义日期格子和节假日标记。',
  },
};
