export default {
  input: {
    props: {
      type: 'Input type: text / number / password / tel / email / url, default text.',
      value: 'Current value (controlled).',
      onChange: 'Value change callback.',
      defaultValue: 'Default value (uncontrolled).',
      placeholder: 'Placeholder text.',
      maxlength: 'Max length. Input blocked beyond this limit.',
      disabled: 'Disabled.',
      readonly: 'Readonly — focusable & copyable, not editable.',
      align: 'Text alignment: left / center / right, default left.',
      clearable: 'Show clear × button when content present.',
      showPasswordToggle: 'Show password visibility toggle (type=password).',
      showCount: 'Show character count (requires maxlength).',
      prefix: 'Left icon or text.',
      suffix: 'Right icon or text.',
      size: 'Preset size: sm (32px) / md (40px) / lg (48px).',
      height: 'Direct height override (takes priority over size).',
      onBlur: 'Blur callback.',
      onFocus: 'Focus callback.',
      onEnter: 'Enter key callback.',
      onClear: 'Clear callback.',
      error: 'Error state — shows red wavy underline.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
      id: 'DOM id.',
      name: 'Native name attribute.',
      autofocus: 'Auto-focus on mount.',
    },
    cssVars: {
      '--sc-input-text-color': 'Text color.',
      '--sc-input-placeholder-color': 'Placeholder color.',
      '--sc-input-disabled-opacity': 'Disabled opacity, default 0.5.',
      '--sc-input-gap': 'Internal gap, default 6px.',
      '--sc-input-affix-color': 'Affix color.',
      '--sc-input-affix-font-size': 'Affix font size, default 0.9rem.',
      '--sc-input-clear-color': 'Clear button color.',
      '--sc-input-clear-hover-color': 'Clear button hover color.',
      '--sc-input-count-font-size': 'Count font size, default 0.75rem.',
      '--sc-input-count-color': 'Count color.',
      '--sc-input-error-color': 'Error underline color, default #e01823.',
    },
    demo: {
      standalone: 'Standalone',
      types: 'Types',
      clearable: 'Clear & Password',
      affix: 'Prefix & Suffix',
      count: 'Char Count',
      states: 'States',
      size: 'Size',
      search: 'Search',
      sms: 'SMS Code',
      form: 'Form Integration',
    },
    demoDesc: {
      standalone: 'No Cell or Form — plain createSignal + value/onChange. Fully standalone.',
      types: 'text, number, password, tel, email — five types.',
      clearable: 'clearable shows × button. showPasswordToggle toggles visibility.',
      affix: 'prefix (@) and suffix (@gmail.com). Also search with emoji.',
      count: 'maxlength limits input + showCount displays counter.',
      states: 'disabled, readonly, error — three states.',
      size: 'sm (32px), md (40px), lg (48px) preset sizes.',
      search: 'prefix + clearable for a rounded search input.',
      sms: 'Phone input + suffix countdown button, 60s timer.',
      form: 'Input auto-integrates with FormItem via useFormField() — no manual value/onChange wiring.',
    },
    intro: 'Text input with types, clear button, prefix/suffix, char count, password toggle. Auto-integrates with Form via FormItem.',
  },
};
