export default {
  input: {
    props: {
      type: '输入类型：text / number / password / tel / email / url，默认 text。',
      value: '当前值（受控）。',
      onChange: '值变化回调。',
      defaultValue: '默认值（非受控）。',
      placeholder: '占位文本。',
      maxlength: '最大长度。超过后不可继续输入。',
      disabled: '禁用。',
      readonly: '只读，可聚焦复制但不可编辑。',
      align: '文字对齐：left / center / right，默认 left。',
      clearable: '显示清除按钮，输入内容后右侧出现 × 图标。',
      showPasswordToggle: 'type=password 时显示密码可见切换按钮。',
      showCount: '显示字数统计（需配合 maxlength）。',
      prefix: '左侧图标或文本。',
      suffix: '右侧图标或文本。',
      size: '尺寸：sm (32px) / md (40px) / lg (48px)。',
      height: '直接指定高度，覆盖 size。',
      onBlur: '失焦回调。',
      onFocus: '聚焦回调。',
      onEnter: '回车回调。',
      onClear: '清除回调。',
      error: '错误状态，底部显示红色波浪线。',
      class: '自定义 CSS class。',
      style: '内联样式。',
      id: 'DOM id。',
      name: '原生 name 属性。',
      autofocus: '自动聚焦。',
    },
    cssVars: {
      '--sc-input-text-color': '文字颜色。',
      '--sc-input-placeholder-color': '占位符颜色。',
      '--sc-input-disabled-opacity': '禁用态透明度，默认 0.5。',
      '--sc-input-gap': '内部元素间距，默认 6px。',
      '--sc-input-affix-color': '前后缀颜色。',
      '--sc-input-affix-font-size': '前后缀字号，默认 0.9rem。',
      '--sc-input-clear-color': '清除按钮颜色。',
      '--sc-input-clear-hover-color': '清除按钮悬停色。',
      '--sc-input-count-font-size': '计数字号，默认 0.75rem。',
      '--sc-input-count-color': '计数颜色。',
      '--sc-input-error-color': '错误态波浪线颜色，默认 #e01823。',
    },
    demo: {
      standalone: '独立使用',
      types: '输入类型',
      clearable: '清除 & 密码',
      affix: '前后缀',
      count: '字数统计',
      states: '状态',
      size: '尺寸',
      search: '搜索框',
      sms: '验证码',
      form: '表单集成',
    },
    demoDesc: {
      standalone: '不依赖 Cell 或 Form，直接用 createSignal 管理值。value + onChange 受控模式。',
      types: 'text / number / password / tel / email 五种类型。',
      clearable: 'clearable 显示清除按钮，showPasswordToggle 切换密码可见性。',
      affix: 'prefix 前置 @ 符号，suffix 后置 @gmail.com，emoj 搜索。',
      count: 'maxlength 限制字数 + showCount 显示统计。',
      states: 'disabled 禁用、readonly 只读、error 红色错误线。',
      size: 'sm (32px) / md (40px) / lg (48px) 三种预设尺寸。',
      search: 'prefix + clearable 实现圆角搜索框。',
      sms: '手机号 + suffix 验证码按钮，60s 倒计时。',
      form: 'Input 通过 useFormField() 自动接入 FormItem，无需手动传 value/onChange。',
    },
    intro: '文本输入组件。支持多种类型、清除、前后缀、字数统计、密码切换，通过 FormItem 自动接入表单。',
  },
};
