export default {
  about: {
    title: 'About the Project',
    origins: 'Origins',
    originsP1: "This project began in 2023, when Solid.js was still in its early days and its ecosystem was sparse — a situation that, candidly, hasn't changed as much as one would hope. Solid the framework is exceptional: it delivers the DX of React with none of the historical baggage, and its performance was — and remains — best-in-class.",
    originsP2: 'The author makes no claim to being a UI designer — the color palette, spacing, and overall visual language draw significant inspiration from ',
    originsP2Link: 'Vant',
    originsP2After: ' — one of the most mature mobile component libraries in the Vue ecosystem. We gratefully acknowledge their pioneering work. At the time, no comparable library existed for Solid.js, and cross-framework migration carried prohibitive cost; the natural conclusion was to build one.',
    firstVersion: 'The First Version',
    firstVersionP: 'The initial iteration, built over several months, included Picker, DatePicker, Cascader, ActionSheet, Dialog, and a handful of form components — the ceiling of what could be achieved with the technical understanding and tooling available at the time. Life intervened, the frontend world moved on, and the project entered a long hibernation.',
    renaissance: 'Renaissance',
    renaissanceP: 'The rapid advancement of AI tooling in recent years provided both the catalyst and the means to resurrect this long-deferred undertaking. The first version served as a blueprint; years of accumulated engineering experience supplied the architectural judgment. The entire library has been rebuilt from the ground up with a unified design token system, first-class TypeScript support, and a commitment to configurability — every visual property that reasonably should be a variable, is.',
    status: 'Current Status',
    statusP1: 'The library currently ships ',
    statusP1After: " components across all major categories — basic, display, navigation, form, feedback, and selector. Features include Tree Shaking, dark mode, ConfigProvider-based global theming with automatic color derivation, a complete documentation site with mobile simulator previews, and i18n support (zh-CN / en-US).",
    roadmap: 'Roadmap',
    roadmapP: 'Near-term priorities include completing the remaining specialized components, expanding i18n coverage, and preparing the initial npm release. Medium-term goals involve business-scenario components and a richer documentation experience.',
    acknowledgments: 'Acknowledgments',
    acknowledgmentsP: 'This is a solo project, built across evenings and weekends. It is also — in the spirit of full disclosure — a collaboration between one human and one AI: the author and Claude together contributed the vast majority of the code, docs, and design decisions in this repository. ',
    acknowledgmentsLink: 'GitHub',
    acknowledgmentsAfter: ' is always open. Stars, issues, and pull requests are genuinely appreciated.',
    catBasic: 'Basic', catDisplay: 'Display', catNav: 'Navigation', catForm: 'Form', catFeedback: 'Feedback', catSelector: 'Selector',
  },
};
