export default {
  about: {
    title: '关于项目',
    origins: '缘起',
    originsP1: '本项目始于 2023 年。那时的 Solid.js 尚在早期，生态几近空白——坦诚地讲，时至今日也远谈不上繁荣。Solid 框架本身极为出色：它提供了 React 般的开发体验，却无需背负其历史包袱；性能方面，当时已是第一梯队，至今依然。',
    originsP2: '作者本人并不擅长 UI 设计——配色、间距和整体视觉风格大量参考了 ',
    originsP2Link: 'Vant',
    originsP2After: '——Vue 生态中最成熟的移动端组件库之一，在此深表敬意与感谢。彼时 Solid.js 尚无同类轮子，跨框架迁移的成本与风险亦非个人开发者所能承受，于是决定自己动手。',
    firstVersion: '第一版',
    firstVersionP: '初版断断续续实现了 Picker、DatePicker、Cascader、ActionSheet、Dialog 及若干表单组件，已是在当时技术认知与工具条件下的极限。随后因种种原因，项目进入了漫长的搁置期。',
    renaissance: '重构',
    renaissanceP: '近两年 AI 技术的快速演进为这个搁置已久的项目提供了重启的契机与工具。以初版为蓝本，结合多年来积累的工程化理解，对整套组件库进行了从底层的重构。统一的 Design Token 体系、完整的 TypeScript 类型支持、以可配置性为核心的设计原则——所有应当可被定制的视觉属性，均通过 CSS 变量暴露。',
    status: '当前进度',
    statusP1: '当前已交付 ',
    statusP1After: ' 个组件，覆盖基础、展示、导航、表单、反馈、选择器六大类别。支持 Tree Shaking、暗色模式、基于 ConfigProvider 的全局主题配置与自动色彩派生、完整的文档站与移动端模拟器预览、以及中英文国际化。',
    roadmap: '后续规划',
    roadmapP: '短期重心：完善国际化覆盖、准备初版 npm 发布。中长期方向：业务场景组件、更丰富的文档交互体验。',
    acknowledgments: '致谢',
    acknowledgmentsP: '这是一个个人项目，利用业余时间完成。坦诚地讲，这也是一个人与一个 AI 的合作项目——作者与 Claude 共同贡献了本仓库中绝大多数的代码、文档与设计决策。 ',
    acknowledgmentsLink: 'GitHub',
    acknowledgmentsAfter: ' 始终开放。每一个 star、每一条 issue、每一个 PR，都发自内心地感谢。',
    catBasic: '基础', catDisplay: '展示', catNav: '导航', catForm: '表单', catFeedback: '反馈', catSelector: '选择器',
  },
};
