export default {
  rate: {
    props: {
      value: 'Current value (controlled).',
      onChange: 'Change callback: (value: number) => void.',
      count: 'Icon count, default 5.',
      size: 'Icon size (px), default 20.',
      gutter: 'Icon gap (px), default 4.',
      color: 'Active color, default #ee0a24.',
      voidColor: 'Inactive color, default #c8c9cc.',
      disabledColor: 'Disabled color, default #c8c9cc.',
      icon: 'Active icon name (Icon component), default star.',
      voidIcon: 'Inactive icon name, default star.',
      allowHalf: 'Enable half-star selection, default false.',
      clearable: 'Allow clearing rating on re-click, default false.',
      readonly: 'Readonly mode.',
      disabled: 'Disabled.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-rate-icon-size': 'Icon size, default 20px.',
      '--sc-rate-gutter': 'Icon gap, default 4px.',
      '--sc-rate-color': 'Active color, default #ee0a24.',
      '--sc-rate-void-color': 'Inactive color, default #c8c9cc.',
      '--sc-rate-disabled-color': 'Disabled color, default #c8c9cc.',
    },
    demo: {
      basic: 'Basic',
      half: 'Half Star',
      count: 'Custom Count',
      color: 'Custom Color',
      clearable: 'Clearable',
      readonly: 'Readonly & Disabled',
      form: 'Form Integration',
    },
    demoDesc: {
      basic: 'value + onChange controlled mode.',
      half: 'allowHalf enables half-star precision (0.5 step).',
      count: 'count={7} with heart icon.',
      color: 'color + voidColor for custom palette.',
      clearable: 'clearable allows re-click to reset rating.',
      readonly: 'readonly for display only, disabled grays out.',
      form: 'Rate auto-binds via useFormField() inside FormItem.',
    },
    intro: 'Rating component using Icon icons. Half-star, custom count/color/icon, clearable, readonly and disabled modes.',
  },
};
