export default {
  rate: {
    props: {
      value: '当前分值（受控）。',
      onChange: '分值变化回调 (value: number) => void。',
      count: '图标总数，默认 5。',
      size: '图标大小（px），默认 20。',
      gutter: '图标间距（px），默认 4。',
      color: '选中时颜色，默认 #ee0a24。',
      voidColor: '未选中时颜色，默认 #c8c9cc。',
      disabledColor: '禁用时颜色，默认 #c8c9cc。',
      icon: '选中时的图标名（对应 Icon 组件 name），默认 star。',
      voidIcon: '未选中时的图标名，默认 star。',
      allowHalf: '是否允许半选，默认 false。',
      clearable: '是否允许再次点击后清除评分，默认 false。',
      readonly: '只读模式。',
      disabled: '禁用。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-rate-icon-size': '图标大小，默认 20px。',
      '--sc-rate-gutter': '图标间距，默认 4px。',
      '--sc-rate-color': '选中颜色，默认 #ee0a24。',
      '--sc-rate-void-color': '未选中颜色，默认 #c8c9cc。',
      '--sc-rate-disabled-color': '禁用颜色，默认 #c8c9cc。',
    },
    demo: {
      basic: '基础用法',
      half: '半星',
      count: '自定义数量',
      color: '自定义颜色',
      clearable: '可清除',
      readonly: '只读 & 禁用',
      form: '表单集成',
    },
    demoDesc: {
      basic: 'value + onChange 受控模式，点击打分。',
      half: 'allowHalf 启用半星选择，精确到 0.5。',
      count: 'count={7} 自定义图标数量，用爱心图标。',
      color: 'color + voidColor 自定义配色。',
      clearable: 'clearable 允许再次点击已选星清除评分。',
      readonly: 'readonly 只读展示，disabled 置灰禁用。',
      form: 'Rate 通过 useFormField() 接入 FormItem，自动双向绑定。',
    },
    intro: '评分组件，基于 Icon 图标渲染。支持半星、自定义数量/颜色/图标、可清除、只读和禁用。',
  },
};
