export default {
  button: {
    props: {
      text: '按钮文字。与 children 二选一，text 优先。',
      children: '按钮子元素。text 未提供时生效。',
      type: '按钮语义色：primary / secondary / success / warning / danger / info。',
      variant: '按钮填充方式：solid（实心）、outline（线框）、ghost（透明）。',
      size: '按钮尺寸：xs / sm / md / lg。',
      block: '通栏按钮，宽度撑满父容器。',
      round: '胶囊形状，使用 full 圆角值。',
      hairline: '0.5px 细线边框（实验性）。',
      color: '自定义背景色，优先级高于 variant。',
      textColor: '自定义文字颜色。',
      icon: '图标，支持 Icon 名称字符串或 JSX 元素。',
      iconPosition: '图标相对文字的位置：left / right。',
      disabled: '禁用状态，不可点击。',
      loading: '加载中状态，显示旋转动画并禁用交互。',
      loadingText: '加载中显示的文字，不设置则保留原文字。',
      nativeType: 'HTML button type 属性：button / submit / reset。',
      href: '链接地址。设置后按钮渲染为 a 标签。',
      target: '链接打开方式，仅在 href 存在时生效。',
      onClick: '点击事件回调。禁用或加载中时不触发。',
      class: '自定义 CSS class。',
      style: '内联样式。',
      'aria-label': '无障碍标签，纯图标按钮必须设置。',
    },
    cssVars: {
      '--sc-color-primary': '主色背景（primary 类型）。',
      '--sc-color-primary-hover': '主色悬停态。',
      '--sc-color-primary-active': '主色按下态。',
      '--sc-border-radius-sm': '小按钮圆角（xs/sm）。',
      '--sc-border-radius-md': '中按钮圆角（md）。',
      '--sc-border-radius-lg': '大按钮圆角（lg）。',
      '--sc-border-radius-full': '胶囊圆角（round 模式）。',
    },
    demo: {
      types: '按钮类型',
      sizes: '按钮尺寸',
      variant: '按钮变体',
    },
    demoDesc: {
      button_types: '六种 type：primary / secondary / success / warning / danger / info',
      button_sizes: '四档尺寸：xs (28px) / sm (32px) / md (40px) / lg (48px)',
      button_variants: 'solid / outline / ghost 三种填充方式。',
    },
    intro: '通用的操作触发按钮。支持多种变体风格、四种尺寸、图标、加载态、链接模式及自定义颜色。',
  },
};
