export default {
  select: { props: {
      options: 'Options: { text: string; value: string|number; render?: JSX.Element }[].',
      value: 'Current value (controlled).', onChange: 'Change callback.', onConfirm: 'Confirm callback.', onCancel: 'Cancel callback.',
      show: 'Controlled show. Auto mode: Select renders its own Cell trigger.',
      onUpdateShow: 'Panel visibility callback.', title: 'Panel title.', placeholder: 'Placeholder.',
      cancelText: 'Cancel text.', confirmText: 'Confirm text.',
      visibleItemCount: 'Picker visible count, default 7.', optionHeight: 'Option height.',
      teleport: 'Portal target.', zIndex: 'Custom z-index.',
      class: 'Custom CSS class.', style: 'Inline styles.',
    },
    cssVars: { '--sc-picker-bg': 'Bg (inherits Picker).', '--sc-picker-header-height': 'Header height.', '--sc-picker-item-height': 'Item height.', '--sc-picker-visible-height': 'Visible height.', '--sc-picker-radius': 'Radius.', '--sc-picker-border-color': 'Border color.' },
    demo: { basic: 'Basic', customRender: 'Custom Render', form: 'Form' },
    demoDesc: { basic: 'Controlled mode — Cell + Select.', customRender: 'option.render for rich JSX options.', form: 'Inside FormItem via useFormField().' },
    design: {
      cardTitle: 'Design: Select = Single-Column Picker',
      para1: 'Select is not "another picker" — it\'s just Picker with columns fixed to a single column [options], and value simplified from an array to a single value. 100% Picker underneath.',
      para2: 'Every Picker feature (option rendering, visibleItemCount, inertia control, etc.) works directly on Select — no relearning or dual-source maintenance.',
      whenTitle: 'When to use Picker directly?',
      when1Title: 'Multi-column — ',
      when1Desc: 'For year+month, province+city, or any multi-column cascade, use Picker with tree or flat multi-column mode. Select is single-column only.',
      when2Title: 'Complex options — ',
      when2Desc: 'For disabled options, async loading, or custom confirm/cancel logic, Picker gives finer control.',
      when3Title: 'Non-standard layout — ',
      when3Desc: 'For custom panel height, scroll physics (ratio/swipeDuration), or other low-level params, use Picker directly.',
      summary: 'Select = Picker + single-column options + auto Cell trigger. Simple cases: Select. Complex cases: Picker.',
    },
    intro: 'Dropdown selector built on Picker. Auto mode with Cell trigger, custom option rendering, Form integration.',
  },
};
