export default {
  select: {
    props: {
      options: '选项列表：{ text: string; value: string|number; render?: JSX.Element }[]。',
      value: '当前选中值（受控）。',
      onChange: '值变化回调。',
      onConfirm: '确认按钮回调。',
      onCancel: '取消按钮回调。',
      show: '受控：是否显示面板。不传时自动模式，Select 自带 Cell 触发器。',
      onUpdateShow: '面板显示状态回调（受控模式）。',
      title: '面板标题。',
      placeholder: '未选中时显示的占位文本。',
      cancelText: '取消按钮文字。',
      confirmText: '确认按钮文字。',
      visibleItemCount: 'Picker 可见选项数量，默认 7。',
      optionHeight: 'Picker 选项高度。',
      teleport: 'Picker Portal 挂载目标。',
      zIndex: '自定义层级。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-picker-bg': '面板背景色（继承 Picker）。',
      '--sc-picker-header-height': '头部高度。',
      '--sc-picker-item-height': '选项高度。',
      '--sc-picker-visible-height': '可见区域高度。',
      '--sc-picker-radius': '面板顶部圆角。',
      '--sc-picker-border-color': '分割线颜色。',
    },
    demo: {
      basic: '基础用法',
      customRender: '自定义渲染',
      form: '表单集成',
    },
    demoDesc: {
      basic: '受控模式 — Cell 触发器 + Select，Picker 单列选择。',
      customRender: 'option.render 传入 JSX，实现图标 + 文字等富文本选项。',
      form: '放入 FormItem，通过 useFormField() 自动双向绑定。',
    },
    design: {
      cardTitle: '设计理念：Select 就是一个单列 Picker',
      para1: 'Select 不是"另一个选择器"，它只是把 Picker 的 columns 固定为单列 [options]，value 从数组简化成单个值。底层能力 100% 来自 Picker。',
      para2: '这意味着 Select 的所有 Picker 特性（选项渲染、visibleItemCount、惯性控制等）都直接可用，不需要重新学习和维护。',
      whenTitle: '什么时候直接用 Picker？',
      when1Title: '多列选择 — ',
      when1Desc: '需要年+月、省+市 等多列联动时，直接用 Picker 的树形或扁平多列模式。Select 只能单列。',
      when2Title: '复杂的选项交互 — ',
      when2Desc: '需要禁用特定选项、异步加载选项数据、自定义确认/取消逻辑时，Picker 提供更细粒度的控制。',
      when3Title: '非标准布局 — ',
      when3Desc: '需要自定义面板高度、滚动物理参数（ratio/swipeDuration）等底层参数时，直接用 Picker 更灵活。',
      summary: 'Select = Picker + 单列 options + auto Cell 触发器。简单场景够用，复杂场景直接用 Picker。',
    },
    intro: '下拉选择器，基于 Picker 封装。自动模式自带 Cell 触发器，支持自定义选项渲染和表单集成。',
  },
};
