export default {
  tooltip: {
    props: {
      content: 'Tooltip content. String or JSX.',
      placement: 'Position: top / bottom / left / right. Auto-flips on overflow.',
      trigger: 'Trigger mode: hover (default) / click / focus / manual.',
      open: 'Controlled open state.',
      defaultOpen: 'Default open state (uncontrolled).',
      onOpenChange: 'Callback when open state changes.',
      showArrow: 'Whether to show the triangle arrow, default true.',
      delay: 'Show/hide delay. Number or { show, hide } object, default 200ms.',
      arrowSize: 'Arrow size (px), default 5.',
      offset: 'Distance from trigger (px), excluding arrow, default 6.',
      maxWidth: 'Bubble max width, default 240px.',
      closeable: 'Show close button (✕). Recommended for mobile click.',
      teleport: 'Portal mount target, default document.body.',
      zIndex: 'Bubble z-index, default 1000.',
      class: 'Custom CSS class for the bubble.',
      style: 'Inline style for the bubble.',
    },
    cssVars: {
      '--sc-tooltip-bg': 'Bubble background color.',
      '--sc-tooltip-color': 'Bubble text color.',
      '--sc-tooltip-font-size': 'Bubble font size.',
      '--sc-tooltip-padding': 'Bubble padding.',
      '--sc-tooltip-radius': 'Bubble border radius.',
      '--sc-tooltip-max-width': 'Bubble max width.',
      '--sc-tooltip-arrow-size': 'Triangle arrow size.',
      '--sc-tooltip-z-index': 'Bubble z-index.',
    },
    demo: {
      basic: 'Basic',
      placement: 'Placements',
      trigger: 'Click Trigger',
      custom: 'Custom Content',
      closeable: 'Closeable',
      delay: 'Delay',
      controlled: 'Controlled',
    },
    demoDesc: {
      basic: 'Default hover trigger. Hover to show the tooltip.',
      placement: 'Four positions with auto-flip on viewport overflow.',
      trigger: 'trigger="click" — click to toggle, click outside to dismiss.',
      custom: 'content supports JSX with icons and rich formatting.',
      closeable: 'closeable adds ✕ button, ideal for mobile click scenarios.',
      delay: 'Custom show/hide delay for better UX.',
      controlled: 'trigger="manual" + open/onOpenChange for external control.',
    },
    intro: 'Floating tooltip bubble on hover/click/focus. Auto-flip positioning, CSS triangle arrow, delay control, Portal rendering.',
  },
};
