export default {
  tooltip: {
    props: {
      content: '气泡内容，支持字符串或 JSX。',
      placement: '弹出方向：top / bottom / left / right，空间不足时自动翻转。',
      trigger: '触发方式：hover（默认）/ click / focus / manual。',
      open: '受控模式：是否显示。',
      defaultOpen: '非受控模式默认状态。',
      onOpenChange: '状态变化回调。',
      showArrow: '是否显示三角箭头，默认 true。',
      delay: '显示/隐藏延迟，number 或 { show, hide } 对象，默认 200ms。',
      arrowSize: '箭头大小 (px)，默认 5。',
      offset: '气泡距触发元素的间距 (px)，不含箭头，默认 6。',
      maxWidth: '气泡最大宽度，默认 240px。',
      closeable: '显示关闭按钮（✕），移动端 click 场景推荐。',
      teleport: 'Portal 挂载目标，默认 document.body。',
      zIndex: '气泡层级，默认 1000。',
      class: '气泡自定义 CSS class。',
      style: '气泡内联样式。',
    },
    cssVars: {
      '--sc-tooltip-bg': '气泡背景色。',
      '--sc-tooltip-color': '气泡文字颜色。',
      '--sc-tooltip-font-size': '气泡字号。',
      '--sc-tooltip-padding': '气泡内边距。',
      '--sc-tooltip-radius': '气泡圆角。',
      '--sc-tooltip-max-width': '气泡最大宽度。',
      '--sc-tooltip-arrow-size': '三角箭头大小。',
      '--sc-tooltip-z-index': '气泡层级。',
    },
    demo: {
      basic: '基础用法',
      placement: '多方向',
      trigger: 'Click 触发',
      custom: '自定义内容',
      closeable: '可关闭',
      delay: '延迟控制',
      controlled: '受控模式',
    },
    demoDesc: {
      basic: '默认 hover 触发，悬停显示气泡。',
      placement: '支持四个方向，空间不足时自动翻转。',
      trigger: 'trigger="click" 点击切换，点击外部关闭。',
      custom: 'content 支持 JSX，可嵌入图标。',
      closeable: 'closeable 显示关闭按钮，适合移动端。',
      delay: '自定义显示/隐藏延迟。',
      controlled: 'trigger="manual" + open/onOpenChange 外部控制。',
    },
    intro: '气泡提示组件，hover/click/focus 时在触发元素旁弹出气泡。内置自动翻转定位、CSS 三角箭头、延迟控制，通过 Portal 渲染避免层级遮挡。',
  },
};
