export default {
  tabbar: {
    props: {
      value: 'Currently selected tab (controlled).',
      defaultValue: 'Default selected (uncontrolled).',
      onChange: 'Tab change callback.',
      fixed: 'Fixed at bottom, default true.',
      border: 'Show top border.',
      zIndex: 'Element z-index.',
      height: 'Tab bar height, default 50px.',
      activeColor: 'Active tab color.',
      inactiveColor: 'Inactive tab color.',
      safeArea: 'Bottom safe area padding.',
      bgColor: 'Custom background. Supports gradients.',
      placeholder: 'Generate equal-height placeholder when fixed.',
      beforeChange: 'Before-change guard, return false to prevent.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    itemProps: {
      name: 'Tab identifier (required).',
      icon: 'Icon: built-in name, JSX element, or (active) => JSX function.',
      label: 'Tab label text.',
      dot: 'Show red dot.',
      badge: 'Badge content (number/string).',
      badgeProps: 'Badge custom props, forwarded to Badge component.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    demo: {
      basic: 'Basic',
      badge: 'Badge & Dot',
      color: 'Custom Color',
      animated: 'Animated Icon',
      fixed: 'Fixed Bottom',
    },
    demoDesc: {
      basic: 'Three bottom tabs with icon and label.',
      badge: 'Use badge and dot for unread counts or status.',
      color: 'Customize via activeColor and bgColor.',
      animated: 'Icon supports ({ active }) => JSX. Active tab gets scale + fill CSS animation — works with Lottie, Rive, or any animation lib.',
      fixed: 'Fixed to bottom with placeholder for native app feel.',
    },
    design: {
      cardTitle: 'Design: No Router Coupling',
      para1: 'TabBar does not implement any routing logic. A component library\'s job is the UI layer; routing is the application layer\'s responsibility.',
      whyTitle: 'Why no built-in routing?',
      whyDesc: 'We cannot know whether or which router your project uses. Built-in routing would become a burden:',
      reason1Title: 'Non-router scenarios — ',
      reason1Desc: 'Many pages don\'t need routing. TabBar works as a pure UI switcher for toggles, settings panels, modals, etc.',
      reason2Title: 'Router diversity — ',
      reason2Desc: 'Your project might use @solidjs/router, tanstack-solid-router, or no router at all. A component library should not care about your router choice.',
      reason3Title: 'Separation of concerns — ',
      reason3Desc: 'Components do UI, the application does routing. TabBar exposes onChange / beforeChange; you handle navigation in your layer.',
      summary: 'Simple, flexible, non-intrusive. TabBar does one thing well: tab switch UI. Routing is yours.',
    },
    intro: 'Mobile bottom tab navigation with icon+text, badge/dot, custom colors, and animated icons.',
  },
};
