export default {
  tabbar: {
    props: {
      value: '当前选中标签（受控）。',
      defaultValue: '默认选中（非受控）。',
      onChange: '切换回调。',
      fixed: '是否固定在底部，默认 true。',
      border: '是否显示顶部分割线。',
      zIndex: '元素 z-index。',
      height: '标签栏高度，默认 50px。',
      activeColor: '选中标签颜色。',
      inactiveColor: '未选中标签颜色。',
      safeArea: '底部安全区域占位。',
      bgColor: '自定义背景色，支持渐变。',
      placeholder: 'fixed 时生成等高占位，防止内容被遮挡。',
      beforeChange: '切换前回调，返回 false 阻止。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    itemProps: {
      name: '标签标识符（必填）。',
      icon: '图标：内置图标名、JSX 元素或 (active) => JSX 函数。',
      label: '标签文字。',
      dot: '显示小红点。',
      badge: '徽标内容（数字/字符串）。',
      badgeProps: '自定义徽标属性，透传给 Badge 组件。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    demo: {
      basic: '基础用法',
      badge: '徽标与红点',
      color: '自定义颜色',
      animated: '动画图标',
      fixed: '固定底部',
    },
    demoDesc: {
      basic: '三个底部标签，点击切换。',
      badge: '通过 badge 和 dot 展示未读消息或状态提示。',
      color: '通过 activeColor 和 bgColor 自定义主题。',
      animated: 'icon 支持 ({ active }) => JSX 函数，自动注入选中态，实现 CSS 动画图标。',
      fixed: 'fixed 固定在底部并占位，模拟原生 App 导航。',
    },
    design: {
      cardTitle: '设计理念：不耦合路由',
      para1: 'TabBar 组件本身不实现任何路由跳转逻辑，也不依赖任何路由库。组件库的职责是提供 UI 交互层，路由是应用层的职责。',
      whyTitle: '为什么不内置路由？',
      whyDesc: '我们无法确定你的项目是否使用了路由、使用了哪个路由方案。组件库如果内置路由逻辑，反而会成为一种负担：',
      reason1Title: '「非路由场景」—— ',
      reason1Desc: '很多页面不需要路由（如功能开关、设置面板、弹窗内切换），TabBar 只作为 UI 切换器使用。',
      reason2Title: '「路由方案不统一」—— ',
      reason2Desc: '项目可能用 @solidjs/router、tanstack-solid-router，或者不用路由。组件库无法预知也不应该关心。',
      reason3Title: '「关注点分离」—— ',
      reason3Desc: '组件层做 UI，应用层做路由。TabBar 通过 onChange / beforeChange 暴露切换事件，你在应用层处理跳转即可。',
      summary: '简单、灵活、无侵入。TabBar 只做好一件事：标签切换的 UI 交互。路由的事，交给你。',
    },
    intro: '移动端底部标签导航栏，支持图标+文字、徽标红点、自定义颜色和动画图标。',
  },
};
