export default {
  picker: {
    props: {
      columns: 'Column data: PickerOption[] (single) or PickerOption[][] (multi). Supports tree cascade via children.',
      value: 'Current selected values (controlled).',
      onChange: 'Selection change callback.',
      onConfirm: 'Confirm button callback with (items, values).',
      onCancel: 'Cancel button callback.',
      show: 'Whether visible (controlled). When omitted, auto mode: Picker renders its own Cell trigger.',
      onUpdateShow: 'Show state change callback.',
      title: 'Title text.',
      cancelText: 'Cancel button text.',
      confirmText: 'Confirm button text.',
      visibleItemCount: 'Visible item count, default 7.',
      optionHeight: 'Option height (px), default 50.',
      ratio: 'Momentum swipe ratio, default 1.5.',
      swipeDuration: 'Swipe animation duration limit (s), default 1.',
      teleport: 'Portal mount target.',
      zIndex: 'Custom z-index.',
      placeholders: 'Placeholder text, string or string[].',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-picker-bg': 'Sheet background color.',
      '--sc-picker-header-height': 'Header height.',
      '--sc-picker-item-height': 'Item height.',
      '--sc-picker-visible-height': 'Visible area height.',
      '--sc-picker-radius': 'Sheet top border radius.',
      '--sc-picker-border-color': 'Border color.',
    },
    demo: {
      city: 'Cascade',
      date: 'Date',
      time: 'Time',
      disabled: 'Disabled',
      placeholder: 'Placeholder',
      controlled: 'Controlled',
    },
    demoDesc: {
      city: 'Tree cascade — select province then city.',
      date: 'Flat multi-column for year + month.',
      time: 'Hour + minute dual columns.',
      disabled: 'Items can be disabled and grayed out.',
      placeholder: 'Placeholder shown when no title.',
      controlled: 'Preset value via value prop.',
    },
    optionProps: {
      text: 'Display text.',
      value: 'Selected value.',
      children: 'Child options for Tree cascade.',
      disabled: 'Whether disabled.',
      className: 'Custom class name.',
      render: 'Custom render, overrides text when set.',
    },
    renderDemo: 'Custom Render',
    renderDesc: 'Use the render prop on options to display any JSX — icons, colors, badges, etc.',
    inertia: 'Inertia Control',
    inertiaDesc: 'ratio controls inertia strength, swipeDuration limits animation time.',
    intro: 'Scroll-wheel selector with Tree cascade and Flat multi-column support.',
  },
};
