export default {
  picker: {
    props: {
      columns: '列数据：PickerOption[]（单列）或 PickerOption[][]（多列），支持 children 树形级联。',
      value: '当前选中值数组（受控）。',
      onChange: '选中值变化回调。',
      onConfirm: '点击确认按钮回调，参数为 (items, values)。',
      onCancel: '点击取消按钮回调。',
      show: '是否显示（受控）。不传时自动模式：Picker 自带 Cell 触发器，点击弹出面板。',
      onUpdateShow: '显示状态变化回调。',
      title: '标题文字。',
      cancelText: '取消按钮文字。',
      confirmText: '确认按钮文字。',
      visibleItemCount: '可见选项数量，默认 7。',
      optionHeight: '选项高度 (px)，默认 50。',
      ratio: '惯性滑动倍率，默认 1.5。',
      swipeDuration: '滑动动画时长限制 (s)，默认 1。',
      teleport: 'Portal 挂载目标。',
      zIndex: '自定义层级。',
      placeholders: '占位文字，string 或 string[]。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-picker-bg': '面板背景色。',
      '--sc-picker-header-height': '头部高度。',
      '--sc-picker-item-height': '选项高度。',
      '--sc-picker-visible-height': '可见区域高度。',
      '--sc-picker-radius': '面板顶部圆角。',
      '--sc-picker-border-color': '分割线颜色。',
    },
    demo: {
      city: '级联选择',
      date: '日期选择',
      time: '时间选择',
      disabled: '禁用选项',
      placeholder: '占位模式',
      controlled: '受控模式',
    },
    demoDesc: {
      city: '树形级联，选择省份后联动城市/区县。',
      date: '扁平多列，年 + 月独立滚轮。',
      time: '时 + 分双列选择。',
      disabled: '选项可被禁用，灰色不可选。',
      placeholder: '不传标题时展示占位文字。',
      controlled: '通过 value 属性预设选中值。',
    },
    renderDemo: '自定义渲染',
    renderDesc: 'option 的 render 属性可传入任意 JSX，实现图标+文字等富文本选项。',
    inertia: '惯性控制',
    inertiaDesc: 'ratio 控制惯性强度，swipeDuration 限制动画时长。',
    optionProps: {
      text: '显示文本。',
      value: '选中值。',
      children: '子选项，用于 Tree 级联。',
      disabled: '是否禁用。',
      className: '自定义类名。',
      render: '自定义渲染，设置后替代 text 显示。',
    },
  },
};
