/**
 * This script reads the current doc-dictionaries.ts and adds the
 * componentProps section with all prop descriptions.
 * Run: npx tsx docs-dev/build-props-dict.ts
 *
 * It outputs the new doc-dictionaries.ts content to stdout.
 * Pipe to file: npx tsx docs-dev/build-props-dict.ts > docs-dev/doc-dictionaries-new.ts
 * Then replace the file manually.
 */

const zhCN: Record<string, Record<string, string>> = {
  // ── Picker ──
  picker: {
    columns: '数据源。支持 tree 级联和 flat 多列两种模式。',
    value: '当前选中值（每列一个，按列顺序排列）。',
    onChange: '滚动停止后回调，参数 (selectedItems: PickerOption[], values: (string|number)[])。',
    onConfirm: '确认按钮点击回调。',
    onCancel: '取消按钮点击回调。',
    show: '受控模式：是否显示面板。不传时 Picker 自动管理。',
    onUpdateShow: '面板开关回调。',
    title: '面板标题。',
    cancelText: '取消按钮文字。默认跟随 locale。',
    confirmText: '确认按钮文字。默认跟随 locale。',
    visibleItemCount: '可见行数（奇数），默认 7。',
    optionHeight: '每行高度 (px)，默认 50。',
    teleport: 'Portal 挂载目标，默认 document.body。',
    zIndex: '层级，默认 2000。',
    placeholders: '每列顶部占位提示文字，string 应用于所有列，string[] 按列指定。',
    ratio: '触摸灵敏度倍率，默认 1.5。值越大滑动越灵敏。',
    swipeDuration: '惯性滚动持续时长（秒），默认 1。',
  },

  // ── DatePicker ──
  datepicker: {
    value: '当前值，格式 YYYY-MM-DD 或 YYYY-MM-DD HH:mm:ss（datetime 模式）。',
    onChange: '值变化回调。',
    onConfirm: '确认按钮回调。',
    onCancel: '取消按钮回调。',
    startDate: '可选范围起点，默认 2014-01-01。',
    endDate: '可选范围终点，默认 2034-12-31。',
    type: '选择类型。date 年月日，year-month 年月，datetime 日期+时间（时/分/秒）。',
    placeholder: '占位文字。',
    title: '面板标题。',
    cancelText: '取消按钮文字。',
    confirmText: '确认按钮文字。',
    disabledDate: '禁用特定日期。传入 (year, month, day)，返回 true 则该日不可选。',
    visibleItemCount: '可见行数。',
    teleport: 'Picker 的 Portal 挂载目标，默认 document.body。',
    show: '受控模式：是否显示面板。不传时 DatePicker 自动管理。',
    onUpdateShow: '受控模式：面板开关回调。',
  },

  // ── TimePicker ──
  timepicker: {
    value: '当前选中时间，格式 HH:mm:ss。',
    onChange: '滚动停止后回调。',
    onConfirm: '确认回调。',
    onCancel: '取消回调。',
    show: '受控：是否显示面板。不传则自带 Cell 触发器。',
    onUpdateShow: '面板开关回调。',
    placeholder: '未选值时显示的占位文本。',
    title: '面板标题。',
    visibleItemCount: '可见行数（奇数）。',
    optionHeight: '每行高度 (px)。',
    cancelText: '取消按钮文字。',
    confirmText: '确认按钮文字。',
    teleport: 'Portal 挂载目标。',
  },

  // ── Form ──
  form: {
    value: '受控值。',
    onChange: '值变化回调。',
    defaultValue: '非受控默认值，默认 {}。',
    onSubmit: '提交回调。',
    validateOnChange: '字段变化时校验。',
    validateOnBlur: '字段失焦时校验。',
    disabled: '全局禁用。',
    readonly: '全局只读。',
    labelAlign: '标签对齐方式：top / left / right。',
    labelWidth: '标签固定宽度，如 "6em"。',
    colon: '标签后加冒号。',
    ref: '组件挂载回调，接收 { setFormValue, resetFormValue, submit, validateAll }。可用于外部重置表单等场景。',
  },
  formItem: {
    name: '字段名，对应 formValue 的 key（必填）。',
    label: '标签文本。',
    required: '必填标记（红色星号）。',
    rules: '校验规则数组。',
    help: '帮助文本（无错误时展示）。',
    labelAlign: '标签对齐方式，继承 Form。',
    labelWidth: '标签固定宽度，继承 Form。',
    contentFlex: '内容区 flex: 1 撑满。',
  },

  // ── Upload ──
  upload: {
    type: '展示类型。image 缩略图网格，file 文件列表。',
    accept: '接受的文件类型，同 <input accept>。',
    multiple: '是否允许多选。',
    maxCount: '最大文件数，达到后隐藏添加按钮。',
    capture: '调用系统相机：environment 后置 / user 前置。',
    maxSize: '单文件大小上限 (bytes)。',
    beforeUpload: '上传前置校验，return false 跳过该文件。',
    api: '上传函数。必须返回文件 URL 用于反显。不传则只管理文件列表。',
    fileList: '受控文件列表。',
    defaultFileList: '非受控初始文件列表。',
    onChange: '列表变化回调（添加 / 删除 / 状态变更 / 进度更新）。',
    onSuccess: '单个文件上传成功回调。',
    onError: '单个文件上传失败回调。',
    onDelete: '删除前回调，return false 阻止删除。',
    disabled: '禁用上传。',
    iconMap: '文件后缀到图标映射。',
    children: '自定义添加按钮。',
    renderFile: '自定义文件项渲染。',
  },

  // ── Button ──
  button: {
    text: '按钮文字。与 children 二选一，text 优先。',
    children: '按钮子元素。text 未提供时生效。',
    type: '按钮语义色：primary / secondary / success / warning / danger / info。',
    variant: '按钮填充方式。solid 实心，outline 线框，ghost 透明。',
    size: '按钮尺寸：xs / sm / md / lg。',
    block: '通栏按钮，宽度撑满父容器。',
    round: '胶囊形状，使用 full 圆角值。',
    hairline: '0.5px 细线边框（实验性）。',
    color: '自定义背景色，优先级高于 variant。',
    textColor: '自定义文字颜色。',
    icon: '图标元素。支持传入任意 JSX。',
    iconPosition: '图标相对文字的位置：left / right。',
    disabled: '禁用状态，不可点击。',
    loading: '加载中状态，显示旋转动画并禁用交互。',
    loadingText: '加载中显示的文字，不设置则保留原文字。',
    nativeType: 'HTML button type 属性：button / submit / reset。',
    href: '链接地址。设置后按钮渲染为 a 标签。',
    target: '链接打开方式，仅在 href 存在时生效。',
    onClick: '点击事件回调。禁用或加载中时不触发。',
    class: '自定义 CSS class。',
    style: '内联样式。',
    'aria-label': '无障碍标签，纯图标按钮必须设置。',
  },

  // ── Input ──
  input: {
    type: '输入类型：text / number / password / tel / email / url。',
    value: '当前值（受控）。',
    onChange: '值变化回调。',
    defaultValue: '默认值（非受控）。',
    placeholder: '占位文本。',
    maxlength: '最大长度。',
    clearable: '显示清除按钮。',
    disabled: '禁用。',
    readonly: '只读。',
    showCount: '显示字数统计（需配合 maxlength）。',
    prefix: '左侧图标/文本。',
    suffix: '右侧图标/文本。',
    align: '文字对齐：left / center / right。',
    onBlur: '失焦回调。',
    onFocus: '聚焦回调。',
    onEnter: '回车回调。',
  },

  // ── Textarea ──
  textarea: {
    value: '当前值（受控）。',
    onChange: '值变化回调。',
    defaultValue: '默认值（非受控）。',
    placeholder: '占位文本。',
    maxlength: '最大长度。',
    rows: '可视行数，默认 3。',
    autoSize: '自动撑高，内容超出时扩展。可传 { minRows, maxRows } 限制范围。',
    clearable: '显示清除按钮。',
    disabled: '禁用。',
    readonly: '只读。',
    showCount: '显示字数统计。',
    error: '错误状态，出现红色波浪线。',
    onBlur: '失焦回调。',
    onFocus: '聚焦回调。',
    onEnter: '回车回调（Shift+Enter 换行）。',
  },

  // ── Switch ──
  switch: {
    checked: '是否打开（受控模式）。',
    value: 'checked 的别名。',
    defaultChecked: '默认状态（非受控模式）。',
    onChange: '状态变化回调。',
    disabled: '是否禁用。',
    size: '尺寸，数字自动补 px，默认 28。',
    activeColor: '打开时的背景色。',
    inactiveColor: '关闭时的背景色。',
    activeText: '打开时显示的文案，在滑块右侧。',
    inactiveText: '关闭时显示的文案，在滑块右侧。',
    class: '自定义 CSS class。',
    style: '内联样式。',
  },

  // ── Select ──
  select: {
    options: '选项列表。',
    value: '当前选中值。',
    onChange: '值变化回调。',
    onConfirm: '确认按钮点击回调。',
    placeholder: '无选中时显示的文字。',
    title: '面板标题。',
    cancelText: '取消按钮文字。',
    confirmText: '确认按钮文字。',
    visibleItemCount: '可见行数，默认 7。',
    teleport: 'Portal 挂载目标。',
    show: '是否显示选择器面板。不传时 Select 自动管理。',
    onUpdateShow: '面板开关回调。',
  },

  // ── Radio & RadioGroup ──
  radio: {
    value: '标识符，选中时对应 RadioGroup 的 value（必填）。',
    label: '标签文字。',
    checked: '独立使用是否选中（受控）。',
    onChange: '独立使用选中变化回调。',
    disabled: '禁用。',
    labelDisabled: '禁用标签点击。',
    labelPosition: '标签位置：left / right。',
    iconSize: '图标大小。',
    checkedColor: '选中态颜色，默认 #1989fa。',
    shape: '形状：round / square / dot。',
    checkedIcon: '自定义选中图标。',
    uncheckedIcon: '自定义未选中图标。',
  },
  radioGroup: {
    value: '当前选中值（受控）。',
    defaultValue: '默认值（非受控）。',
    onChange: '值变化回调。',
    direction: '排列方向：vertical / horizontal。',
    gap: '选项间距。',
    disabled: '全局禁用。',
    iconSize: '图标大小（统一设置）。',
    checkedColor: '选中态颜色（统一设置）。',
    shape: '形状（统一设置）：round / square / dot。',
  },

  // ── Checkbox & CheckboxGroup ──
  checkbox: {
    value: '标识符，选中时对应 CheckboxGroup 的 value（必填）。',
    label: '标签文字。',
    checked: '独立使用是否选中（受控）。',
    defaultChecked: '默认选中（非受控）。',
    indeterminate: '半选状态，选中态图标不覆盖。',
    onChange: '独立使用选中变化回调。',
    disabled: '禁用。',
    labelDisabled: '禁用标签点击。',
    labelPosition: '标签位置：left / right。',
    iconSize: '图标大小。',
    checkedColor: '选中态颜色，默认 #1989fa。',
    shape: '形状：square / round。',
    checkedIcon: '自定义选中图标。',
    uncheckedIcon: '自定义未选中图标。',
    indeterminateIcon: '自定义半选图标。',
  },
  checkboxGroup: {
    value: '当前选中值列表（受控）。',
    defaultValue: '默认值（非受控）。',
    onChange: '值变化回调。',
    direction: '排列方向：vertical / horizontal。',
    gap: '选项间距。',
    disabled: '全局禁用。',
    max: '最大可选数。',
    min: '最少可选数。',
    iconSize: '图标大小（统一设置）。',
    checkedColor: '选中态颜色（统一设置）。',
    shape: '形状（统一设置）：square / round。',
    checkedIcon: '自定义选中图标。',
    uncheckedIcon: '自定义未选中图标。',
  },

  // ── Slider ──
  slider: {
    value: '当前值。count=1 时为数字，count>1 时为数组。',
    onChange: '值变化回调。',
    min: '最小值，默认 0。',
    max: '最大值，默认 100。',
    step: '步长，默认 1。',
    count: '滑块数量。1 为单滑块，2 为双滑块，以此类推。',
    barHeight: '进度条高度。',
    buttonSize: '滑块按钮大小。',
    thumbRender: '自定义滑块按钮渲染。接收当前值和索引，返回字符串/元素则替换默认样式。',
    activeColor: '进度条激活态颜色，默认 #1989fa。',
    inactiveColor: '进度条非激活态颜色，默认 #e5e5e5。',
    reverse: '是否反转。',
    disabled: '禁用。',
    readonly: '只读。',
  },

  // ── Stepper ──
  stepper: {
    value: '当前值（受控）。',
    onChange: '值变化回调。',
    defaultValue: '默认值（非受控）。',
    size: '快捷设置整体尺寸（覆盖 buttonSize/inputWidth 默认值）。',
    min: '最小值。',
    max: '最大值。',
    step: '步长。',
    decimalLength: '小数位数。',
    integer: '整数模式。',
    disabled: '禁用。',
    inputDisabled: '禁用输入框。',
    buttonSize: '按钮大小。',
    inputWidth: '输入框宽度。',
    minusIcon: '自定义减号图标。',
    plusIcon: '自定义加号图标。',
    allowEmpty: '允许空值。',
  },

  // ── Rate ──
  rate: {
    value: '当前分值。',
    onChange: '分值变化回调。',
    count: '图标总数，默认 5。',
    size: '图标大小。',
    gutter: '图标间距。',
    color: '选中时的颜色。',
    voidColor: '未选中时的颜色。',
    disabledColor: '禁用时的颜色。',
    icon: '选中时的图标名，对应 Icon 的 name 属性。',
    voidIcon: '未选中时的图标名。',
    allowHalf: '是否允许半选。',
    clearable: '是否允许再次点击后清除。',
    readonly: '只读。',
    disabled: '禁用。',
  },

  // ── Calendar ──
  calendar: {
    type: '选择模式：single / range / multiple。',
    value: '当前选中值，按 type 不同格式不同。',
    onChange: '值变化回调。',
    popup: '弹出模式。设为 false 平铺展示。',
    show: '弹出层受控显示。',
    title: '弹出层标题。',
    closeable: '显示关闭按钮。',
    minDate: '最小可选日期。',
    maxDate: '最大可选日期。',
    firstDayOfWeek: '一周起始日，0=周日。',
    weekdays: '星期标题数组。',
    titleFormatter: '月份标题格式化函数。',
    activeColor: '选中态颜色。',
    dayRender: '日期格子自定义渲染函数。',
    maxCount: '多选最大天数。',
    maxRange: '范围选择最大跨度（天）。',
    showConfirm: '范围模式确认按钮。',
    readonly: '只读。',
    lunar: '显示农历信息。',
    teleport: '挂载目标。',
  },

  // ── Cascader ──
  cascader: {
    options: '级联数据源，见 CascaderOption。',
    value: '当前选中值。',
    onChange: '值变化回调。',
    title: '标题。',
    placeholder: '未选中的占位文字。',
    closeable: '是否显示关闭按钮。',
    show: '受控显示。',
    onUpdateShow: '关闭回调。',
    onClose: '关闭回调。',
    maxHeight: '弹窗固定高度。',
    showCheckmark: '是否在选中项右侧显示对勾，默认 true。',
    checkmark: '自定义选中图标。',
    teleport: '挂载目标。',
    zIndex: 'z-index。',
  },

  // ── CityPicker ──
  citypicker: {
    columns: '省市区树形数据，用户自行提供。',
    value: '当前选中值（每级一个）。',
    onChange: '值变化回调。',
    onConfirm: '确认按钮回调。',
    onCancel: '取消按钮回调。',
    placeholder: '占位文字。',
    separator: '显示文字分隔符，默认 " / "。',
    title: '面板标题。',
    teleport: 'Portal 挂载目标。',
  },

  // ── Dialog ──
  dialog: {
    show: '是否显示弹窗（受控模式，必填）。',
    title: '标题，支持 string 或 JSX。',
    message: '内容，支持 \\n 换行和 JSX。',
    width: '弹窗宽度。',
    messageAlign: '内容水平对齐：left / center / right。',
    showConfirmButton: '是否展示确认按钮，默认 true。',
    showCancelButton: '是否展示取消按钮，默认 false。',
    confirmText: '确认按钮文案。',
    cancelText: '取消按钮文案。',
    confirmDisabled: '是否禁用确认按钮。',
    cancelDisabled: '是否禁用取消按钮。',
    zIndex: 'z-index 层级，默认 2000。',
    overlay: '是否展示遮罩层，默认 true。',
    closeOnClickOverlay: '点击遮罩是否关闭，默认 false。',
    lockScroll: '是否锁定背景滚动，默认 true。',
    beforeClose: '关闭前回调，返回 false 阻止关闭。',
    onConfirm: '确认回调。',
    onCancel: '取消回调。',
    onClose: '关闭回调。',
    teleport: '挂载目标节点。',
    destroyOnClose: '关闭时销毁内容。',
    lazyRender: '懒渲染，默认 true。',
  },

  // ── ActionSheet ──
  actionsheet: {
    open: '是否显示（必填）。',
    onClose: '关闭回调（必填）。',
    items: '选项列表。',
    title: '标题文字。',
    closeable: '显示关闭图标，默认 false。',
    description: '描述文字，显示在标题下方。',
    cancelText: '取消按钮文字。',
    closeOnSelect: '选中后自动关闭，默认 true。',
    closeOnOverlayClick: '点击遮罩关闭，默认 true。',
    round: '顶部圆角，默认 true。',
  },

  // ── Toast ──
  toast: {
    message: '提示消息内容。',
    type: '类型，决定图标和默认样式：success / error / warning / loading / info。',
    position: '显示位置：top / middle / bottom。',
    duration: '自动关闭的毫秒数，0 表示不自动关闭。',
    overlay: '是否显示半透明遮罩，默认 false。',
    closeOnClick: '点击 toast 自身是否关闭。',
    onClose: '关闭时的回调。',
  },

  // ── PullRefresh ──
  pullrefresh: {
    loading: '受控加载状态，传此属性后由你管理 loading。',
    onRefresh: '刷新回调。返回 Promise 时组件自动等待完成后关闭。',
    pullDistance: '触发刷新的下拉距离 (px)。',
    headHeight: '顶部刷新提示区高度 (px)。',
    successDuration: '加载成功后展示成功状态时长 (ms)。',
    animationDuration: '回弹动画时长 (ms)。',
    disabled: '禁用下拉刷新。',
    pullingText: '下拉文案。',
    loosingText: '释放文案。',
    loadingText: '加载文案。',
    successText: '成功文案。',
  },

  // ── Swiper ──
  swiper: {
    autoplay: '自动轮播间隔 (ms)。',
    duration: '动画时长 (ms)。',
    initialSwipe: '初始位置索引。',
    'width / height': '滑块宽高。',
    loop: '是否循环播放。',
    showIndicators: '是否显示指示器。',
    vertical: '纵向滚动。',
    touchable: '手势滑动。',
    indicatorColor: '指示器颜色。',
    indicators: '自定义指示器渲染函数。',
    imgUrls: '快捷图片数组，传此属性后无需写子组件。',
    lazyRender: '延迟渲染非当前页。',
    onChange: '切换回调。',
  },

  // ── TabBar ──
  tabbar: {
    value: '当前选中标签（受控）。',
    defaultValue: '默认选中（非受控）。',
    onChange: '切换回调。',
    fixed: '是否固定在底部，默认 true。',
    border: '是否显示外边框。',
    zIndex: '元素 z-index。',
    height: '标签栏高度，占位高度同步变化。',
    activeColor: '选中标签颜色。',
    inactiveColor: '未选中标签颜色。',
    safeArea: '底部安全区域占位。',
    bgColor: '自定义背景色，支持渐变、半透明毛玻璃。',
    placeholder: 'fixed 时生成等高占位，防止页面内容被遮挡。',
    beforeChange: '切换前回调，返回 false 阻止。',
  },

  // ── Tabs ──
  tabs: {
    active: '当前激活的 tab（受控）。',
    defaultActive: '默认激活的 tab（非受控）。',
    onChange: '切换回调。',
    type: '样式风格：line / card。',
    color: '主题色。',
    background: '标签栏背景色。',
    duration: '动画时长（秒）。',
    animated: '内容区切换动画。',
    border: '显示外边框（仅 line）。',
    sticky: '粘性定位。',
    lazyRender: '延迟渲染未激活的 tab，默认 true。',
    titleActiveColor: '标题选中态颜色。',
    titleInactiveColor: '标题默认态颜色。',
    beforeChange: '切换前回调，返回 false 阻止切换。',
  },

  // ── NavBar ──
  navbar: {
    title: '标题。',
    left: '左侧自定义内容。',
    right: '右侧自定义内容。',
    backArrow: '是否显示返回箭头。',
    onBack: '返回箭头点击回调。',
    onLeftClick: '左侧区域点击回调。',
    onRightClick: '右侧区域点击回调。',
    fixed: '是否固定在顶部。',
    placeholder: '固定时生成占位元素，避免内容被遮挡。',
    border: '是否显示底部边框。',
    zIndex: 'z-index。',
    background: '背景色。',
    color: '文字颜色。',
    height: '导航栏高度。',
  },

  // ── Cell ──
  cell: {
    title: '左侧标题。',
    value: '右侧内容。',
    description: '标题下方描述。',
    children: '自定义内容，设置后 title/value/description 被忽略。',
    icon: '左侧图标，支持字符串或 JSX。',
    size: '尺寸：xs / sm / md / lg。',
    required: '是否显示必填红色星号。',
    center: '内容垂直居中。',
    clickable: '是否可点击，设为 true 时显示右侧箭头。',
    onClick: '点击回调（仅 clickable 时生效）。',
    class: '自定义 CSS class。',
    style: '内联样式。',
  },
  cellgroup: {
    title: '分组标题。',
    card: '卡片模式（圆角 + 背景色）。',
    border: '是否显示单元格边框。',
    children: 'Cell 子元素。',
    class: '自定义 CSS class。',
    style: '内联样式。',
  },

  // ── Overlay ──
  overlay: {
    open: '控制遮罩显示/隐藏。',
    onClose: '点击背景或按 Escape 时的回调。',
    zIndex: '自定义层级。',
    lockScroll: '是否锁定 body 滚动。',
    mount: 'Portal 挂载目标。',
    duration: '进出动画时长（ms）。',
  },

  // ── Loading ──
  loading: {
    text: '加载文字。与 children 二选一，text 优先。',
    children: '子元素，text 未提供时生效。',
    type: '内置动画类型：spinner / circular / dots。',
    size: '动画尺寸，数字自动补 px。',
    color: '动画颜色。',
    textColor: '文字颜色。',
    vertical: '文字与动画是否纵向排列。',
    overlay: '是否为全屏遮罩模式。',
    icon: '自定义图标，设置后忽略 type。',
    class: '自定义 CSS class。',
    style: '内联样式。',
  },

  // ── Avatar ──
  avatar: {
    src: '头像图片地址。',
    alt: '替代文本（无障碍）。',
    size: '尺寸，预设 xs/sm/md/lg/xl 或自定义 px。',
    round: '完全圆形（与 square 互斥）。',
    square: '方形。传数字控制圆角大小。',
    icon: '无 src 或加载失败时显示的图标。',
    text: '无 src 且无 icon 时的文字（取首字符）。',
    color: '自定义背景色。',
  },

  // ── Badge ──
  badge: {
    content: '徽标内容。数字超出 max 时显示 max+。',
    dot: '仅显示小红点。',
    max: '数字上限，如 99。',
    position: '位置：top-right / top-left / bottom-right / bottom-left。',
    color: '自定义背景色。',
  },

  // ── Tag ──
  tag: {
    type: '语义色：primary / secondary / success / warning / danger / info。',
    variant: '填充方式：solid / outline / ghost。',
    size: '尺寸：xs / sm / md / lg。',
    round: '胶囊圆角。',
    closeable: '是否可关闭。',
    onClose: '关闭回调。',
    color: '自定义颜色。',
  },

  // ── Empty ──
  empty: {
    description: '描述文字。',
    image: '图片：预设类型（default / network / search）或自定义 JSX。',
    children: '自定义底部内容（如按钮）。',
    class: '自定义 CSS class。',
  },

  // ── Image ──
  image: {
    src: '图片地址。',
    alt: '替代文本。',
    width: '宽度。',
    height: '高度。',
    fit: '填充方式：cover / contain / fill / none / scale-down。',
    position: 'object-position 值。',
    radius: '圆角大小。',
    round: '完全圆形。',
    block: '块级元素，宽度撑满。',
    lazy: '启用懒加载。',
    placeholder: '加载中占位。',
    fallback: '加载失败兜底。',
    iconSize: '加载失败时图标大小。',
    onLoad: '加载成功回调。',
    onError: '加载失败回调。',
    preview: '点击预览大图。',
  },

  // ── Icon ──
  icon: {
    name: '图标名称。',
    variant: '线性 / 填充风格：line / fill。',
    size: '尺寸，数字自动补 px。',
    color: '图标颜色。',
    class: '自定义 CSS class。',
    style: '内联样式。',
    id: 'DOM id。',
    'aria-label': '无障碍标签，功能性图标需设置。',
    onClick: '点击事件。',
  },

  // ── Layout (Row / Col) ──
  row: {
    gap: '列间距，数字自动补 px。',
    align: '垂直对齐：top / center / bottom / stretch。',
    justify: '水平分布：start / center / end / space-between / space-around。',
    wrap: '是否换行。',
  },
  col: {
    span: '栅格占位 1-24。',
    offset: '左偏移量。',
  },

  // ── Divider ──
  divider: {
    direction: '方向：horizontal / vertical。',
    text: '中间文字（仅水平模式）。',
    dashed: '虚线样式。',
    color: '线条颜色。',
    size: '线条粗细。',
  },

  // ── SafeArea ──
  safearea: {
    position: '安全区域位置：top / bottom / both。',
  },

  // ── Center ──
  center: {
    flexX: 'Flexbox 水平居中 (justify-content: center)。',
    flexY: 'Flexbox 垂直居中 (align-items: center)。父级需有高度。',
    text: 'text-align: center。适合行内/行内块内容。',
    vertical: 'vertical-align: middle。适合行内元素。',
    position: 'absolute + transform 居中。父级需 position: relative。',
    inline: '行内模式（flex -> inline-flex）。',
    as: '渲染的 HTML 标签，默认 div。',
    class: '自定义 CSS class。',
    style: '内联样式。',
  },

  // ── Lazyload ──
  lazyload: {
    active: '受控模式：外部控制是否激活。',
    placeholder: '未激活时显示的占位内容。',
    children: '激活后渲染的实际内容。',
    rootMargin: '提前触发的距离。',
    height: '最小高度，占位期间撑住布局，避免加载后抖动。',
    threshold: '可见比例阈值 0-1。',
    once: '是否只触发一次，默认 true。',
  },

  // ── List ──
  list: {
    data: '受控模式：外部管理的数据源。',
    onLoad: '非受控模式：触底时调用，返回值追加到列表。',
    finished: '是否已加载完成。',
    children: '渲染每一项的模板函数。',
    empty: '空数据占位。',
    loadMoreText: '加载中底部提示。',
    finishedText: '全部加载完成底部提示。',
    offset: '距底部多少 px 触发 onLoad。',
    virtual: '开启虚拟列表。',
    itemHeight: '虚拟列表模式下每项的固定高度 (px)。',
    pullRefresh: '开启下拉刷新，配合 onRefresh。',
    onRefresh: '下拉刷新回调。',
  },

  // ── Notify ──
  notify: {
    type: '类型：primary / success / warning / danger。',
    message: '展示文案，支持 \\n 换行。',
    duration: '展示时长 (ms)，0 不消失。',
    position: '弹出位置：top / bottom。',
    color: '字体颜色。',
    background: '背景颜色。',
    lockScroll: '锁定背景滚动。',
    onClick: '点击回调。',
    onClose: '关闭回调。',
  },

  // ── SwipeCell ──
  swipecell: {
    rightActions: '右侧滑出按钮。',
    leftActions: '左侧滑出按钮。',
    threshold: '触发打开的滑动阈值 (px)。',
    actionsWidth: '按钮区域宽度 (px)。',
    disabled: '是否禁用。',
    onOpen: '打开时回调。',
    onClose: '关闭时回调。',
    children: '内容层，最常用 Cell。',
    class: '自定义类名。',
    style: '内联样式。',
  },
};

// ── English translations ──
const enUS: Record<string, Record<string, string>> = {
  picker: {
    columns: 'Data source. Supports tree cascade and flat multi-column modes.',
    value: 'Currently selected values (one per column, in column order).',
    onChange: 'Fires on scroll stop with (selectedItems: PickerOption[], values: (string|number)[]).',
    onConfirm: 'Fires when confirm button is clicked.',
    onCancel: 'Fires when cancel button is clicked or overlay clicked.',
    show: 'Controlled: show the panel. Picker auto-manages when not provided.',
    onUpdateShow: 'Panel visibility callback.',
    title: 'Panel title.',
    cancelText: 'Cancel button text. Defaults to locale.',
    confirmText: 'Confirm button text. Defaults to locale.',
    visibleItemCount: 'Visible row count (odd number), default 7.',
    optionHeight: 'Row height (px), default 50.',
    teleport: 'Portal mount target, default document.body.',
    zIndex: 'Stack level, default 2000.',
    placeholders: 'Placeholder text at top of each column. String applies to all, string[] per column.',
    ratio: 'Touch sensitivity multiplier, default 1.5. Higher = more sensitive.',
    swipeDuration: 'Inertia scroll duration (seconds), default 1.',
  },
  datepicker: {
    value: 'Current value, format YYYY-MM-DD or YYYY-MM-DD HH:mm:ss (datetime mode).',
    onChange: 'Value change callback.',
    onConfirm: 'Confirm button callback.',
    onCancel: 'Cancel button callback.',
    startDate: 'Start of selectable range, default 2014-01-01.',
    endDate: 'End of selectable range, default 2034-12-31.',
    type: 'Selection type. date=year/month/day, year-month=year/month, datetime=date+time.',
    placeholder: 'Placeholder text.',
    title: 'Panel title.',
    cancelText: 'Cancel button text.',
    confirmText: 'Confirm button text.',
    disabledDate: 'Disable specific dates. Function (year, month, day) => boolean.',
    visibleItemCount: 'Visible row count.',
    teleport: 'Picker portal mount target, default document.body.',
    show: 'Controlled: show the panel. DatePicker auto-manages when not provided.',
    onUpdateShow: 'Panel visibility callback for controlled mode.',
  },
  timepicker: {
    value: 'Current time, format HH:mm:ss.',
    onChange: 'Fires when scroll stops.',
    onConfirm: 'Confirm callback.',
    onCancel: 'Cancel callback.',
    show: 'Controlled: show the panel. Has built-in Cell trigger when not provided.',
    onUpdateShow: 'Panel visibility callback.',
    placeholder: 'Placeholder text when no value selected.',
    title: 'Panel title.',
    visibleItemCount: 'Visible row count (odd number).',
    optionHeight: 'Row height (px).',
    cancelText: 'Cancel button text.',
    confirmText: 'Confirm button text.',
    teleport: 'Portal mount target.',
  },
  form: {
    value: 'Controlled form value.',
    onChange: 'Value change callback.',
    defaultValue: 'Uncontrolled default value, default {}.',
    onSubmit: 'Submit callback.',
    validateOnChange: 'Validate on field change.',
    validateOnBlur: 'Validate on field blur.',
    disabled: 'Disable all fields.',
    readonly: 'Readonly for all fields.',
    labelAlign: 'Label alignment: top / left / right.',
    labelWidth: 'Fixed label width, e.g. "6em".',
    colon: 'Append colon after label.',
    ref: 'Mount callback, receives { setFormValue, resetFormValue, submit, validateAll }.',
  },
  formItem: {
    name: 'Field name, maps to formValue key (required).',
    label: 'Label text.',
    required: 'Show required indicator (red asterisk).',
    rules: 'Validation rules array.',
    help: 'Help text shown when no error.',
    labelAlign: 'Label alignment, inherits from Form.',
    labelWidth: 'Fixed label width, inherits from Form.',
    contentFlex: 'Make content area flex: 1 to fill remaining space.',
  },
  upload: {
    type: 'Display type. image=thumbnail grid, file=file list.',
    accept: 'Accepted file types, same as <input accept>.',
    multiple: 'Allow multi-select.',
    maxCount: 'Max file count. Add button hidden when reached.',
    capture: 'Invoke system camera: environment (rear) / user (front).',
    maxSize: 'Max single file size (bytes).',
    beforeUpload: 'Pre-upload guard. Return false to skip the file.',
    api: 'Upload function. Must return file URL for display. Only manages list if not provided.',
    fileList: 'Controlled file list.',
    defaultFileList: 'Uncontrolled initial file list.',
    onChange: 'File list change callback (add/delete/status/progress).',
    onSuccess: 'Single file upload success callback.',
    onError: 'Single file upload error callback.',
    onDelete: 'Pre-delete guard. Return false to prevent deletion.',
    disabled: 'Disable upload.',
    iconMap: 'File extension to icon mapping.',
    children: 'Custom add button.',
    renderFile: 'Custom file item render.',
  },
  button: {
    text: 'Button text. Takes precedence over children.',
    children: 'Button children. Used when text not provided.',
    type: 'Semantic color: primary / secondary / success / warning / danger / info.',
    variant: 'Fill style. solid=filled, outline=bordered, ghost=transparent.',
    size: 'Size: xs / sm / md / lg.',
    block: 'Full-width button, fills parent container.',
    round: 'Pill shape with full border-radius.',
    hairline: '0.5px hairline border (experimental).',
    color: 'Custom background color, overrides variant.',
    textColor: 'Custom text color.',
    icon: 'Icon element. Accepts any JSX.',
    iconPosition: 'Icon position relative to text: left / right.',
    disabled: 'Disabled state, not interactive.',
    loading: 'Loading state, shows spinner and disables interaction.',
    loadingText: 'Text shown during loading. Keeps original text if not set.',
    nativeType: 'HTML button type: button / submit / reset.',
    href: 'Link URL. Renders as <a> when set.',
    target: 'Link target, only effective when href is set.',
    onClick: 'Click callback. Not fired when disabled or loading.',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
    'aria-label': 'Accessibility label. Required for icon-only buttons.',
  },
  input: {
    type: 'Input type: text / number / password / tel / email / url.',
    value: 'Current value (controlled).',
    onChange: 'Value change callback.',
    defaultValue: 'Default value (uncontrolled).',
    placeholder: 'Placeholder text.',
    maxlength: 'Max length.',
    clearable: 'Show clear button.',
    disabled: 'Disabled.',
    readonly: 'Readonly.',
    showCount: 'Show character count (requires maxlength).',
    prefix: 'Left icon/text.',
    suffix: 'Right icon/text.',
    align: 'Text alignment: left / center / right.',
    onBlur: 'Blur callback.',
    onFocus: 'Focus callback.',
    onEnter: 'Enter key callback.',
  },
  textarea: {
    value: 'Current value (controlled).',
    onChange: 'Value change callback.',
    defaultValue: 'Default value (uncontrolled).',
    placeholder: 'Placeholder text.',
    maxlength: 'Max length.',
    rows: 'Visible rows, default 3.',
    autoSize: 'Auto-resize as content grows. Can pass { minRows, maxRows } to limit.',
    clearable: 'Show clear button.',
    disabled: 'Disabled.',
    readonly: 'Readonly.',
    showCount: 'Show character count.',
    error: 'Error state, shows red wavy underline.',
    onBlur: 'Blur callback.',
    onFocus: 'Focus callback.',
    onEnter: 'Enter key callback (Shift+Enter for newline).',
  },
  switch: {
    checked: 'Whether switch is on (controlled mode).',
    value: 'Alias for checked.',
    defaultChecked: 'Default state (uncontrolled mode).',
    onChange: 'State change callback.',
    disabled: 'Whether disabled.',
    size: 'Size, numbers auto-suffixed with px, default 28.',
    activeColor: 'Background color when on.',
    inactiveColor: 'Background color when off.',
    activeText: 'Text shown when on, right of thumb.',
    inactiveText: 'Text shown when off, right of thumb.',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
  },
  select: {
    options: 'Options list.',
    value: 'Currently selected value.',
    onChange: 'Value change callback.',
    onConfirm: 'Confirm button callback.',
    placeholder: 'Text when no selection.',
    title: 'Panel title.',
    cancelText: 'Cancel button text.',
    confirmText: 'Confirm button text.',
    visibleItemCount: 'Visible row count, default 7.',
    teleport: 'Portal mount target.',
    show: 'Controlled: show the selector. Select auto-manages when not provided.',
    onUpdateShow: 'Panel visibility callback.',
  },
  radio: {
    value: 'Identifier, corresponds to RadioGroup value when selected (required).',
    label: 'Label text.',
    checked: 'Whether checked when used standalone (controlled).',
    onChange: 'Change callback when used standalone.',
    disabled: 'Disabled.',
    labelDisabled: 'Disable label click.',
    labelPosition: 'Label position: left / right.',
    iconSize: 'Icon size.',
    checkedColor: 'Checked color, default #1989fa.',
    shape: 'Shape: round / square / dot.',
    checkedIcon: 'Custom checked icon.',
    uncheckedIcon: 'Custom unchecked icon.',
  },
  radioGroup: {
    value: 'Currently selected value (controlled).',
    defaultValue: 'Default value (uncontrolled).',
    onChange: 'Value change callback.',
    direction: 'Layout direction: vertical / horizontal.',
    gap: 'Item spacing.',
    disabled: 'Disable all items.',
    iconSize: 'Icon size (applied uniformly).',
    checkedColor: 'Checked color (applied uniformly).',
    shape: 'Shape (applied uniformly): round / square / dot.',
  },
  checkbox: {
    value: 'Identifier, corresponds to CheckboxGroup value when selected (required).',
    label: 'Label text.',
    checked: 'Whether checked when used standalone (controlled).',
    defaultChecked: 'Default checked (uncontrolled).',
    indeterminate: 'Indeterminate state, check icon not shown.',
    onChange: 'Change callback when used standalone.',
    disabled: 'Disabled.',
    labelDisabled: 'Disable label click.',
    labelPosition: 'Label position: left / right.',
    iconSize: 'Icon size.',
    checkedColor: 'Checked color, default #1989fa.',
    shape: 'Shape: square / round.',
    checkedIcon: 'Custom checked icon.',
    uncheckedIcon: 'Custom unchecked icon.',
    indeterminateIcon: 'Custom indeterminate icon.',
  },
  checkboxGroup: {
    value: 'Currently selected values array (controlled).',
    defaultValue: 'Default values (uncontrolled).',
    onChange: 'Value change callback.',
    direction: 'Layout direction: vertical / horizontal.',
    gap: 'Item spacing.',
    disabled: 'Disable all items.',
    max: 'Maximum selectable count.',
    min: 'Minimum selectable count.',
    iconSize: 'Icon size (applied uniformly).',
    checkedColor: 'Checked color (applied uniformly).',
    shape: 'Shape (applied uniformly): square / round.',
    checkedIcon: 'Custom checked icon.',
    uncheckedIcon: 'Custom unchecked icon.',
  },
  slider: {
    value: 'Current value. Number when count=1, array when count>1.',
    onChange: 'Value change callback.',
    min: 'Minimum value, default 0.',
    max: 'Maximum value, default 100.',
    step: 'Step size, default 1.',
    count: 'Number of thumbs. 1=single, 2=dual, etc.',
    barHeight: 'Track height.',
    buttonSize: 'Thumb button size.',
    thumbRender: 'Custom thumb render function. Receives (value, index).',
    activeColor: 'Active track color, default #1989fa.',
    inactiveColor: 'Inactive track color, default #e5e5e5.',
    reverse: 'Reverse direction.',
    disabled: 'Disabled.',
    readonly: 'Readonly.',
  },
  stepper: {
    value: 'Current value (controlled).',
    onChange: 'Value change callback.',
    defaultValue: 'Default value (uncontrolled).',
    size: 'Quick size preset, overrides buttonSize/inputWidth defaults.',
    min: 'Minimum value.',
    max: 'Maximum value.',
    step: 'Step size.',
    decimalLength: 'Number of decimal places.',
    integer: 'Integer-only mode.',
    disabled: 'Disabled.',
    inputDisabled: 'Disable input field only.',
    buttonSize: 'Button size.',
    inputWidth: 'Input field width.',
    minusIcon: 'Custom minus icon.',
    plusIcon: 'Custom plus icon.',
    allowEmpty: 'Allow empty value.',
  },
  rate: {
    value: 'Current rating value.',
    onChange: 'Rating change callback.',
    count: 'Total icon count, default 5.',
    size: 'Icon size.',
    gutter: 'Icon spacing.',
    color: 'Color when active.',
    voidColor: 'Color when inactive.',
    disabledColor: 'Color when disabled.',
    icon: 'Icon name when active, maps to Icon name prop.',
    voidIcon: 'Icon name when inactive.',
    allowHalf: 'Allow half-star selection.',
    clearable: 'Allow clearing on second click.',
    readonly: 'Readonly.',
    disabled: 'Disabled.',
  },
  calendar: {
    type: 'Selection mode: single / range / multiple.',
    value: 'Current value, format depends on type.',
    onChange: 'Value change callback.',
    popup: 'Popup mode. Set false to display inline.',
    show: 'Controlled popup visibility.',
    title: 'Popup title.',
    closeable: 'Show close button.',
    minDate: 'Minimum selectable date.',
    maxDate: 'Maximum selectable date.',
    firstDayOfWeek: 'First day of week, 0=Sunday.',
    weekdays: 'Weekday label array.',
    titleFormatter: 'Month title formatter function.',
    activeColor: 'Active color.',
    dayRender: 'Custom day cell render function.',
    maxCount: 'Max days for multi-select.',
    maxRange: 'Max span in days for range.',
    showConfirm: 'Show confirm button for range mode.',
    readonly: 'Readonly.',
    lunar: 'Show lunar calendar information.',
    teleport: 'Mount target.',
  },
  cascader: {
    options: 'Cascade data source, see CascaderOption.',
    value: 'Currently selected value.',
    onChange: 'Value change callback.',
    title: 'Title.',
    placeholder: 'Placeholder when no selection.',
    closeable: 'Show close button.',
    show: 'Controlled visibility.',
    onUpdateShow: 'Close callback.',
    onClose: 'Close callback.',
    maxHeight: 'Fixed popup height.',
    showCheckmark: 'Show checkmark on selected item, default true.',
    checkmark: 'Custom check icon.',
    teleport: 'Mount target.',
    zIndex: 'z-index.',
  },
  citypicker: {
    columns: 'Tree data for regions. You provide your own data.',
    value: 'Currently selected values (one per level).',
    onChange: 'Value change callback.',
    onConfirm: 'Confirm button callback.',
    onCancel: 'Cancel button callback.',
    placeholder: 'Placeholder text.',
    separator: 'Display separator, default " / ".',
    title: 'Panel title.',
    teleport: 'Portal mount target.',
  },
  dialog: {
    show: 'Whether dialog is visible (controlled, required).',
    title: 'Title, supports string or JSX.',
    message: 'Content, supports \\n line breaks and JSX.',
    width: 'Dialog width.',
    messageAlign: 'Content horizontal alignment: left / center / right.',
    showConfirmButton: 'Show confirm button, default true.',
    showCancelButton: 'Show cancel button, default false.',
    confirmText: 'Confirm button text.',
    cancelText: 'Cancel button text.',
    confirmDisabled: 'Disable confirm button.',
    cancelDisabled: 'Disable cancel button.',
    zIndex: 'Stack level, default 2000.',
    overlay: 'Show overlay, default true.',
    closeOnClickOverlay: 'Close on overlay click, default false.',
    lockScroll: 'Lock background scroll, default true.',
    beforeClose: 'Before-close guard. Return false to prevent close.',
    onConfirm: 'Confirm callback.',
    onCancel: 'Cancel callback.',
    onClose: 'Close callback.',
    teleport: 'Mount target node.',
    destroyOnClose: 'Destroy content on close.',
    lazyRender: 'Lazy render, default true.',
  },
  actionsheet: {
    open: 'Whether visible (required).',
    onClose: 'Close callback (required).',
    items: 'Options list.',
    title: 'Title text.',
    closeable: 'Show close icon, default false.',
    description: 'Description text shown below title.',
    cancelText: 'Cancel button text.',
    closeOnSelect: 'Auto close after selection, default true.',
    closeOnOverlayClick: 'Close on overlay click, default true.',
    round: 'Top rounded corners, default true.',
  },
  toast: {
    message: 'Toast message content.',
    type: 'Type, determines icon and default style: success / error / warning / loading / info.',
    position: 'Position: top / middle / bottom.',
    duration: 'Auto-dismiss duration in ms. 0 = no auto-dismiss.',
    overlay: 'Show semi-transparent overlay, default false.',
    closeOnClick: 'Close toast when clicked.',
    onClose: 'Close callback.',
  },
  pullrefresh: {
    loading: 'Controlled loading state. You manage loading when this is provided.',
    onRefresh: 'Refresh callback. Returning a Promise auto-closes on completion.',
    pullDistance: 'Pull distance to trigger refresh (px).',
    headHeight: 'Refresh indicator area height (px).',
    successDuration: 'Success state display duration (ms).',
    animationDuration: 'Bounce-back animation duration (ms).',
    disabled: 'Disable pull-to-refresh.',
    pullingText: 'Pulling text.',
    loosingText: 'Release text.',
    loadingText: 'Loading text.',
    successText: 'Success text.',
  },
  swiper: {
    autoplay: 'Auto-play interval (ms).',
    duration: 'Animation duration (ms).',
    initialSwipe: 'Initial slide index.',
    'width / height': 'Slide dimensions.',
    loop: 'Enable loop playback.',
    showIndicators: 'Show indicators.',
    vertical: 'Vertical scroll direction.',
    touchable: 'Enable touch swipe.',
    indicatorColor: 'Indicator color.',
    indicators: 'Custom indicator render function.',
    imgUrls: 'Quick image array. No need for children when this is set.',
    lazyRender: 'Lazy render non-current pages.',
    onChange: 'Slide change callback.',
  },
  tabbar: {
    value: 'Currently selected tab (controlled).',
    defaultValue: 'Default selected (uncontrolled).',
    onChange: 'Tab change callback.',
    fixed: 'Fixed at bottom, default true.',
    border: 'Show outer border.',
    zIndex: 'Element z-index.',
    height: 'Tab bar height. Placeholder height syncs.',
    activeColor: 'Active tab color.',
    inactiveColor: 'Inactive tab color.',
    safeArea: 'Enable bottom safe area padding.',
    bgColor: 'Custom background color. Supports gradients, translucent glass.',
    placeholder: 'Generate equal-height placeholder when fixed.',
    beforeChange: 'Before-change guard. Return false to prevent.',
  },
  tabs: {
    active: 'Current active tab (controlled).',
    defaultActive: 'Default active tab (uncontrolled).',
    onChange: 'Tab change callback.',
    type: 'Style: line / card.',
    color: 'Theme color.',
    background: 'Tab bar background color.',
    duration: 'Animation duration (seconds).',
    animated: 'Content area switch animation.',
    border: 'Show border (line mode only).',
    sticky: 'Sticky positioning.',
    lazyRender: 'Lazy render inactive tabs, default true.',
    titleActiveColor: 'Active title color.',
    titleInactiveColor: 'Inactive title color.',
    beforeChange: 'Before-change guard. Return false to prevent.',
  },
  navbar: {
    title: 'Title.',
    left: 'Custom left content.',
    right: 'Custom right content.',
    backArrow: 'Show back arrow.',
    onBack: 'Back arrow click callback.',
    onLeftClick: 'Left area click callback.',
    onRightClick: 'Right area click callback.',
    fixed: 'Fix at top.',
    placeholder: 'Generate placeholder to avoid content overlap when fixed.',
    border: 'Show bottom border.',
    zIndex: 'z-index.',
    background: 'Background color.',
    color: 'Text color.',
    height: 'Nav bar height.',
  },
  cell: {
    title: 'Left title.',
    value: 'Right content.',
    description: 'Description below title.',
    children: 'Custom content. title/value/description ignored when set.',
    icon: 'Left icon, string or JSX.',
    size: 'Size: xs / sm / md / lg.',
    required: 'Show required red asterisk.',
    center: 'Vertically center content.',
    clickable: 'Clickable. Shows right arrow when true.',
    onClick: 'Click callback (only when clickable).',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
  },
  cellgroup: {
    title: 'Group title.',
    card: 'Card mode (rounded + background).',
    border: 'Show cell borders.',
    children: 'Cell children.',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
  },
  overlay: {
    open: 'Control overlay visibility.',
    onClose: 'Fires on background click or Escape.',
    zIndex: 'Custom z-index.',
    lockScroll: 'Lock body scroll.',
    mount: 'Portal mount target.',
    duration: 'Transition animation duration (ms).',
  },
  loading: {
    text: 'Loading text. Takes precedence over children.',
    children: 'Children. Used when text not provided.',
    type: 'Built-in animation type: spinner / circular / dots.',
    size: 'Animation size. Numbers auto-suffixed with px.',
    color: 'Animation color.',
    textColor: 'Text color.',
    vertical: 'Stack text and animation vertically.',
    overlay: 'Full-screen overlay mode.',
    icon: 'Custom icon. Overrides type when set.',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
  },
  avatar: {
    src: 'Avatar image URL.',
    alt: 'Alt text (accessibility).',
    size: 'Size: preset xs/sm/md/lg/xl or custom px.',
    round: 'Fully round (mutually exclusive with square).',
    square: 'Square shape. Number value controls border-radius.',
    icon: 'Icon shown when no src or load fails.',
    text: 'Text shown when no src and no icon (first character).',
    color: 'Custom background color.',
  },
  badge: {
    content: 'Badge content. Shows max+ when number exceeds max.',
    dot: 'Show only red dot.',
    max: 'Number cap, e.g. 99.',
    position: 'Position: top-right / top-left / bottom-right / bottom-left.',
    color: 'Custom background color.',
  },
  tag: {
    type: 'Semantic color: primary / secondary / success / warning / danger / info.',
    variant: 'Fill style: solid / outline / ghost.',
    size: 'Size: xs / sm / md / lg.',
    round: 'Pill rounded corners.',
    closeable: 'Show close button.',
    onClose: 'Close callback.',
    color: 'Custom color.',
  },
  empty: {
    description: 'Description text.',
    image: 'Image: preset types (default/network/search) or custom JSX.',
    children: 'Custom bottom content (e.g. button).',
    class: 'Custom CSS class.',
  },
  image: {
    src: 'Image URL.',
    alt: 'Alt text.',
    width: 'Width.',
    height: 'Height.',
    fit: 'Object fit: cover / contain / fill / none / scale-down.',
    position: 'object-position value.',
    radius: 'Border radius.',
    round: 'Fully round (circle).',
    block: 'Block-level element, full width.',
    lazy: 'Enable lazy loading.',
    placeholder: 'Loading placeholder.',
    fallback: 'Error fallback.',
    iconSize: 'Icon size on load error.',
    onLoad: 'Load success callback.',
    onError: 'Load error callback.',
    preview: 'Click to preview full image.',
  },
  icon: {
    name: 'Icon name.',
    variant: 'Style variant: line / fill.',
    size: 'Size. Numbers auto-suffixed with px.',
    color: 'Icon color.',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
    id: 'DOM id.',
    'aria-label': 'Accessibility label. Required for functional icons.',
    onClick: 'Click event.',
  },
  row: {
    gap: 'Column gap. Numbers auto-suffixed with px.',
    align: 'Vertical alignment: top / center / bottom / stretch.',
    justify: 'Horizontal distribution: start / center / end / space-between / space-around.',
    wrap: 'Allow wrapping.',
  },
  col: {
    span: 'Grid columns 1-24.',
    offset: 'Left offset.',
  },
  divider: {
    direction: 'Direction: horizontal / vertical.',
    text: 'Middle text (horizontal only).',
    dashed: 'Dashed style.',
    color: 'Line color.',
    size: 'Line thickness.',
  },
  safearea: {
    position: 'Safe area position: top / bottom / both.',
  },
  center: {
    flexX: 'Flexbox horizontal center (justify-content: center).',
    flexY: 'Flexbox vertical center (align-items: center). Parent needs height.',
    text: 'text-align: center. For inline/inline-block content.',
    vertical: 'vertical-align: middle. For inline elements.',
    position: 'absolute + transform center. Parent needs position: relative.',
    inline: 'Inline mode (flex -> inline-flex).',
    as: 'Rendered HTML tag, default div.',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
  },
  lazyload: {
    active: 'Controlled: manually activate.',
    placeholder: 'Placeholder shown when inactive.',
    children: 'Actual content rendered when active.',
    rootMargin: 'Trigger offset from viewport edge.',
    height: 'Minimum height to hold layout before activation, prevents layout shift.',
    threshold: 'Visibility ratio threshold 0-1.',
    once: 'Trigger only once, default true.',
  },
  list: {
    data: 'Controlled mode: externally managed data source.',
    onLoad: 'Uncontrolled mode: called on scroll-to-bottom. Return value appends to list.',
    finished: 'Whether all data has been loaded.',
    children: 'Render function for each item.',
    empty: 'Empty state placeholder.',
    loadMoreText: 'Bottom loading prompt.',
    finishedText: 'Bottom finished prompt.',
    offset: 'Distance from bottom (px) to trigger onLoad.',
    virtual: 'Enable virtual list.',
    itemHeight: 'Fixed item height (px) for virtual list mode.',
    pullRefresh: 'Enable pull-to-refresh, use with onRefresh.',
    onRefresh: 'Pull-to-refresh callback.',
  },
  notify: {
    type: 'Type: primary / success / warning / danger.',
    message: 'Display text. Supports \\n line breaks.',
    duration: 'Display duration (ms). 0 = no auto-dismiss.',
    position: 'Position: top / bottom.',
    color: 'Text color.',
    background: 'Background color.',
    lockScroll: 'Lock background scroll.',
    onClick: 'Click callback.',
    onClose: 'Close callback.',
  },
  swipecell: {
    rightActions: 'Right-side swipe actions.',
    leftActions: 'Left-side swipe actions.',
    threshold: 'Swipe threshold to open (px).',
    actionsWidth: 'Action area width (px).',
    disabled: 'Disable swipe.',
    onOpen: 'Open callback.',
    onClose: 'Close callback.',
    children: 'Content layer, most commonly Cell.',
    class: 'Custom CSS class.',
    style: 'Inline styles.',
  },
};

// Output the section as TypeScript code
console.log('  componentProps: {');
for (const [comp, props] of Object.entries(zhCN)) {
  console.log(`    ${comp}: {`);
  for (const [prop, desc] of Object.entries(props)) {
    const escaped = desc.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    console.log(`      ${prop}: '${escaped}',`);
  }
  console.log('    },');
}
console.log('  },');

console.log('\n// ---- en-US ----\n');
console.log('  componentProps: {');
for (const [comp, props] of Object.entries(enUS)) {
  console.log(`    ${comp}: {`);
  for (const [prop, desc] of Object.entries(props)) {
    const escaped = desc.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    console.log(`      ${prop}: '${escaped}',`);
  }
  console.log('    },');
}
console.log('  },');
