export default {
  solidjs: {
    title: 'About Solid.js',
    whatTitle: 'What Is It',
    whatP1: 'Solid.js',
    whatP1After: ' is a declarative, fine-grained reactive JavaScript UI framework. Its programming model is nearly identical to React — JSX, components, Hooks, Context, Suspense… every familiar concept is there, and it feels even more "React" than React itself.',
    perfTitle: 'Performance',
    perfP1: 'Solid has no virtual DOM. Component functions run exactly once; after that, a compiler-generated fine-grained reactivity system updates DOM nodes directly. This means extremely low runtime overhead — Solid consistently ranks in the top tier of every major frontend framework benchmark, and in some scenarios it\'s the fastest.',
    perfP2: 'This "no virtual DOM + fine-grained reactivity" design has, in a sense, inspired Vue 3.6\'s ',
    perfP2Link: 'Vapor Mode',
    perfP2After: ' — a compilation strategy that eliminates the need for a virtual DOM. Solid was ahead of the entire industry on this front.',
    missedTitle: 'A Missed Opportunity',
    missedP1: 'But Solid arrived too late.',
    missedP2: 'It was officially released in 2021, by which time the frontend landscape had already been reshaped many times over. React\'s ecosystem is an immovable mountain. Vue is deeply entrenched in developer communities worldwide. Svelte captured the "compile-time framework" narrative, while Qwik carved out the "resumability" niche. Solid, despite being technically superior in many ways, found itself squeezed between giants.',
    missedP3: 'From a technical standpoint, Solid delivers almost everything you could want from a "React replacement" — better performance, simpler state management, cleaner side-effect handling (no dependency arrays, no stale closures). But it ran into an iron law:',
    missedQuote: 'Framework competition is no longer just about technology — it\'s about ecosystem and first-mover advantage.',
    missedP4: 'This is why, despite its excellence, Solid\'s ecosystem has never truly flourished. The lack of third-party component libraries, starter templates, and enterprise-grade solutions makes most teams hesitate — nobody wants to be the one who has to fill every gap alone.',
    whyTitle: 'Why We Chose It',
    whyP1: "We chose Solid to build this component library not because it's trendy — quite the opposite. Its reactivity model and compilation strategy happen to be the best foundation for building a component system. Fine-grained updates mean components don't need a massive runtime diff to locate changes. Single-execution component functions let state management return to simple JavaScript variables and functions, without yet another framework API to learn.",
    whyP2: "We believe this component library itself is a step toward filling Solid's ecosystem gap. If this article sparked even a little interest, check out the ",
    whyP2Link: 'official tutorial',
    whyP2After: " — ten minutes, and you'll discover a world that's cleaner and lighter than React.",
    readingTitle: 'Further Reading',
    reading1a: 'Solid.js Website', reading1b: 'Docs, tutorials, playground',
    reading2a: 'Solid API Reference', reading2b: 'Compare with React API, 10 min to get started',
    reading3a: 'Vue Vapor Mode', reading3b: 'A no-VDOM compilation strategy inspired by Solid',
    reading4a: 'JS Framework Benchmark', reading4b: 'Solid consistently tops the charts',
  },
};