export default {
  solidjs: {
    title: '关于 Solid.js',
    whatTitle: '它是什么',
    whatP1: 'Solid.js',
    whatP1After: ' 是一个声明式、细粒度响应式的 JavaScript UI 框架。它的编程模型和 React 几乎一模一样——JSX、组件、Hooks、Context、Suspense……你能想到的 React 里有的概念，它都有，而且写得比 React 还「React」。',
    perfTitle: '性能',
    perfP1: 'Solid 没有虚拟 DOM。组件函数只执行一次，之后由编译器生成的细粒度响应式系统直接更新 DOM 节点。这意味着它的运行时开销极低——在所有主流前端框架的性能基准测试中，Solid 始终处于第一梯队，在某些场景下甚至是最快的那个。',
    perfP2: '这个「无虚拟 DOM + 细粒度响应式」的设计，在某种意义上启发了 Vue 3.6 的 ',
    perfP2Link: 'Vapor Mode',
    perfP2After: '——一种不需要虚拟 DOM 的编译策略。可以说，Solid 在这个方向上领先了整个行业。',
    missedTitle: '惋惜',
    missedP1: '但 Solid 诞生得太晚了。',
    missedP2: '它 2021 年才正式发布，那时前端世界早已完成了一轮又一轮的框架洗牌。React 的生态像一座无人能撼动的大山，Vue 在中小团队和国内社区根深蒂固，Svelte 抢走了「编译时框架」的叙事，而 Qwik 又在「可恢复性」方向上建立了护城河。',
    missedP3: '从技术角度看，Solid 几乎做到了你能对「React 的完美替代品」期待的一切——更好的性能、更简单的状态管理、更干净的副作用处理（没有依赖数组，没有 stale closure）。但它撞上了一个铁律：',
    missedQuote: '前端框架的竞争早已不只是技术的竞争，而是生态和先发优势的竞争。',
    missedP4: '这也是为什么尽管它足够优秀，社区生态却始终没有真正起来的原因——第三方组件库、脚手架模板、企业级解决方案的匮乏，让大多数团队在评估时会因为「万一遇到问题没人填坑」而犹豫。',
    whyTitle: '我们为什么选它',
    whyP1: '选择 Solid 来写这套组件库，不是因为追随什么潮流——恰恰相反，是因为它的响应式模型和编译策略恰好是构建组件系统的最佳土壤。细粒度的更新意味着组件不需要依赖庞大的运行时 diff 来定位变化；一次执行的组件函数让状态管理回归到最简单的 JavaScript 变量和函数，而不是一套需要额外学习的框架 API。',
    whyP2: '我们相信这套组件库本身，就是帮它补齐生态短板的一步。如果你读完这篇文章，对 Solid 产生了哪怕一点点兴趣，都可以去它的 ',
    whyP2Link: '官方教程',
    whyP2After: ' 看看——十分钟，你会发现一个比 React 更干净、更轻量的世界。',
    readingTitle: '延伸阅读',
    reading1a: 'Solid.js 官网', reading1b: '文档、教程、Playground',
    reading2a: 'Solid API 参考', reading2b: '和 React 的 API 对照着看，10 分钟上手',
    reading3a: 'Vue Vapor Mode', reading3b: '受 Solid 启发的无虚拟 DOM 编译策略',
    reading4a: 'JS Framework Benchmark', reading4b: '主流框架性能基准，Solid 常年榜首',
  },
};