export default {
  radio: {
    props: {
      value: 'Identifier — maps to RadioGroup value when selected (required).',
      label: 'Label text, supports JSX.',
      checked: 'Checked state for standalone mode (controlled), with onChange.',
      onChange: 'Standalone change callback: (checked: boolean) => void.',
      disabled: 'Disabled.',
      labelDisabled: 'Disable label click toggle.',
      labelPosition: 'Label position: left / right, default right.',
      iconSize: 'Icon size, default 20px.',
      checkedColor: 'Checked color, default #1989fa.',
      shape: 'Shape: round / square / dot, default round.',
      checkedIcon: 'Custom checked icon JSX.',
      uncheckedIcon: 'Custom unchecked icon JSX.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
      name: 'Native name attribute.',
    },
    groupProps: {
      value: 'Current value (controlled).',
      defaultValue: 'Default value (uncontrolled).',
      onChange: 'Value change callback: (value: unknown) => void.',
      direction: 'Direction: vertical (default) / horizontal.',
      gap: 'Gap between items. Horizontal defaults to "4px 12px", vertical to 0.',
      disabled: 'Disable all options.',
      iconSize: 'Icon size, default 20px.',
      checkedColor: 'Checked color, default #1989fa.',
      shape: 'Shape: round / square / dot, default round.',
      checkedIcon: 'Custom checked icon.',
      uncheckedIcon: 'Custom unchecked icon.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-radio-text-color': 'Text color.',
      '--sc-radio-disabled-text-color': 'Disabled text color.',
      '--sc-radio-icon-size': 'Icon size, default 20px.',
      '--sc-radio-border-color': 'Unchecked border color, default #c8c9cc.',
      '--sc-radio-checked-border-color': 'Checked border color, default #1989fa.',
      '--sc-radio-checked-bg': 'Checked background, default #1989fa.',
      '--sc-radio-disabled-opacity': 'Disabled opacity, default 0.5.',
      '--sc-radio-gap': 'Icon-label gap, default 8px.',
      '--sc-radio-font-size': 'Font size, default 0.9375rem.',
    },
    demo: {
      basic: 'Basic',
      disabled: 'Disabled',
      shape: 'Shape',
      color: 'Custom Color',
      horizontal: 'Horizontal',
      customIcon: 'Custom Icon',
      standalone: 'Standalone',
      form: 'Form Integration',
    },
    demoDesc: {
      basic: 'RadioGroup wraps Radio items. value maps to the selected option.',
      disabled: 'Per-item disabled or RadioGroup-level disabled.',
      shape: 'round / square / dot — three shapes.',
      color: 'checkedColor="#22c55e" changes the accent color.',
      horizontal: 'direction="horizontal" for inline layout, good for 2–3 choices.',
      customIcon: 'checkedIcon + uncheckedIcon replace the default dot with custom SVGs.',
      standalone: 'Radio used alone without RadioGroup — self-managed checked state.',
      form: 'RadioGroup inside FormItem auto-binds via useFormField().',
    },
    intro: 'Radio button component with RadioGroup wrapper. Three shapes, custom colors and icons, horizontal/vertical layout, standalone or Form mode.',
  },
};
