export default {
  radio: {
    props: {
      value: '标识符，选中时对应 RadioGroup 的 value（必填）。',
      label: '标签文字，支持 JSX。',
      checked: '独立使用时是否选中（受控），配合 onChange 使用。',
      onChange: '独立使用时选中变化回调 (checked: boolean) => void。',
      disabled: '是否禁用。',
      labelDisabled: '是否禁用标签点击切换。',
      labelPosition: '标签位置：left / right，默认 right。',
      iconSize: '图标大小，默认 20px。',
      checkedColor: '选中态颜色，默认 #1989fa。',
      shape: '形状：round（圆）/ square（方）/ dot（点），默认 round。',
      checkedIcon: '自定义选中图标 JSX。',
      uncheckedIcon: '自定义未选中图标 JSX。',
      class: '自定义 CSS class。',
      style: '内联样式。',
      name: '原生 name 属性。',
    },
    groupProps: {
      value: '当前选中值（受控）。',
      defaultValue: '默认值（非受控）。',
      onChange: '值变化回调 (value: unknown) => void。',
      direction: '排列方向：vertical（默认）/ horizontal。',
      gap: '选项间距。horizontal 默认 "4px 12px"，vertical 默认 0。',
      disabled: '是否禁用所有选项。',
      iconSize: '图标大小，默认 20px。',
      checkedColor: '选中态颜色，默认 #1989fa。',
      shape: '形状：round / square / dot，默认 round。',
      checkedIcon: '自定义选中图标。',
      uncheckedIcon: '自定义未选中图标。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-radio-text-color': '文字颜色。',
      '--sc-radio-disabled-text-color': '禁用态文字颜色。',
      '--sc-radio-icon-size': '图标大小，默认 20px。',
      '--sc-radio-border-color': '未选中边框颜色，默认 #c8c9cc。',
      '--sc-radio-checked-border-color': '选中态边框颜色，默认 #1989fa。',
      '--sc-radio-checked-bg': '选中态背景色，默认 #1989fa。',
      '--sc-radio-disabled-opacity': '禁用态透明度，默认 0.5。',
      '--sc-radio-gap': '图标与标签间距，默认 8px。',
      '--sc-radio-font-size': '字号，默认 0.9375rem。',
    },
    demo: {
      basic: '基础用法',
      disabled: '禁用',
      shape: '形状',
      color: '自定义颜色',
      horizontal: '横向排列',
      customIcon: '自定义图标',
      standalone: '独立使用',
      form: '表单集成',
    },
    demoDesc: {
      basic: 'RadioGroup 包裹 Radio，value 对应当前选中项。',
      disabled: '单个 Radio 设置 disabled，或 RadioGroup 全局 disabled。',
      shape: 'round（圆形）/ square（方形）/ dot（点状）三种形状。',
      color: 'checkedColor="#22c55e" 修改选中态颜色。',
      horizontal: 'direction="horizontal" 横向排列，适合两三个选项。',
      customIcon: 'checkedIcon + uncheckedIcon 用自定义 SVG 图标替代默认圆点，更生动的满意度选择。',
      standalone: 'Radio 脱离 RadioGroup 单独使用，自行管理 checked 和 onChange。',
      form: 'RadioGroup 放入 FormItem，通过 useFormField() 自动双向绑定，direction="horizontal" 配合 auto-control-align。',
    },
    intro: '单选组件，配合 RadioGroup 使用。支持三种形状、自定义颜色和图标、横向/纵向排列、独立模式和表单集成。',
  },
};
