export default {
  form: {
    props: {
      value: 'Controlled: current form value.',
      onChange: 'Value change callback (controlled mode).',
      defaultValue: 'Uncontrolled: initial default value.',
      onSubmit: 'Submit callback. Not fired if validation fails.',
      validateOnChange: 'Validate on field change, default false.',
      validateOnBlur: 'Validate on field blur, default false.',
      disabled: 'Disable all fields globally.',
      readonly: 'Readonly mode for all fields.',
      labelAlign: 'Label alignment: top / left / right.',
      labelWidth: 'Fixed label width, e.g. "5em".',
      controlAlign: 'Control area alignment, default left. Set right to push controls to the end.',
      colon: 'Append colon after label, default false.',
      scrollToError: 'Auto-scroll to the first error field on submit failure.',
      ref: 'Mount callback, receives { setFormValue, resetFormValue, submit, validateAll }.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    itemProps: {
      name: 'Field name, key in formValue. Required.',
      label: 'Label text.',
      required: 'Required indicator (red asterisk).',
      rules: 'Validation rules: [{ validator, message, trigger? }].',
      help: 'Help text shown when no error.',
      labelAlign: 'Override Form label alignment.',
      labelWidth: 'Override Form label width.',
      controlAlign: 'Control alignment, inherits from Form by default.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    ruleProps: {
      validator: 'Validator: (value, formValue) => boolean | Promise<boolean>.',
      message: 'Error message, can be a function (value) => string.',
      trigger: 'Trigger: onChange (default) / onBlur / onSubmit.',
    },
    cssVars: {
      '--sc-form-control-height': 'Control row height, default 40px.',
      '--sc-form-item-padding-y': 'Vertical padding, default 8px.',
      '--sc-form-item-label-top-padding-y': 'Top-label vertical padding, default 12px.',
      '--sc-form-item-label-gap': 'Top-label gap to control, default 6px.',
      '--sc-form-item-label-margin': 'Side-label gap to control, default 12px.',
    },
    layout: {
      title: 'Layout Strategy',
      desc: 'Form uses Flexbox layout, optimized for narrow mobile viewports (375–430px). Principles:',
      item1: 'Controls always take remaining space (flex: 1). Labels use content width or fixed labelWidth — controls fill the space beside them.',
      item2: 'controlAlign: default "left" (start), set "right" for end alignment. "center" is intentionally omitted — cramped on narrow screens.',
      item3: 'labelAlign: "top" / "left" / "right". Use "top" for horizontal multi-choice controls (Radio, Checkbox) for more room.',
      item4: 'RadioGroup / CheckboxGroup auto-detect controlAlign via FormFieldContext and follow the Form setting.',
      item5: 'Spacing via CSS vars: --sc-form-control-height, --sc-form-item-padding-y, --sc-form-item-label-gap (top), --sc-form-item-label-margin (right).',
    },
    demo: {
      uncontrolled: 'Uncontrolled',
      controlled: 'Controlled',
      validation: 'Validation (Sync + Async)',
      ref: 'Ref API',
      full: 'Full Example',
    },
    demoDesc: {
      uncontrolled: 'Set defaultValue to initialize — Form manages its own state internally.',
      controlled: 'Pass value + onChange to manage form state externally, for real-time access.',
      validation: 'Sync (length/format/number) + async (simulated 800ms server check). validateOnBlur triggers validation on blur.',
      ref: 'ref callback exposes { setFormValue, resetFormValue, submit, validateAll } for imperative control. resetFormValue restores initial defaults.',
      full: '13 controls inside one Form — the complete demo.',
    },
    refApi: {
      title: 'Ref API',
      desc: 'The ref callback gives you imperative APIs to control the form from outside:',
      setFormValue: 'Replace the entire form value.',
      resetFormValue: 'Reset to defaultValue (or empty object) and clear all errors.',
      submit: 'Trigger form submission (validates first).',
      validateAll: 'Validate all registered fields, returns Promise<boolean>. Errors auto-display on failure.',
    },
    intro: 'Form container with value management, validation, and submit. Controls integrate via FormItem and useFormField() — works standalone too.',
  },
};
