export default {
  form: {
    props: {
      value: '受控模式：表单当前值。',
      onChange: '值变化回调（受控模式）。',
      defaultValue: '非受控模式：初始默认值。',
      onSubmit: '提交回调。若校验失败则不触发。',
      validateOnChange: '字段变化时是否校验，默认 false。',
      validateOnBlur: '字段失焦时是否校验，默认 false。',
      disabled: '全局禁用所有字段。',
      readonly: '全局只读所有字段。',
      labelAlign: '标签对齐：top（上方）/ left（左侧）/ right（右侧）。',
      labelWidth: '标签固定宽度，如 "5em"。',
      controlAlign: '控件区对齐，默认 left。设为 right 时控件靠右。',
      colon: '标签后是否追加冒号，默认 false。',
      scrollToError: '提交校验失败时是否自动滚动到第一个错误字段。',
      ref: '挂载回调，接收 { setFormValue, resetFormValue, submit, validateAll }。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    itemProps: {
      name: '字段名，对应 formValue 中的 key，必填。',
      label: '标签文本。',
      required: '是否必填，标签前显示红色星号。',
      rules: '校验规则数组，每项 { validator, message, trigger? }。',
      help: '帮助文本，无错误时显示在 description 位置。',
      labelAlign: '覆盖 Form 的标签对齐设置。',
      labelWidth: '覆盖 Form 的标签宽度。',
      controlAlign: '控件区对齐，默认继承 Form。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    ruleProps: {
      validator: '校验函数 (value, formValue) => boolean | Promise<boolean>。',
      message: '校验失败提示文本，可为函数 (value) => string。',
      trigger: '触发时机：onChange（默认）/ onBlur / onSubmit。',
    },
    cssVars: {
      '--sc-form-control-height': '控件行高度，默认 40px。',
      '--sc-form-item-padding-y': '表单项垂直内边距，默认 8px。',
      '--sc-form-item-label-top-padding-y': '标签在上方时的垂直内边距，默认 12px。',
      '--sc-form-item-label-gap': '标签在上方时与控件间距，默认 6px。',
      '--sc-form-item-label-margin': '标签在侧边时与控件间距，默认 12px。',
    },
    layout: {
      title: '布局策略',
      desc: 'Form 使用 Flexbox 布局，适配移动端窄屏（375-430px）。布局遵循以下原则：',
      item1: '控件区始终占据剩余空间（flex: 1）。标签仅占内容宽度或 labelWidth 指定宽度，控件自动填满标签旁空间。',
      item2: 'controlAlign 设置控件区对齐：默认 left（从左开始），设为 right 靠右。刻意不支持 center — 移动端窄屏下标签已占较多空间，居中不自然且浪费空间。',
      item3: 'labelAlign 支持 top / left / right。Radio、Checkbox 等横向多选控件建议用 top，给它们更多空间。',
      item4: 'RadioGroup / CheckboxGroup 通过 FormFieldContext 自动感知 controlAlign，跟随 Form 设置对齐。',
      item5: '间距可通过 CSS 变量自定义：--sc-form-control-height、--sc-form-item-padding-y、--sc-form-item-label-gap（top 模式）、--sc-form-item-label-margin（标签右侧间距）。',
    },
    demo: {
      uncontrolled: '非受控模式',
      controlled: '受控模式',
      validation: '表单校验（同步 + 异步）',
      ref: 'Ref 命令式 API',
      full: '综合示例',
    },
    demoDesc: {
      uncontrolled: '通过 defaultValue 设置初始值，表单内部自行管理状态。',
      controlled: '通过 value + onChange 外部接管表单值，适合需要实时读取表单数据的场景。',
      validation: '同步校验（长度/格式/数值） + 异步校验（模拟 800ms 服务端检查）。validateOnBlur 失焦时触发。',
      ref: 'ref 回调暴露 { setFormValue, resetFormValue, submit, validateAll }，实现外部命令式控制。resetFormValue 恢复为初始默认值。',
      full: '13 种控件放入一个 Form 中，展示完整的表单能力。',
    },
    refApi: {
      title: 'Ref API',
      desc: '通过 ref 属性可以获取表单的命令式 API，用于在组件外部控制表单行为：',
      setFormValue: '整体替换表单值。',
      resetFormValue: '重置表单值为 defaultValue（或空对象），同时清除所有错误信息。',
      submit: '手动触发表单提交（会先执行校验）。',
      validateAll: '校验所有已注册规则的字段，返回 Promise<boolean>。不通过时自动显示错误。',
    },
    intro: '表单容器，通过 FormItem 统一管理字段值、校验和提交。支持受控/非受控两种模式，子控件通过 useFormField() 自动接入。',
  },
};
