export default {
  swiper: {
    props: {
      children: 'Slide content. No SwiperItem wrapper needed — pass children directly. Mutually exclusive with imgUrls.',
      autoplay: 'Auto-play interval (ms). Omit to disable.',
      duration: 'Animation duration (ms), default 500.',
      initialSwipe: 'Initial slide index, default 0.',
      width: 'Swiper width, default 100%.',
      height: 'Swiper height, default 160px.',
      loop: 'Enable loop, default true.',
      showIndicators: 'Show indicators, default true.',
      vertical: 'Vertical scroll, default false.',
      touchable: 'Touch swipe, default true.',
      indicatorColor: 'Indicator color.',
      indicators: 'Custom indicator render (current, total) => JSX.',
      imgUrls: 'Quick image URL array. No children needed.',
      lazyRender: 'Lazy render non-current slides, default false.',
      onChange: 'Slide change callback.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-swiper-dot-size': 'Indicator dot size.',
      '--sc-swiper-dot-active-width': 'Active indicator width (pill shape).',
      '--sc-swiper-dot-color': 'Indicator color.',
      '--sc-swiper-dot-active-color': 'Active indicator color.',
      '--sc-swiper-dot-gap': 'Indicator gap.',
      '--sc-swiper-dot-bottom': 'Indicator distance from bottom.',
      '--sc-swiper-radius': 'Swiper container border radius.',
    },
    demo: {
      custom: 'Custom Content',
      autoplay: 'Auto Play',
      indicator: 'Custom Indicator',
      vertical: 'Vertical',
    },
    demoDesc: {
      custom: 'Pass custom children as slides, supports autoplay and loop.',
      autoplay: 'imgUrls + autoplay for auto-rotating image carousel.',
      indicator: 'Customize indicator via the indicators render function.',
      vertical: 'Vertical mode for up/down swipe.',
    },
    intro: 'Carousel with swipe, autoplay, loop, vertical, and custom indicators. No SwiperItem sub-component — pass children directly as slides, or use imgUrls for quick image carousels.',
  },
};
