export default {
  swiper: {
    props: {
      children: '轮播项内容。无需 SwiperItem 包裹，直接传任意子元素即可。与 imgUrls 二选一。',
      autoplay: '自动轮播间隔 (ms)，不传则不自动播放。',
      duration: '切换动画时长 (ms)，默认 500。',
      initialSwipe: '初始位置索引，默认 0。',
      width: '轮播宽度，默认 100%。',
      height: '轮播高度，默认 160px。',
      loop: '是否循环播放，默认 true。',
      showIndicators: '是否显示指示器，默认 true。',
      vertical: '纵向滚动，默认 false。',
      touchable: '手势滑动，默认 true。',
      indicatorColor: '指示器颜色。',
      indicators: '自定义指示器渲染函数 (current, total) => JSX。',
      imgUrls: '快捷图片数组，传此属性后无需写子组件。',
      lazyRender: '延迟渲染非当前页，默认 false。',
      onChange: '切换回调。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-swiper-dot-size': '指示器圆点大小。',
      '--sc-swiper-dot-active-width': '当前指示器宽度（激活态为长条）。',
      '--sc-swiper-dot-color': '指示器颜色。',
      '--sc-swiper-dot-active-color': '当前指示器颜色。',
      '--sc-swiper-dot-gap': '指示器间距。',
      '--sc-swiper-dot-bottom': '指示器距底部距离。',
      '--sc-swiper-radius': '轮播容器圆角。',
    },
    demo: {
      custom: '自定义内容',
      autoplay: '自动轮播',
      indicator: '自定义指示器',
      vertical: '纵向滚动',
    },
    demoDesc: {
      custom: '传入任意子元素作为轮播项，支持自动播放和循环。',
      autoplay: 'imgUrls + autoplay 实现自动轮播图片。',
      indicator: '通过 indicators 函数自定义指示器样式。',
      vertical: 'vertical 开启纵向滚动。',
    },
    intro: '轮播组件，支持手势滑动、自动播放、循环、纵向滚动、自定义指示器。无 SwiperItem 子组件概念——直接传 children 作为轮播项，或通过 imgUrls 快速渲染图片轮播。',
  },
};
