export default {
  actionsheet: {
    props: {
      open: 'Whether visible (required).',
      onClose: 'Close callback (required).',
      items: 'Options list ActionSheetItem[].',
      children: 'Custom content. Overrides items/cancelText.',
      title: 'Title text.',
      closeable: 'Show close icon, default false.',
      description: 'Description below title.',
      cancelText: 'Cancel button text.',
      closeOnSelect: 'Auto close after select, default true.',
      closeOnOverlayClick: 'Close on overlay click, default true.',
      round: 'Top rounded corners, default true.',
      lockScroll: 'Lock background scroll, default true.',
      onSelect: 'Item select callback.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    demo: {
      basic: 'Basic',
      full: 'Full Header',
      twoline: 'Two-line Items',
      disabled: 'Disabled',
      noClose: 'No Auto Close',
      custom: 'Custom Content',
    },
    demoDesc: {
      basic: 'Basic option list.',
      full: 'Title + closeable + description + cancelText.',
      twoline: 'name + subname two-line display.',
      disabled: 'Disabled options.',
      noClose: 'closeOnSelect=false for multi-select scenarios.',
      custom: 'Custom JSX content via children.',
    },
    cssVars: {
      '--sc-actionsheet-bg': 'Sheet background color.',
      '--sc-actionsheet-item-height': 'Item height.',
      '--sc-actionsheet-cancel-btn-height': 'Cancel button height.',
      '--sc-actionsheet-header-height': 'Header height.',
      '--sc-actionsheet-max-height': 'Sheet max height.',
    },
    intro: 'Bottom sheet action menu. Supports item list, title, description, cancel button, custom content.',
  },
};
