export default {
  actionsheet: {
    props: {
      open: '是否显示（必填）。',
      onClose: '关闭回调（必填）。',
      items: '选项列表 ActionSheetItem[]。',
      children: '自定义内容，设置后 items / cancelText 被忽略。',
      title: '标题文字。',
      closeable: '显示关闭图标，默认 false。',
      description: '描述文字，显示在标题下方。',
      cancelText: '取消按钮文字。',
      closeOnSelect: '选中后自动关闭，默认 true。',
      closeOnOverlayClick: '点击遮罩关闭，默认 true。',
      round: '顶部圆角，默认 true。',
      lockScroll: '锁定背景滚动，默认 true。',
      onSelect: '选项选中回调。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    demo: {
      basic: '基础选项',
      full: '完整标题',
      twoline: '双行选项',
      disabled: '禁用选项',
      noClose: '不自动关闭',
      custom: '自定义内容',
    },
    demoDesc: {
      basic: '基础选项列表示例。',
      full: '标题 + closeable + description + cancelText。',
      twoline: 'name + subname 双行展示。',
      disabled: 'disabled 禁用选项。',
      noClose: 'closeOnSelect=false 选中不关闭，适合多选场景。',
      custom: 'children 自定义内容，可放置任意 JSX。',
    },
    cssVars: {
      '--sc-actionsheet-bg': '面板背景色。',
      '--sc-actionsheet-item-height': '选项高度。',
      '--sc-actionsheet-cancel-btn-height': '取消按钮高度。',
      '--sc-actionsheet-header-height': '标题栏高度。',
      '--sc-actionsheet-max-height': '面板最大高度。',
    },
    intro: '从底部弹出的选项菜单。支持选项列表、标题、描述、取消按钮、自定义内容。',
  },
};
