export default {
  stepper: {
    props: {
      value: 'Current value (controlled).',
      onChange: 'Change callback: (value: number) => void.',
      defaultValue: 'Default value (uncontrolled), default 0.',
      min: 'Min value, default 0.',
      max: 'Max value, default Infinity.',
      step: 'Step, default 1.',
      decimalLength: 'Decimal places, default 0.',
      integer: 'Only allow integer input, default false.',
      allowEmpty: 'Allow empty value.',
      inputDisabled: 'Disable input field only.',
      disabled: 'Disable the entire stepper.',
      readonly: 'Readonly.',
      size: 'Shortcut size, overrides buttonSize/inputWidth.',
      buttonSize: 'Button size, default 32px.',
      inputWidth: 'Input width, default 50px.',
      placeholder: 'Placeholder text.',
      minusIcon: 'Custom minus icon.',
      plusIcon: 'Custom plus icon.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-stepper-button-size': 'Button size.',
      '--sc-stepper-input-width': 'Input width.',
      '--sc-stepper-input-height': 'Input height.',
      '--sc-stepper-radius': 'Button radius.',
      '--sc-stepper-button-bg': 'Button background.',
      '--sc-stepper-button-color': 'Button text color.',
      '--sc-stepper-button-border': 'Button border color.',
      '--sc-stepper-disabled-opacity': 'Disabled opacity.',
    },
    demo: {
      basic: 'Basic',
      range: 'Range Limit',
      step: 'Step & Decimal',
      disabled: 'Disabled & Readonly',
      form: 'Form Integration',
    },
    demoDesc: {
      basic: 'value + onChange controlled mode.',
      range: 'min={1} max={10} constrains the value.',
      step: 'step={0.5} decimalLength={1} enables fractional stepping.',
      disabled: 'disabled globally, inputDisabled only blocks the input.',
      form: 'Inside FormItem auto-binds via useFormField().',
    },
    intro: 'Number stepper with +/- buttons. Range limits, fractional stepping, input disable, and Form integration.',
  },
};
