export default {
  stepper: {
    props: {
      value: '当前值（受控）。',
      onChange: '值变化回调 (value: number) => void。',
      defaultValue: '默认值（非受控），默认 0。',
      min: '最小值，默认 0。',
      max: '最大值，默认 Infinity。',
      step: '步长，默认 1。',
      decimalLength: '小数位数，默认 0。',
      integer: '是否只允许整数输入，默认 false。',
      allowEmpty: '是否允许空值。',
      inputDisabled: '是否禁用输入框。',
      disabled: '是否禁用整个步进器。',
      readonly: '只读。',
      size: '整体尺寸快捷设置，覆盖 buttonSize / inputWidth。',
      buttonSize: '按钮大小，默认 32px。',
      inputWidth: '输入框宽度，默认 50px。',
      placeholder: '占位文本。',
      minusIcon: '自定义减号图标。',
      plusIcon: '自定义加号图标。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-stepper-button-size': '按钮大小。',
      '--sc-stepper-input-width': '输入框宽度。',
      '--sc-stepper-input-height': '输入框高度。',
      '--sc-stepper-radius': '按钮圆角。',
      '--sc-stepper-button-bg': '按钮背景色。',
      '--sc-stepper-button-color': '按钮文字色。',
      '--sc-stepper-button-border': '按钮边框色。',
      '--sc-stepper-disabled-opacity': '禁用态透明度。',
    },
    demo: {
      basic: '基础用法',
      range: '范围限制',
      step: '步长 & 小数',
      disabled: '禁用 & 只读',
      form: '表单集成',
    },
    demoDesc: {
      basic: 'value + onChange 受控模式。',
      range: 'min={1} max={10} 限制范围。',
      step: 'step={0.5} decimalLength={1} 支持小数步进。',
      disabled: 'disabled 全局禁用，inputDisabled 仅禁用输入。',
      form: '放入 FormItem，通过 useFormField() 自动双向绑定。',
    },
    intro: '步进器，通过加减按钮调整数值。支持范围限制、小数步进、禁用输入框和表单集成。',
  },
};
