export default {
  skeleton: {
    props: {
      loading: 'Show skeleton placeholder when true, content when false.',
      animated: 'Enable shimmer animation.',
      size: "Preset size: 'small' | 'normal' | 'large'.",
      shape: "Border radius: 'square' | 'round' | 'circle'.",
      duration: 'Animation duration in seconds.',
      rows: 'Number of skeleton rows.',
      width: 'Custom width (px or %). Overrides size.',
      height: 'Custom height (px or %). Overrides size.',
      children: 'Content shown when loading=false.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      bg: 'Skeleton bar background color.',
      bgDark: 'Skeleton bar background color (dark mode).',
      gap: 'Gap between rows.',
      duration: 'Shimmer animation duration.',
      smallH: 'Bar height for size=small.',
      normalH: 'Bar height for size=normal.',
      largeH: 'Bar height for size=large.',
      lastWidth: 'Width of the last row (shorter).',
    },
    demo: {
      basic: 'Basic Usage',
      animated: 'Animated',
      rows: 'Multiple Rows',
      shapes: 'Shapes',
      sizes: 'Sizes',
      custom: 'Custom Size',
    },
    demoDesc: {
      basic: 'Wrap content with Skeleton. Toggle loading to switch between placeholder and real content.',
      animated: 'Shimmer animation sweeps across skeleton bars.',
      rows: 'Multiple rows of skeleton bars, last row is shorter.',
      shapes: "Three shapes: 'round' (default), 'square', 'circle'.",
      sizes: "Three preset sizes: 'small' (12px), 'normal' (18px), 'large' (28px).",
      custom: "width and height override the size prop for pixel-perfect control.",
    },
    intro: 'Skeleton placeholder component. Wrap any content and toggle loading to show a loading state with shimmer animation.',
  },
};