export default {
  skeleton: {
    props: {
      loading: 'true 显示骨架屏，false 显示 children 内容。',
      animated: '是否启用 shimmer 扫光动画。',
      size: "预设尺寸：'small' | 'normal' | 'large'。",
      shape: "圆角形状：'square' | 'round' | 'circle'。",
      duration: '动画时长（秒）。',
      rows: '骨架行数。',
      width: '自定义宽度（px 或 %），优先级高于 size。',
      height: '自定义高度（px 或 %），优先级高于 size。',
      children: 'loading=false 时展示的内容。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      bg: '骨架条背景色。',
      bgDark: '骨架条背景色（暗色模式）。',
      gap: '行间距。',
      duration: '扫光动画时长。',
      smallH: 'size=small 的条高。',
      normalH: 'size=normal 的条高。',
      largeH: 'size=large 的条高。',
      lastWidth: '最后一行的宽度（较短）。',
    },
    demo: {
      basic: '基础用法',
      animated: '动画效果',
      rows: '多行骨架',
      shapes: '形状',
      sizes: '尺寸',
      custom: '自定义尺寸',
    },
    demoDesc: {
      basic: '用 Skeleton 包裹内容，切换 loading 在占位和真实内容之间过渡。',
      animated: 'shimmer 扫光动画在骨架条上循环播放。',
      rows: '多行骨架条，最后一行较短，模拟真实文本布局。',
      shapes: "三种形状：'round'（默认圆角）、'square'（方角）、'circle'（圆形）。",
      sizes: "三种预设尺寸：'small'（12px）、'normal'（18px）、'large'（28px）。",
      custom: "width / height 可覆盖 size 属性，精确控制尺寸。",
    },
    intro: '骨架屏占位组件。包裹任意内容，切换 loading 即可在加载态和真实内容间切换，支持 shimmer 动画。',
  },
};