export default {
  chatMessage: {
    props: {
      position: "Bubble position: 'left' (other) | 'right' (self).",
      messageType: "Message type: plainText | image | video | file | custom.",
      content: 'Text / markdown content.',
      src: "Image, video, or file URL.",
      fileName: 'File display name — extension auto-matched against iconMap.',
      fileSize: 'File display size, e.g. "2.4 MB".',
      iconMap: "File icon map: { pdf: '📄', doc: <Icon />, '*': '📎' }. Matches by extension, falls back to '*' or built-in defaults.",
      progress: 'Download/upload progress 0-100. When set, a progress bar appears at the bottom of the bubble.',
      children: 'Custom slot content (messageType=custom).',
      avatar: 'Avatar: string URL for image, or JSX for custom element.',
      avatarSize: 'Avatar size in px, default 36.',
      avatarShape: "Avatar shape: 'circle' | 'rounded' | 'square'.",
      showAvatar: 'Whether to show the avatar, default true.',
      tail: 'Show bubble tail pointer, default true.',
      maxWidth: 'Max bubble width, default 72%.',
      bgColor: 'Custom bubble background color.',
      borderRadius: 'Custom bubble border radius.',
      name: 'Sender name for group chats. Overridden by header.',
      header: 'Custom JSX above bubble, replaces name when provided.',
      time: 'Timestamp string. Overridden by footer.',
      footer: 'Custom JSX below bubble, replaces time + status when provided.',
      status: "Delivery state: 'sending' | 'sent' | 'read' | 'failed'.",
      statusPosition: "Icon position: 'meta' (after time), 'bubble' (inside bubble), 'side' (between avatar & bubble).",
      statusIcon: "Custom status icons: { sent: <MyCheck />, read: <BlueCheck /> }. Falls back to built-in defaults.",
      onRetry: 'Retry callback when status=failed.',
      onAvatarClick: 'Avatar click callback.',
      longPressMenu: "Long-press menu: [{ title, action }] array or custom JSX. 500ms hold to open.",
      onContentClick: 'Click callback on image/video/file content.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    demo: {
      basic: 'Basic Chat',
      imageVideo: 'Image & Video',
      fileAndCustom: 'File & Custom',
      statusesAndMeta: 'Status & Meta',
      statusPosition: 'Status Position',
      longPressArray: 'Long Press: Array Menu',
      longPressCustom: 'Long Press: Custom JSX',
      longPressSelect: 'Long Press: Text Selection',
      fileDownload: 'File Download',
    },
    demoDesc: {
      basic: 'Left/right bubbles with avatar, name, time, and tail pointer.',
      imageVideo: 'Built-in image (with preview) and video rendering. For complex media players, use messageType=custom + your own JSX.',
      fileAndCustom: 'Built-in file display with icon + progress bar. For custom download UX or interactive file cards, use messageType=custom + your own JSX.',
      statusesAndMeta: 'Delivery states: sending → sent → read → failed with retry button.',
      fileDownload: 'Use onContentClick for custom download logic. Works with any bridge API, fetch, or download manager.',
      statusPosition: "Three positions. 'meta' follows time (WhatsApp), 'bubble' floats inside (iMessage), 'side' sits between avatar & bubble (WeChat).",
      longPressArray: 'Array mode: each item gets built-in styling. 500ms hold triggers the popup menu.',
      longPressCustom: 'Custom JSX mode: full control over menu layout. Uses Tooltip for positioning.',
      longPressSelect: 'selectOnLongPress selects all bubble text on hold. Mutually exclusive with longPressMenu.',
    },
    intro: 'Chat bubble component supporting text, image, video, file, and custom content. Left/right alignment, avatar, tail pointer, and delivery status built in.',
    note: 'Honestly, I kind of regret designing this component. Unlike the rest of the library which stays firmly in the UI layer, ChatMessage inevitably reaches into business territory — chat paradigms, message statuses, long-press menus. It breaks my own design philosophy and may well be a thankless effort (lol). But in the age of LLMs and chat-driven apps, it is undeniably useful. So here it is — take it, fork it, bend it to your will. This is an opinionated starting point, not a universal chat UI solution.',
    cssVars: {
      gap: 'Gap between avatar and body.',
      wrapperPadding: 'Outer wrapper padding.',
      maxWidth: 'Max bubble width.',
      bubblePadding: 'Padding inside the text bubble.',
      fontSize: 'Base font size for bubble text.',
      lineHeight: 'Line height for bubble text.',
      radius: 'Border radius for bubbles.',
      bubbleBgLeft: 'Background color for left (other) bubbles.',
      bubbleBgSelf: 'Background color for right (self) bubbles.',
      textColor: 'Text color for left bubbles.',
      textColorSelf: 'Text color for right (self) bubbles.',
      mutedColor: 'Muted text color for name / time / meta.',
      tailWidth: 'Width of the tail triangle.',
      tailOffset: 'Distance of tail from bubble top.',
      fileIconSize: 'Width & height of the file icon box.',
      menuBg: 'Long press menu background.',
      menuItemHoverBg: 'Long press menu item hover background.',
      progressHeight: 'File progress bar height.',
    },
  },
};