export default {
  chatMessage: {
    props: {
      position: "Bubble position: 'left' (other) | 'right' (self).",
      messageType: "Message type: plainText | richText | image | video | file | custom.",
      content: 'Text / markdown content.',
      src: "Image, video, or file URL.",
      fileName: 'Display name for file messages.',
      fileSize: 'Display size for file messages.',
      children: 'Custom slot content (messageType=custom).',
      renderSlot: 'Full custom render override for all types.',
      avatar: 'Avatar image URL.',
      avatarSize: 'Avatar size in px, default 36.',
      avatarShape: "Avatar shape: 'circle' | 'rounded' | 'square'.",
      showAvatar: 'Whether to show the avatar, default true.',
      avatarSlot: 'Custom avatar JSX, overrides avatar image.',
      tail: 'Show bubble tail pointer, default true.',
      maxWidth: 'Max bubble width, default 72%.',
      bgColor: 'Custom bubble background color.',
      borderRadius: 'Custom bubble border radius.',
      name: 'Sender name for group chats.',
      time: 'Timestamp string.',
      status: "Delivery state: 'sending' | 'sent' | 'read' | 'failed'.",
      onRetry: 'Retry callback when status=failed.',
      onAvatarClick: 'Avatar click callback.',
      onLongPress: 'Long-press callback on the bubble.',
      onContentClick: 'Click callback on image/video/file content.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    demo: {
      basic: 'Basic Chat',
      imageVideo: 'Image & Video',
      fileAndCustom: 'File & Custom',
      statusesAndMeta: 'Status & Meta',
    },
    demoDesc: {
      basic: 'Left/right bubbles with avatar, name, time, and tail pointer.',
      imageVideo: 'Image and video messages with play overlay and click handling.',
      fileAndCustom: 'File attachments showing name + size, plus fully custom content via slot.',
      statusesAndMeta: 'Delivery states: sending → sent → read → failed with retry button.',
    },
    intro: 'Chat bubble component supporting text, image, video, file, and custom content. Left/right alignment, avatar, tail pointer, and delivery status built in.',
  },
};