export default {
  chatMessage: {
    props: {
      position: "Bubble position: 'left' (other) | 'right' (self).",
      messageType: "Message type: plainText | richText | image | video | file | custom.",
      content: 'Text / markdown content.',
      src: "Image, video, or file URL.",
      fileName: 'File display name — extension auto-matched against iconMap.',
      fileSize: 'File display size, e.g. "2.4 MB".',
      iconMap: "File icon map: { pdf: '📄', doc: <Icon />, '*': '📎' }. Matches by extension, falls back to '*' or built-in defaults.",
      progress: 'Download/upload progress 0-100. When set, a progress bar appears at the bottom of the bubble.',
      onDownload: 'Custom download callback. If not set, clicking the bubble calls window.open(src).',
      children: 'Custom slot content (messageType=custom).',
      avatar: 'Avatar: string URL for image, or JSX for custom element.',
      avatarSize: 'Avatar size in px, default 36.',
      avatarShape: "Avatar shape: 'circle' | 'rounded' | 'square'.",
      showAvatar: 'Whether to show the avatar, default true.',
      tail: 'Show bubble tail pointer, default true.',
      maxWidth: 'Max bubble width, default 72%.',
      bgColor: 'Custom bubble background color.',
      borderRadius: 'Custom bubble border radius.',
      name: 'Sender name for group chats. Overridden by header.',
      header: 'Custom JSX above bubble, replaces name when provided.',
      time: 'Timestamp string. Overridden by footer.',
      footer: 'Custom JSX below bubble, replaces time + status when provided.',
      status: "Delivery state: 'sending' | 'sent' | 'read' | 'failed'.",
      statusPosition: "Icon position: 'meta' (after time), 'bubble' (inside bubble), 'side' (between avatar & bubble).",
      statusIcon: "Custom status icons: { sent: <MyCheck />, read: <BlueCheck /> }. Falls back to built-in defaults.",
      onRetry: 'Retry callback when status=failed.',
      onAvatarClick: 'Avatar click callback.',
      longPressMenu: "Long-press menu: [{ title, action }] array or custom JSX. 500ms hold to open.",
      onContentClick: 'Click callback on image/video/file content.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    demo: {
      basic: 'Basic Chat',
      imageVideo: 'Image & Video',
      fileAndCustom: 'File & Custom',
      statusesAndMeta: 'Status & Meta',
    },
    demoDesc: {
      basic: 'Left/right bubbles with avatar, name, time, and tail pointer.',
      imageVideo: 'Image and video messages with play overlay and click handling.',
      fileAndCustom: 'File attachments showing name + size, plus fully custom content via slot.',
      statusesAndMeta: 'Delivery states: sending → sent → read → failed with retry button.',
    },
    intro: 'Chat bubble component supporting text, image, video, file, and custom content. Left/right alignment, avatar, tail pointer, and delivery status built in.',
  },
};