export default {
  chatMessage: {
    props: {
      position: "气泡位置：'left'（对方）| 'right'（自己）。",
      messageType: '消息类型：plainText | richText | image | video | file | custom。',
      content: '文本 / markdown 内容。',
      src: '图片、视频或文件 URL。',
      fileName: '文件显示名称，自动提取后缀匹配 iconMap。',
      fileSize: '文件显示大小，如 "2.4 MB"。',
      iconMap: "文件图标映射：{ pdf: '📄', doc: <Icon />, '*': '📎' }。按后缀匹配，未命中回退到 '*' 或内置默认图标。",
      progress: '下载/上传进度 0-100，有值时气泡底部显示进度条。',
      onDownload: '自定义下载回调，不传则点击气泡执行 window.open(src)。',
      children: '自定义插槽（messageType=custom）。',
      avatar: '头像：传 string 显示图片，传 JSX 直接渲染。',
      avatarSize: '头像大小（px），默认 36。',
      avatarShape: "头像形状：'circle' | 'rounded' | 'square'。",
      showAvatar: '是否显示头像，默认 true。',
      tail: '显示气泡尖角，默认 true。',
      maxWidth: '气泡最大宽度，默认 72%。',
      bgColor: '自定义气泡背景色。',
      borderRadius: '自定义气泡圆角。',
      name: '发送者名称（群聊场景），header 会覆盖它。',
      header: '气泡上方自定义 JSX，传了则替代 name。',
      time: '时间戳字符串，footer 会覆盖它。',
      footer: '气泡下方自定义 JSX，传了则替代 time + status。',
      status: "发送状态：'sending' | 'sent' | 'read' | 'failed'。",
      statusPosition: "图标位置：'meta'（时间旁）、'bubble'（气泡内）、'side'（头像与气泡之间）。",
      statusIcon: "自定义状态图标：{ sent: <MyCheck />, read: <BlueCheck /> }，未覆盖的用内置默认。",
      onRetry: '发送失败时的重试回调。',
      onAvatarClick: '头像点击回调。',
      longPressMenu: "长按菜单：传 [{ title, action }] 数组使用内置样式，传 JSX 完全自定义。长按 500ms 弹出。",
      onContentClick: '图片/视频/文件点击回调。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    demo: {
      basic: '基础对话',
      imageVideo: '图片 & 视频',
      fileAndCustom: '文件 & 自定义',
      statusesAndMeta: '状态 & 元信息',
    },
    demoDesc: {
      basic: '左右气泡布局，带头像、名称、时间和尖角指针。',
      imageVideo: '图片和视频消息，视频带播放按钮遮罩。',
      fileAndCustom: '文件附件显示名称+大小，以及通过 slot 完全自定义内容。',
      statusesAndMeta: '发送状态：发送中 → 已发送 → 已读 → 失败（可重试）。',
    },
    intro: '聊天气泡组件，支持文本、图片、视频、文件和自定义内容。内置左右布局、头像、尖角指针和发送状态。',
  },
};