export default {
  chatMessage: {
    props: {
      position: "气泡位置：'left'（对方）| 'right'（自己）。",
      messageType: '消息类型：plainText | richText | image | video | file | custom。',
      content: '文本 / markdown 内容。',
      src: '图片、视频或文件 URL。',
      file: 'JS File 对象，自动提取名称和大小。',
      iconMap: "文件图标映射：{ pdf: '📄', doc: <Icon />, image: '🖼️', '*': '📎' }。匹配优先级：后缀 → MIME大类 → '*'。未匹配时显示大写后缀标签。",
      fileName: '文件显示名称（可覆盖 file.name）。',
      fileSize: '文件显示大小（可覆盖 file.size，自动格式化）。',
      children: '自定义插槽（messageType=custom）。',
      renderSlot: '完全自定义渲染，所有类型均可替代默认。',
      avatar: '头像图片 URL。',
      avatarSize: '头像大小（px），默认 36。',
      avatarShape: "头像形状：'circle' | 'rounded' | 'square'。",
      showAvatar: '是否显示头像，默认 true。',
      avatarSlot: '自定义头像 JSX，会覆盖 avatar 图片。',
      tail: '显示气泡尖角，默认 true。',
      maxWidth: '气泡最大宽度，默认 72%。',
      bgColor: '自定义气泡背景色。',
      borderRadius: '自定义气泡圆角。',
      name: '发送者名称（群聊场景）。',
      time: '时间戳字符串。',
      status: "发送状态：'sending' | 'sent' | 'read' | 'failed'。",
      onRetry: '发送失败时的重试回调。',
      onAvatarClick: '头像点击回调。',
      onLongPress: '气泡长按回调。',
      onContentClick: '图片/视频/文件点击回调。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    demo: {
      basic: '基础对话',
      imageVideo: '图片 & 视频',
      fileAndCustom: '文件 & 自定义',
      statusesAndMeta: '状态 & 元信息',
    },
    demoDesc: {
      basic: '左右气泡布局，带头像、名称、时间和尖角指针。',
      imageVideo: '图片和视频消息，视频带播放按钮遮罩。',
      fileAndCustom: '文件附件显示名称+大小，以及通过 slot 完全自定义内容。',
      statusesAndMeta: '发送状态：发送中 → 已发送 → 已读 → 失败（可重试）。',
    },
    intro: '聊天气泡组件，支持文本、图片、视频、文件和自定义内容。内置左右布局、头像、尖角指针和发送状态。',
  },
};