export default {
  chatMessage: {
    props: {
      position: "气泡位置：'left'（对方）| 'right'（自己）。",
      messageType: '消息类型：plainText | image | video | file | custom。',
      content: '文本 / markdown 内容。',
      src: '图片、视频或文件 URL。',
      fileName: '文件显示名称，自动提取后缀匹配 iconMap。',
      fileSize: '文件显示大小，如 "2.4 MB"。',
      iconMap: "文件图标映射：{ pdf: '📄', doc: <Icon />, '*': '📎' }。按后缀匹配，未命中回退到 '*' 或内置默认图标。",
      progress: '下载/上传进度 0-100，有值时气泡底部显示进度条。',
      children: '自定义插槽（messageType=custom）。',
      avatar: '头像：传 string 显示图片，传 JSX 直接渲染。',
      avatarSize: '头像大小（px），默认 36。',
      avatarShape: "头像形状：'circle' | 'rounded' | 'square'。",
      showAvatar: '是否显示头像，默认 true。',
      tail: '显示气泡尖角，默认 true。',
      maxWidth: '气泡最大宽度，默认 72%。',
      bgColor: '自定义气泡背景色。',
      borderRadius: '自定义气泡圆角。',
      name: '发送者名称（群聊场景），header 会覆盖它。',
      header: '气泡上方自定义 JSX，传了则替代 name。',
      time: '时间戳字符串，footer 会覆盖它。',
      footer: '气泡下方自定义 JSX，传了则替代 time + status。',
      status: "发送状态：'sending' | 'sent' | 'read' | 'failed'。",
      statusPosition: "图标位置：'meta'（时间旁）、'bubble'（气泡内）、'side'（头像与气泡之间）。",
      statusIcon: "自定义状态图标：{ sent: <MyCheck />, read: <BlueCheck /> }，未覆盖的用内置默认。",
      onRetry: '发送失败时的重试回调。',
      onAvatarClick: '头像点击回调。',
      longPressMenu: "长按菜单：传 [{ title, action }] 数组使用内置样式，传 JSX 完全自定义。长按 500ms 弹出。",
      onContentClick: '图片/视频/文件点击回调。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    demo: {
      basic: '基础对话',
      imageVideo: '图片 & 视频',
      fileAndCustom: '文件 & 自定义',
      statusesAndMeta: '状态 & 元信息',
      statusPosition: '状态图标位置',
      longPressArray: '长按：数组菜单',
      longPressCustom: '长按：自定义 JSX',
      longPressSelect: '长按：文本选中',
      fileDownload: '文件下载',
    },
    demoDesc: {
      basic: '左右气泡布局，带头像、名称、时间和尖角指针。',
      imageVideo: '内置图片（带预览）和视频渲染。复杂媒体播放场景请用 messageType=custom + 自定义 JSX。',
      fileAndCustom: '内置文件展示（图标+进度条）。自定义下载交互或交互式文件卡片请用 messageType=custom + 自定义 JSX。',
      statusesAndMeta: '发送状态：发送中 → 已发送 → 已读 → 失败（可重试）。',
      fileDownload: '通过 onContentClick 实现自定义下载逻辑，可对接任意 bridge API、fetch 或下载管理器。',
      statusPosition: "三种位置。'meta' 在时间旁（WhatsApp 风格），'bubble' 浮在气泡内（iMessage 风格），'side' 在头像与气泡之间（微信风格）。",
      longPressArray: '数组模式：每项自动内置样式，长按 500ms 弹出菜单。',
      longPressCustom: '自定义 JSX 模式：完全控制菜单布局，复用 Tooltip 定位。',
      longPressSelect: 'selectOnLongPress 长按全选气泡文字。与 longPressMenu 互斥。',
    },
    intro: '聊天气泡组件，支持文本、图片、视频、文件和自定义内容。内置左右布局、头像、尖角指针和发送状态。',
    note: '说实话，我有些后悔设计这个组件。它不得不将一些经典聊天场景固化为范式，让我的手伸到了本不该触及的业务领域。这和我其他组件的设计理念极为不符，也极容易成为一件费力不讨好的事情（笑）。但大模型时代，聊天气泡确实又十分常用——罢了，还是加上吧。这是一个观点明确的起点，而非通用聊天 UI 方案。如需深度定制，建议基于底层组件自行组装。',
    cssVars: {
      gap: '头像与气泡主体的间距。',
      wrapperPadding: '外层 wrapper 内边距。',
      maxWidth: '气泡最大宽度。',
      bubblePadding: '文本气泡内边距。',
      fontSize: '气泡文字基准字号。',
      lineHeight: '气泡文字行高。',
      radius: '气泡圆角。',
      bubbleBgLeft: '左侧（对方）气泡背景色。',
      bubbleBgSelf: '右侧（自己）气泡背景色。',
      textColor: '左侧气泡文字颜色。',
      textColorSelf: '右侧气泡文字颜色。',
      mutedColor: '名称/时间/元信息的弱化文字颜色。',
      tailWidth: '尖角宽度。',
      tailOffset: '尖角距气泡顶部距离。',
      fileIconSize: '文件图标宽高。',
      menuBg: '长按菜单背景色。',
      menuItemHoverBg: '长按菜单项悬停背景色。',
      progressHeight: '文件进度条高度。',
    },
  },
};