export default {
  upload: { props: {
      type: "Display type: image (thumb grid) / file (list), default image.", accept: 'Accepted file types, <input accept>.', multiple: 'Allow multi-select.', maxCount: 'Max file count, add button hidden when reached.', capture: 'Camera: environment / user.', maxSize: 'Max file size (bytes), exceeded files filtered.', beforeUpload: 'Pre-upload check: (file, files) => boolean|Promise<boolean>.', api: 'Upload function: (file, onProgress?) => Promise<string|undefined>. Must return URL string. No api = file picker only.', fileList: 'File list (controlled).', defaultFileList: 'Initial file list (uncontrolled).', onChange: '(fileList, file) => void on add/remove/progress/status change.', onSuccess: 'Upload success callback.', onError: 'Upload error callback.', onDelete: 'Pre-delete callback. Return false to block.', disabled: 'Disabled.', iconMap: 'File icon map: { pdf: "file-text", "*": "file" }.', children: 'Custom add button.', renderFile: 'Custom file item render: (file, index) => JSX.Element.', class: 'Custom CSS class.', style: 'Inline styles.',
    },
    cssVars: { '--sc-upload-gap': 'Thumb gap, 8px.', '--sc-upload-thumb-size': 'Thumb size, 80px.', '--sc-upload-radius': 'Radius, 8px.', '--sc-upload-add-bg': 'Add button bg.', '--sc-upload-add-border': 'Add button border.', '--sc-upload-add-color': 'Add button + color.', '--sc-upload-progress-bg': 'Progress bg.', '--sc-upload-progress-color': 'Progress fill.' },
    demo: { image: 'Image Upload', file: 'File Upload', limits: 'Limits', controlled: 'Controlled', customTrigger: 'Custom Trigger', customRender: 'Custom Render', iconMap: 'Custom Icons' },
    demoDesc: { image: 'type=image thumb grid, simulated upload progress.', file: 'type=file list mode, no thumbnails.', limits: 'maxCount={3} maxSize={1MB} beforeUpload filters non-images.', controlled: 'fileList + onChange for controlled file list.', customTrigger: 'children override the default + button.', customRender: 'renderFile for custom file item layout.', iconMap: 'iconMap shows different icons per file extension.' },
    design: {
      title: 'Design: No HTTP in the Component Layer',
      ideal: 'The ideal upload component — just pass a URL:',
      reality: 'But in real enterprise projects, it\'s far more complex:',
      q1: 'Is the method always POST?', q2: 'Binary or form-data, or another encoding?', q3: 'How are extra headers (Authorization, etc.) passed?', q4: 'Where does the BaseURL come from?', q5: 'How are timeout and retry configured?', q6: 'How are errors handled? How is progress reported?',
      noHttpTitle: 'Upload Does Not Make HTTP Requests',
      noHttpDesc: 'Traditional component libraries send upload requests on behalf of developers. It seems convenient, but it bakes request logic into props, making it difficult to leverage your existing global HTTP configuration (interceptors, token refresh, unified error handling, etc.). Redundancy with existing infrastructure is inevitable — miss an update on either side and you have a bug. Requests belong to the business layer, not the component layer.',
      noHttpSum: 'Therefore, Upload does not construct or initiate requests. It has no action, headers, data, withCredentials, or any request-related props. Upload requests are initiated by you; the library stays out of it.',
      iocTitle: 'Inversion of Control — Program to an interface, not an implementation',
      iocDesc: 'Upload does one thing: manage the file lifecycle (select → validate → display → delete). "How to upload" is a strategy, injected by you through the api prop — you write a function returning a Promise, and Upload calls it. This is IoC: the component defines an interface (a Promise-returning function), and you provide the implementation. Tokens, interceptors, HTTP libraries — all under your control.',
      noApi: 'Without the api prop, Upload degrades to a file picker + list manager.',
      belief: 'Behind this design is a belief: a mature project already has its own HTTP infrastructure. Upload does not replace it — Upload integrates with it.',
      means: 'This means:',
      row1Title: 'No HTTP library lock-in',
      row1Desc: 'Upload only manages the file lifecycle; network requests are fully under your control. fetch, axios, ky, wx.uploadFile — you choose. The component stays fully decoupled from the HTTP layer.',
      row2Title: "Doesn't bypass infrastructure",
      row2Desc: 'Your request instance — interceptors, token refresh, unified error handling, loading state — all work as usual.',
      row3Title: 'Any Upload Flow',
      row3Desc: 'OSS signatures, COS auth headers, callback notifications — all achievable through a single async function. The traditional action+data model cannot describe such scenarios.',
      row4Title: 'Naturally Testable',
      row4Desc: 'Pass async () => ({ url: "/fake" }) — no HTTP mocking required. Upload logic is fully decoupled from UI; tests verify UI behavior only.',
    },
    intro: 'File upload component. api function injects upload logic — component and HTTP layer are decoupled. Image/file modes, custom rendering and icons.',
  },
};
