export default {
  upload: {
    props: {
      type: '展示类型：image（缩略图网格）/ file（文件列表），默认 image。',
      accept: '接受的文件类型，同 <input accept>。type=image 时默认 image/*。',
      multiple: '是否允许多选，默认 false。',
      maxCount: '最大文件数，达到后隐藏添加按钮。',
      capture: '调用系统相机：environment（后置）/ user（前置）。',
      maxSize: '单文件大小上限（bytes），超限被自动过滤。',
      beforeUpload: '上传前置校验 (file, fileList) => boolean|Promise<boolean>，返回 false 跳过。',
      api: '上传函数 (file, onProgress?) => Promise<string|undefined>。必须返回文件 URL 字符串。不传则仅管理文件列表。',
      fileList: '文件列表（受控）。',
      defaultFileList: '文件列表初始值（非受控）。',
      onChange: '(fileList, file) => void，添加/删除/进度/状态变更时触发。',
      onSuccess: '(file, response) => void，单个文件上传成功回调。',
      onError: '(file, error) => void，上传失败回调。',
      onDelete: '(file) => boolean|Promise<boolean>，删除前回调，返回 false 阻止删除。',
      disabled: '禁用上传。',
      iconMap: '文件图标映射：{ pdf: "file-text", "*": "file" }。type=file 时生效。',
      children: '自定义添加按钮，不传使用默认 + 按钮。',
      renderFile: '(file, index) => JSX.Element，自定义文件项渲染。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-upload-gap': '缩略图间距，默认 8px。',
      '--sc-upload-thumb-size': '缩略图尺寸，默认 80px。',
      '--sc-upload-radius': '缩略图圆角，默认 8px。',
      '--sc-upload-add-bg': '添加按钮背景色。',
      '--sc-upload-add-border': '添加按钮边框色。',
      '--sc-upload-add-color': '添加按钮 + 号颜色。',
      '--sc-upload-progress-bg': '进度条背景色。',
      '--sc-upload-progress-color': '进度条填充色。',
    },
    demo: {
      image: '图片上传',
      file: '文件上传',
      limits: '数量 & 大小限制',
      controlled: '受控模式',
      customTrigger: '自定义触发按钮',
      customRender: '自定义文件渲染',
      iconMap: '自定义文件图标',
    },
    demoDesc: {
      image: 'type=image 缩略图网格，模拟上传进度。',
      file: 'type=file 文件列表模式，不生成缩略图。',
      limits: 'maxCount={3} maxSize={1MB} beforeUpload 过滤非图片。',
      controlled: 'fileList + onChange 受控管理文件列表。',
      customTrigger: 'children 自定义上传触发按钮。',
      customRender: 'renderFile 自定义文件项布局：缩略图 + 名称 + 大小。',
      iconMap: 'iconMap 根据文件扩展名显示不同图标。',
    },
    design: {
      title: '设计理念：组件不做 HTTP 请求',
      ideal: '理想中的上传组件，传一个 URL 就够了：',
      reality: '但真实的企业项目中，事情远比这复杂：',
      q1: '方法一定是 POST 吗？', q2: '请求体是二进制还是 form-data，还是其他编码？', q3: '额外的 Header（Authorization、Content-Type 等）怎么传？', q4: 'BaseURL 从哪来？', q5: '超时和重试策略怎么配？', q6: '错误怎么处理？进度怎么上报？',
      noHttpTitle: 'Upload 不做 HTTP 请求',
      noHttpDesc: '传统组件库替开发者发送上传请求，看似方便，实则把请求逻辑硬编码到 Props 中，让你无法复用已有的全局 HTTP 配置（拦截器、token 刷新、统一错误处理等）。即使勉强凑齐同样的配置，也难免与既有基础设施重复 — 任何一边漏改都会出 Bug。请求属于业务层，不属于组件层。',
      noHttpSum: '因此 Upload 不构建也不发起请求。它不提供 action、headers、data、withCredentials 等任何请求相关属性。上传请求由你发起，组件库不插手。',
      iocTitle: '控制反转（IoC）— 面向接口编程，而非面向实现',
      iocDesc: 'Upload 只做一件事：管理文件生命周期（选择 → 校验 → 展示 → 删除）。怎么上传是一种策略，由你通过 api 属性注入 — 你写一个返回 Promise 的函数，Upload 调用它。这就是控制反转：组件定义接口（返回 Promise 的函数），你提供实现。Token、拦截器、HTTP 库，全在你掌控之中。',
      noApi: '不传 api 时，Upload 退化为一个文件选择器 + 列表管理器。',
      belief: '这个设计背后是一个信念：成熟项目已有自己的 HTTP 基础设施。Upload 不替代它 — Upload 融入它。',
      means: '这意味着：',
      row1Title: '不绑定 HTTP 库',
      row1Desc: 'Upload 只管理文件生命周期；网络请求完全由你控制。fetch、axios、ky、wx.uploadFile — 任你选择，组件与 HTTP 层完全解耦。',
      row2Title: '不绕过基础设施',
      row2Desc: '你的请求实例 — 拦截器、token 刷新、统一错误处理、loading 态 — 一切正常工作。',
      row3Title: '适应任意上传流程',
      row3Desc: 'OSS 签名、COS 鉴权 Header、上传回调通知 — 都能通过一个 async 函数实现。传统的 action+data 模型无法描述这些场景。',
      row4Title: '天然可测试',
      row4Desc: '传入 async () => ({ url: "/fake" })，不需要模拟 HTTP。上传逻辑与 UI 完全解耦，测试只验证 UI 行为。',
    },
    intro: '文件上传组件。通过 api 函数注入上传逻辑，组件层与 HTTP 层解耦。支持图片/文件两种模式，自定义渲染和图标。',
  },
};
