export default {
  timepicker: {
    props: {
      value: 'Current time, format HH:mm:ss (e.g. "08:30:00").',
      onChange: 'Fires when scroll stops.',
      onConfirm: 'Confirm button callback.',
      onCancel: 'Cancel button callback.',
      show: 'Controlled: show the panel. When omitted, auto mode: TimePicker renders its own Cell trigger.',
      onUpdateShow: 'Panel visibility callback for controlled mode.',
      placeholder: 'Placeholder when no value selected.',
      title: 'Panel title.',
      cancelText: 'Cancel button text.',
      confirmText: 'Confirm button text.',
      showUnit: 'Show unit suffix on each column. True → "08h 30m 15s", false → plain numbers. Default false.',
      units: 'Custom unit labels. e.g. { hour: "h", minute: "m", second: "s" }. Falls back to i18n (zh: 时/分/秒, en: h/m/s).',
      visibleItemCount: 'Picker visible item count, default 7.',
      optionHeight: 'Picker option height (px), default 50.',
      teleport: 'Picker portal mount target.',
      zIndex: 'Custom z-index.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-picker-bg': 'Panel background (inherits Picker).',
      '--sc-picker-header-height': 'Header height.',
      '--sc-picker-item-height': 'Item height.',
      '--sc-picker-visible-height': 'Visible area height.',
      '--sc-picker-radius': 'Panel top border radius.',
      '--sc-picker-border-color': 'Divider color.',
    },
    demo: {
      basic: 'Basic',
      preset: 'Preset Value',
      showUnit: 'Show Units',
      form: 'Form Integration',
    },
    demoDesc: {
      basic: 'Controlled mode — Cell trigger + TimePicker, hour:minute:second columns.',
      preset: 'Set value="14:30:00" to pre-select a time. User can adjust it freely.',
      showUnit: 'showUnit adds unit suffixes (en: h/m/s) to each column for clarity.',
      form: 'Use inside FormItem for automatic two-way binding to a form field.',
    },
    intro: 'HH:mm:ss time picker built on Picker. Auto mode with built-in Cell trigger, or controlled mode. Form integration supported.',
  },
};
