export default {
  timepicker: {
    props: {
      value: '当前选中时间，格式 HH:mm:ss（如 "08:30:00"）。',
      onChange: '滚动停止后回调。',
      onConfirm: '确认按钮回调。',
      onCancel: '取消按钮回调。',
      show: '受控：是否显示面板。不传时自动模式，TimePicker 自带 Cell 触发器。',
      onUpdateShow: '面板显示状态回调（受控模式）。',
      placeholder: '未选值时显示的占位文本。',
      title: '面板标题。',
      cancelText: '取消按钮文字。',
      confirmText: '确认按钮文字。',
      showUnit: '是否在每列显示单位后缀。true 时显示 "08时 30分 15秒"，false 时纯数字。默认 false。',
      units: '自定义单位文字。如 { hour: "时", minute: "分", second: "秒" }，不传则跟随 i18n（中文 时/分/秒，英文 h/m/s）。',
      visibleItemCount: 'Picker 可见选项数量，默认 7。',
      optionHeight: 'Picker 选项高度 (px)，默认 50。',
      teleport: 'Picker Portal 挂载目标。',
      zIndex: '自定义层级。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-picker-bg': '面板背景色（继承 Picker）。',
      '--sc-picker-header-height': '头部高度。',
      '--sc-picker-item-height': '选项高度。',
      '--sc-picker-visible-height': '可见区域高度。',
      '--sc-picker-radius': '面板顶部圆角。',
      '--sc-picker-border-color': '分割线颜色。',
    },
    demo: {
      basic: '基础用法',
      preset: '预设值',
      showUnit: '显示单位',
      form: '表单集成',
    },
    demoDesc: {
      basic: '受控模式 — Cell 触发器 + TimePicker，时:分:秒三列滚轮选择。',
      preset: '通过 value="14:30:00" 预设初始值，用户可直接修改。',
      showUnit: 'showUnit 开启后每列追加单位后缀（中文 时/分/秒），更直观。',
      form: '放入 FormItem 中使用，自动双向绑定表单字段。',
    },
    intro: 'HH:mm:ss 三列时间选择器，基于 Picker 封装。自动模式自带 Cell 触发器，也可受控使用。支持 Form 表单集成。',
  },
};
