export default {
  checkbox: {
    props: {
      value: 'Identifier — maps to CheckboxGroup value when checked (required).',
      label: 'Label text, supports JSX.',
      checked: 'Controlled checked state for standalone mode.',
      defaultChecked: 'Uncontrolled default checked state.',
      indeterminate: 'Half-checked state for select-all scenarios.',
      onChange: 'Change callback: (checked: boolean) => void.',
      disabled: 'Disabled.',
      labelDisabled: 'Disable label click toggle.',
      labelPosition: 'Label position: left / right, default right.',
      iconSize: 'Icon size, default 20px.',
      checkedColor: 'Checked color, default #1989fa.',
      shape: 'Shape: square (default) / round.',
      checkedIcon: 'Custom checked icon JSX.',
      uncheckedIcon: 'Custom unchecked icon JSX.',
      indeterminateIcon: 'Custom indeterminate icon JSX.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
      name: 'Native name attribute.',
    },
    groupProps: {
      value: 'Current checked values array (controlled).',
      defaultValue: 'Default value (uncontrolled).',
      onChange: 'Change callback: (value: unknown[]) => void.',
      direction: 'Direction: vertical (default) / horizontal.',
      gap: 'Gap between items.',
      disabled: 'Disable all options.',
      max: 'Max selectable count — remaining options auto-disable.',
      min: 'Min selectable count for validation.',
      iconSize: 'Icon size, default 20px.',
      checkedColor: 'Checked color, default #1989fa.',
      shape: 'Shape: square (default) / round.',
      checkedIcon: 'Custom checked icon.',
      uncheckedIcon: 'Custom unchecked icon.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-checkbox-text-color': 'Text color.',
      '--sc-checkbox-disabled-text-color': 'Disabled text color.',
      '--sc-checkbox-icon-size': 'Icon size, default 20px.',
      '--sc-checkbox-border-color': 'Unchecked border color.',
      '--sc-checkbox-checked-border-color': 'Checked border color.',
      '--sc-checkbox-checked-bg': 'Checked background.',
      '--sc-checkbox-disabled-opacity': 'Disabled opacity.',
      '--sc-checkbox-gap': 'Icon-label gap.',
      '--sc-checkbox-font-size': 'Font size.',
      '--sc-checkbox-border-radius': 'Square corner radius, default 4px.',
    },
    demo: {
      basic: 'Basic',
      disabled: 'Disabled',
      shape: 'Shape',
      color: 'Custom Color',
      horizontal: 'Horizontal',
      max: 'Max Select',
      indeterminate: 'Indeterminate',
      standalone: 'Standalone',
      form: 'Form Integration',
    },
    demoDesc: {
      basic: 'CheckboxGroup wraps Checkbox items. value is the checked values array.',
      disabled: 'Per-item disabled or group-level disabled.',
      shape: 'square (default) and round shapes.',
      color: 'checkedColor="#22c55e" changes the accent.',
      horizontal: 'direction="horizontal" for inline layout.',
      max: 'max={2} limits selection to 2 — extras auto-disable.',
      indeterminate: 'Half-checked state for select-all — shows a dash instead of checkmark.',
      standalone: 'Checkbox used alone with checked + onChange.',
      form: 'CheckboxGroup inside FormItem auto-binds via useFormField().',
    },
    intro: 'Checkbox component with CheckboxGroup wrapper. Square/round shapes, indeterminate state, max selection limit, standalone or Form mode.',
  },
};
