export default {
  checkbox: {
    props: {
      value: '标识符，选中时对应 CheckboxGroup 的 value（必填）。',
      label: '标签文字，支持 JSX。',
      checked: '独立使用时是否选中（受控）。',
      defaultChecked: '独立使用时默认选中（非受控）。',
      indeterminate: '半选状态，用于全选场景中的部分选中指示。',
      onChange: '选中变化回调 (checked: boolean) => void。',
      disabled: '是否禁用。',
      labelDisabled: '是否禁用标签点击切换。',
      labelPosition: '标签位置：left / right，默认 right。',
      iconSize: '图标大小，默认 20px。',
      checkedColor: '选中态颜色，默认 #1989fa。',
      shape: '形状：square（方，默认）/ round（圆）。',
      checkedIcon: '自定义选中图标 JSX。',
      uncheckedIcon: '自定义未选中图标 JSX。',
      indeterminateIcon: '自定义半选图标 JSX。',
      class: '自定义 CSS class。',
      style: '内联样式。',
      name: '原生 name 属性。',
    },
    groupProps: {
      value: '当前选中值列表（受控），unknown[]。',
      defaultValue: '默认值（非受控）。',
      onChange: '值变化回调 (value: unknown[]) => void。',
      direction: '排列方向：vertical（默认）/ horizontal。',
      gap: '选项间距。horizontal 默认 "4px 12px"，vertical 默认 0。',
      disabled: '是否禁用所有选项。',
      max: '最大可选数量，超出后其他选项自动禁用。',
      min: '最小可选数量，用于表单校验场景。',
      iconSize: '图标大小，默认 20px。',
      checkedColor: '选中态颜色，默认 #1989fa。',
      shape: '形状：square（默认）/ round。',
      checkedIcon: '自定义选中图标。',
      uncheckedIcon: '自定义未选中图标。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-checkbox-text-color': '文字颜色。',
      '--sc-checkbox-disabled-text-color': '禁用态文字颜色。',
      '--sc-checkbox-icon-size': '图标大小，默认 20px。',
      '--sc-checkbox-border-color': '未选中边框颜色。',
      '--sc-checkbox-checked-border-color': '选中态边框颜色。',
      '--sc-checkbox-checked-bg': '选中态背景色。',
      '--sc-checkbox-disabled-opacity': '禁用态透明度。',
      '--sc-checkbox-gap': '图标与标签间距。',
      '--sc-checkbox-font-size': '字号。',
      '--sc-checkbox-border-radius': '方角圆角，默认 4px。',
    },
    demo: {
      basic: '基础用法',
      disabled: '禁用',
      shape: '形状',
      color: '自定义颜色',
      horizontal: '横向排列',
      max: '最大选择',
      indeterminate: '半选状态',
      standalone: '独立使用',
      form: '表单集成',
    },
    demoDesc: {
      basic: 'CheckboxGroup 包裹 Checkbox，value 为选中值数组。',
      disabled: '单个 Checkbox 设置 disabled，或全局 disabled。',
      shape: 'square（方形，默认）和 round（圆形）两种形状。',
      color: 'checkedColor="#22c55e" 修改选中态颜色。',
      horizontal: 'direction="horizontal" 横向排列。',
      max: 'max={2} 限制最多选 2 项，超出后其余选项自动禁用。',
      indeterminate: '半选状态用于全选场景 — 部分选中时显示横线而非勾号。',
      standalone: 'Checkbox 脱离 Group 单独使用，checked + onChange 自行管理。',
      form: 'CheckboxGroup 放入 FormItem，通过 useFormField() 自动双向绑定。',
    },
    intro: '多选组件，配合 CheckboxGroup 使用。支持方形/圆形、半选状态、最大选择数限制、独立模式和表单集成。',
  },
};
