export default {
  cascader: {
    props: {
      options: 'Cascade data source: CascaderOption[]. Each item\'s children forms the next level.',
      value: 'Current value: (string | number)[] in depth order.',
      onChange: 'Value change callback: (value: (string | number)[]) => void.',
      title: 'Popup title.',
      placeholder: 'Placeholder text when no selection.',
      closeable: 'Show close button.',
      show: 'Controlled popup visibility.',
      onUpdateShow: 'Show state change callback.',
      onClose: 'Close callback.',
      maxHeight: 'Max popup height, default 40vh.',
      showCheckmark: 'Show ✓ checkmark on selected item, default true.',
      checkmark: 'Custom checkmark JSX, replaces default ✓.',
      teleport: 'Portal mount target.',
      zIndex: 'Custom z-index.',
      name: 'Form field name.',
      required: 'Required flag.',
      disabled: 'Disable the entire selector.',
      readonly: 'Readonly mode.',
      onLoadChildren: 'Async loader: (option) => Promise<CascaderOption[]>.',
      loading: 'Custom loading content for async mode.',
      onFocus: 'Focus callback.',
      onBlur: 'Blur callback.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-cascader-bg': 'Sheet background color.',
      '--sc-cascader-header-height': 'Header height.',
      '--sc-cascader-tab-height': 'Tab bar height.',
      '--sc-cascader-item-height': 'Option item height.',
      '--sc-cascader-text-color': 'Text color.',
      '--sc-cascader-text-secondary': 'Secondary text / inactive tab color.',
      '--sc-cascader-active-color': 'Active / selected color.',
      '--sc-cascader-border': 'Divider border color.',
      '--sc-cascader-radius': 'Sheet top border radius.',
      '--sc-cascader-shadow': 'Sheet shadow.',
    },
    demo: {
      region: 'Region Select',
      disabledOption: 'Disabled Options',
      customRender: 'Custom Render',
      asyncLoad: 'Async Load',
    },
    demoDesc: {
      region: 'Three-level cascade. Auto-closes on leaf select. Click top tabs to go back.',
      disabledOption: 'Set disabled: true to gray out options — they won\'t respond to clicks.',
      customRender: 'Rich JSX per option: emoji icon + city name + population info + colored region badge, with custom checkmark icon.',
      asyncLoad: 'Empty options initially; each level fetched on demand. Simulates 1s latency.',
    },
    optionProps: {
      text: 'Display text.',
      value: 'Selected value.',
      children: 'Child options for next level expansion.',
      disabled: 'Whether disabled.',
      isLeaf: 'Mark as leaf node — stops async loading when true.',
      render: 'Custom JSX render, overrides text when set.',
    },
    intro: 'Multi-level cascade selector with tree data source. Top tabs show the selected path — click to navigate back. Supports async loading, custom rendering, and disabled control.',
  },
};
