export default {
  cascader: {
    props: {
      options: '级联数据源，CascaderOption[]。每项的 children 为下一级选项。',
      value: '当前选中值，(string | number)[] 按层级顺序排列。',
      onChange: '值变化回调，(value: (string | number)[]) => void。',
      title: '弹出层标题。',
      placeholder: '未选中时的占位文字。',
      closeable: '是否显示关闭按钮。',
      show: '弹出层显示（受控）。',
      onUpdateShow: '显示状态变化回调。',
      onClose: '关闭回调。',
      maxHeight: '弹窗最大高度，默认 40vh。',
      showCheckmark: '选中的项右侧是否显示对勾图标，默认 true。',
      checkmark: '自定义选中图标 JSX，传入后替代默认 ✓。',
      teleport: 'Portal 挂载目标。',
      zIndex: '自定义 z-index 层级。',
      name: '表单字段名。',
      required: '是否必填。',
      disabled: '是否禁用整个选择器。',
      readonly: '是否只读。',
      onLoadChildren: '异步加载子选项，(option) => Promise<CascaderOption[]>。',
      loading: '异步加载时的自定义 Loading 内容。',
      onFocus: '聚焦回调。',
      onBlur: '失焦回调。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-cascader-bg': '面板背景色。',
      '--sc-cascader-header-height': '标题栏高度。',
      '--sc-cascader-tab-height': 'Tab 栏高度。',
      '--sc-cascader-item-height': '选项高度。',
      '--sc-cascader-text-color': '文字颜色。',
      '--sc-cascader-text-secondary': '次要文字 / Tab 未激活态颜色。',
      '--sc-cascader-active-color': '选中态 / 激活态颜色。',
      '--sc-cascader-border': '分割线颜色。',
      '--sc-cascader-radius': '面板顶部圆角。',
      '--sc-cascader-shadow': '面板阴影。',
    },
    demo: {
      region: '地区选择',
      disabledOption: '禁用选项',
      customRender: '自定义渲染',
      asyncLoad: '异步加载',
    },
    demoDesc: {
      region: '三级联动选择，选中叶子节点自动关闭，顶部 Tab 可回退层级。',
      disabledOption: '设置 disabled: true 禁用特定选项，灰色不可点击。',
      customRender: 'option.render 传入 JSX：emoji 图标 + 城市名 + 人口信息 + 彩色地区标签，checkmark 替换为自定义图标。',
      asyncLoad: 'options 初始为空，每级由 onLoadChildren 按需拉取，模拟 1s 延迟。',
    },
    optionProps: {
      text: '显示文本。',
      value: '选中值。',
      children: '子选项数组，用于下一级展开。',
      disabled: '是否禁用。',
      isLeaf: '是否为叶子节点，为 true 时不再触发异步加载。',
      render: '自定义渲染 JSX，设置后替代 text 显示。',
    },
    intro: '多层级联选择器，通过树形数据源逐级展开。顶部 Tab 显示选中路径，可点击回退。支持异步加载、自定义渲染和禁用控制。',
  },
};
