export default {
  image: {
    props: {
      src: 'Image URL.',
      alt: 'Alt text.',
      width: 'Width. Numbers auto-suffixed with px.',
      height: 'Height. Numbers auto-suffixed with px.',
      fit: 'Object fit: cover / contain / fill / none / scale-down.',
      position: 'object-position value.',
      radius: 'Border radius. Numbers auto-suffixed with px.',
      round: 'Fully round (circle).',
      block: 'Block-level element, full width.',
      lazy: 'Enable lazy loading.',
      placeholder: 'Loading placeholder content.',
      fallback: 'Error fallback content.',
      iconSize: 'Icon size on load error.',
      onLoad: 'Load success callback.',
      onError: 'Load error callback.',
      preview: 'Click to preview full image.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    demo: {
      basic: 'Basic',
      fit: 'Fit Modes',
      shape: 'Shape',
      block: 'Block',
      state: 'Load States',
      preview: 'Preview',
    },
    demoDesc: {
      basic: 'Use src for image URL, width/height for dimensions.',
      fit: 'Fit controls object-fit behavior with fixed container size.',
      shape: 'Radius for rounded corners, round for circle.',
      block: 'Block fills parent width.',
      state: 'Placeholder while loading, fallback on error.',
      preview: 'Preview enables full-screen image viewer on click.',
    },
    intro: 'Enhanced image component with lazy loading, placeholder, fallback, fit modes, rounded/circle shape, and tap-to-preview.',
  },
};
