export default {
  image: {
    props: {
      src: '图片地址。',
      alt: '替代文本。',
      width: '宽度，数字自动补 px。',
      height: '高度，数字自动补 px。',
      fit: '填充方式：cover / contain / fill / none / scale-down。',
      position: 'object-position 值。',
      radius: '圆角大小，数字自动补 px。',
      round: '完全圆形。',
      block: '块级元素，宽度 100%。',
      lazy: '启用懒加载。',
      placeholder: '加载中占位内容。',
      fallback: '加载失败兜底内容。',
      iconSize: '加载失败时图标大小。',
      onLoad: '加载成功回调。',
      onError: '加载失败回调。',
      preview: '点击全屏预览大图。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    demo: {
      basic: '基础用法',
      fit: '填充方式',
      shape: '形状',
      block: '块级展示',
      state: '加载状态',
      preview: '图片预览',
    },
    demoDesc: {
      basic: '通过 src 传入地址，width / height 控制尺寸。',
      fit: 'fit 控制 object-fit 行为，容器固定尺寸对比不同填充效果。',
      shape: 'radius 控制圆角，round 变为圆形。',
      block: 'block 撑满父容器宽度。',
      state: 'placeholder 加载中占位，fallback 加载失败兜底。',
      preview: 'preview 开启点击全屏预览大图。',
    },
    intro: '增强的图片组件，支持懒加载、加载占位、失败兜底、多种填充方式、圆角/圆形和点击预览。',
  },
};
