export default {
  citypicker: {
    props: {
      columns: 'Region tree data: PickerOption[]. You provide your own data — the component has none built-in.',
      value: 'Current value: (string | number)[] in province→city→district order.',
      onChange: 'Value change callback.',
      onConfirm: 'Confirm button callback.',
      onCancel: 'Cancel button callback.',
      placeholder: 'Placeholder when no selection.',
      separator: 'Display separator, default " / ".',
      show: 'Controlled: show the panel. When omitted, auto mode: CityPicker renders its own Cell trigger.',
      onUpdateShow: 'Panel visibility callback for controlled mode.',
      title: 'Popup title.',
      cancelText: 'Cancel button text.',
      confirmText: 'Confirm button text.',
      visibleItemCount: 'Picker visible item count.',
      optionHeight: 'Picker option height.',
      teleport: 'Picker portal mount target.',
      zIndex: 'Custom z-index.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-picker-bg': 'Panel background (inherits Picker).',
      '--sc-picker-header-height': 'Header height.',
      '--sc-picker-item-height': 'Item height.',
      '--sc-picker-visible-height': 'Visible area height.',
      '--sc-picker-radius': 'Panel top border radius.',
      '--sc-picker-border-color': 'Divider color.',
    },
    demo: {
      region: '3-Level Cascade',
      autoMode: 'Auto Mode',
      deepCascade: '4-Level Deep',
    },
    demoDesc: {
      region: 'Controlled mode — Cell trigger + CityPicker, province→city→district cascade.',
      autoMode: 'Auto mode — omit show, CityPicker renders its own Cell trigger, great for CellGroup embedding.',
      deepCascade: 'CityPicker uses Picker tree mode under the hood — arbitrary depth supported. 4 levels: province→city→district→street.',
    },
    design: {
      cardTitle: 'Design: Picker + City Data = CityPicker',
      para1: 'CityPicker is not "another picker" — it IS a Picker. It just standardizes the tree data shape for region selection. You supply PickerOption[] data, and CityPicker handles cascade display and selection. Everything else is standard Picker capability.',
      para2: 'The component library ships with zero city data. Administrative divisions change (mergers, new districts), and bundling data means you\'d have to wait for a library update to get current data — that\'s unreasonable.',
      whyTitle: 'Why no built-in city data?',
      whyDesc: 'The library\'s job is UI interaction, not business data. Bundling city data creates several problems:',
      reason1Title: 'Stale data — ',
      reason1Desc: 'Administrative divisions change frequently. Outdated data in the library is incorrect data in your app.',
      reason2Title: 'Bundle bloat — ',
      reason2Desc: 'Full national region data has tens of thousands of entries. Most projects only need a small subset.',
      reason3Title: 'Your choice — ',
      reason3Desc: 'Your project may have its own data source (backend API, CDN JSON) or only need specific regions. CityPicker defines the format — you own the content.',
      summary: 'CityPicker = Picker(tree) + PickerOption[] region data (provided by you). Simple, flexible, no black boxes.',
    },
    intro: 'Region cascade picker built on Picker. Includes a built-in Cell trigger (auto mode) or works in controlled mode. You supply your own region data — the component ships with none.',
  },
};
