export default {
  citypicker: {
    props: {
      columns: '省市区树形数据，PickerOption[]。数据需用户自行提供，组件不内置。',
      value: '当前选中值，(string | number)[] 按省→市→区顺序排列。',
      onChange: '值变化回调。',
      onConfirm: '确认按钮回调。',
      onCancel: '取消按钮回调。',
      placeholder: '未选中时的占位文字。',
      separator: '显示文字分隔符，默认 " / "。',
      show: '受控模式：是否显示面板。不传时自动模式，CityPicker 自带 Cell 触发器。',
      onUpdateShow: '面板显示状态回调（受控模式）。',
      title: '弹出层标题。',
      cancelText: '取消按钮文字。',
      confirmText: '确认按钮文字。',
      visibleItemCount: 'Picker 可见选项数量。',
      optionHeight: 'Picker 选项高度。',
      teleport: 'Picker Portal 挂载目标。',
      zIndex: '自定义层级。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-picker-bg': '面板背景色（继承 Picker）。',
      '--sc-picker-header-height': '头部高度。',
      '--sc-picker-item-height': '选项高度。',
      '--sc-picker-visible-height': '可见区域高度。',
      '--sc-picker-radius': '面板顶部圆角。',
      '--sc-picker-border-color': '分割线颜色。',
    },
    demo: {
      region: '省市区三级',
      autoMode: '自动模式',
      deepCascade: '四级深度',
    },
    demoDesc: {
      region: '受控模式 — Cell 触发器 + CityPicker，省→市→区三级联级选择。',
      autoMode: '自动模式 — 不传 show，CityPicker 自带 Cell 触发器，适合直接嵌入 CellGroup。',
      deepCascade: 'CityPicker 底层是 Picker tree 模式，天然支持任意深度。4 级：省→市→区→街道。',
    },
    design: {
      cardTitle: '设计理念：Picker + 城市数据 = CityPicker',
      para1: 'CityPicker 不是"另一个选择器"，它就是 Picker，只是帮你把城市树形数据的结构约定好了。你传入 PickerOption[] 格式的省市区数据，CityPicker 负责级联展示和选择，剩下的全是标准 Picker 的能力。',
      para2: '组件库不内置任何城市数据。城市区划会变化（行政区划调整、新区设立），内置数据意味着你必须等组件库更新才能获得新数据，这不合理。',
      whyTitle: '为什么不内置城市数据？',
      whyDesc: '组件库的职责是提供 UI 交互，不是提供业务数据。内置城市数据会带来一系列问题：',
      reason1Title: '「数据过时」—— ',
      reason1Desc: '行政区划经常调整（如撤县设区、新区设立），内置数据一旦过时就是错误数据。',
      reason2Title: '「包体积膨胀」—— ',
      reason2Desc: '全国完整的省市区街道数据有数万条，打包进去会让组件库体积暴增，而大部分项目只需要其中一部分。',
      reason3Title: '「选择权交给你」—— ',
      reason3Desc: '你的项目可能有自己的数据源（后端接口、CDN JSON），或者只需要特定几个省市。CityPicker 只定义数据格式，数据内容由你决定。',
      summary: 'CityPicker = Picker(tree) + PickerOption[] 城市数据（你自己提供）。简单、灵活，没有黑箱。',
    },
    intro: '省市区级联选择器，基于 Picker 封装。自带 Cell 触发器（自动模式），也可受控使用。数据需用户自行提供，组件不内置地区数据。',
  },
};
