export default {
  textarea: {
    props: {
      value: '当前值（受控）。',
      onChange: '值变化回调 (value: string) => void。',
      defaultValue: '默认值（非受控）。',
      placeholder: '占位文本。',
      maxlength: '最大长度。超过后不可继续输入。',
      rows: '可视行数，默认 3。',
      autoSize: '自动撑高，传入 { minRows, maxRows } 可限制范围。',
      clearable: '显示清除按钮，输入内容后右侧出现 × 图标。',
      disabled: '禁用。',
      readonly: '只读，可聚焦复制但不可编辑。',
      showCount: '显示字数统计（需配合 maxlength）。',
      error: '错误状态，底部显示红色指示。',
      height: '自定义高度，如 "120px"。',
      onBlur: '失焦回调。',
      onFocus: '聚焦回调。',
      onEnter: '回车回调。',
      onClear: '清除回调。',
      autofocus: '自动聚焦。',
      class: '自定义 CSS class。',
      style: '内联样式。',
      id: 'DOM id。',
      name: '原生 name 属性。',
    },
    cssVars: {
      '--sc-textarea-text-color': '文字颜色。',
      '--sc-textarea-placeholder-color': '占位符颜色。',
      '--sc-textarea-border-color': '边框颜色。',
      '--sc-textarea-border-focus-color': '聚焦时边框颜色。',
      '--sc-textarea-disabled-opacity': '禁用态透明度，默认 0.5。',
      '--sc-textarea-count-font-size': '计数字号，默认 0.75rem。',
      '--sc-textarea-count-color': '计数颜色。',
      '--sc-textarea-error-color': '错误态颜色，默认 #e01823。',
    },
    demo: {
      basic: '基础用法',
      autoSize: '自动撑高',
      states: '状态',
      count: '字数统计',
      form: '表单集成',
    },
    demoDesc: {
      basic: 'rows={5} 控制高度，placeholder 占位提示。',
      autoSize: 'autoSize 随内容自动撑高，可传 { minRows, maxRows } 限制范围。',
      states: 'disabled 禁用 / readonly 只读 / error 错误 / clearable 可清除。',
      count: 'maxlength 限制字数 + showCount 显示统计。',
      form: '放入 FormItem，通过 useFormField() 自动双向绑定。',
    },
    intro: '多行文本输入组件。支持自动撑高、字数统计、清除、状态控制，通过 FormItem 自动接入表单。',
  },
};
