export default {
  tabs: {
    props: {
      active: 'Current active tab (controlled).',
      defaultActive: 'Default active tab (uncontrolled).',
      onChange: 'Tab change callback.',
      type: 'Style: line / card.',
      color: 'Theme color.',
      background: 'Tab bar background color.',
      duration: 'Animation duration (s), default 0.3.',
      animated: 'Content area switch animation.',
      border: 'Show bottom border (line mode only).',
      sticky: 'Sticky positioning.',
      offsetTop: 'Sticky offset from top.',
      lazyRender: 'Lazy render inactive tabs, default true.',
      titleActiveColor: 'Active title color.',
      titleInactiveColor: 'Inactive title color.',
      centered: 'Auto-scroll to center the active tab (scrollable), default false.',
      beforeChange: 'Guard callback, return false to prevent switch.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    tabProps: {
      title: 'Tab title. String or JSX.',
      name: 'Tab identifier, matches Tabs active.',
      disabled: 'Whether this tab is disabled.',
      children: 'Tab panel content.',
    },
    demo: {
      line: 'Line Mode',
      scrollable: 'Scrollable',
      jsxTitle: 'JSX Title',
      card: 'Card Mode',
      color: 'Custom Color',
      controlled: 'Controlled',
      disabled: 'Disabled',
    },
    demoDesc: {
      line: "Default line style with sliding indicator.",
      scrollable: 'Tab titles overflow horizontally for many tabs.',
      jsxTitle: 'Title supports any JSX, e.g. icon + text.',
      card: "Card style tab bar.",
      color: 'Customize theme via color / titleActiveColor.',
      controlled: 'External control via active + onChange.',
      disabled: 'Disabled tabs cannot be clicked.',
    },
    intro: 'Tab switcher. Supports line/card styles, lazy render, JSX titles, controlled mode, and disabled tabs.',
  },
};
