export default {
  tabs: {
    props: {
      active: '当前激活的 tab（受控）。',
      defaultActive: '默认激活的 tab（非受控）。',
      onChange: '切换回调。',
      type: '样式风格：line / card。',
      color: '主题色。',
      background: '标签栏背景色。',
      duration: '动画时长（秒），默认 0.3。',
      animated: '内容区切换动画。',
      border: '显示底部边框（仅 line 模式）。',
      sticky: '粘性定位。',
      offsetTop: '粘性定位距顶距离。',
      lazyRender: '延迟渲染未激活的 tab，默认 true。',
      titleActiveColor: '标题选中态颜色。',
      titleInactiveColor: '标题默认态颜色。',
      centered: '切换时自动滚动标签使选中项居中（仅横向滚动生效），默认 false。',
      beforeChange: '切换前回调，返回 false 阻止切换。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    tabProps: {
      title: 'Tab 标题，支持字符串或 JSX。',
      name: 'Tab 标识符，对应 Tabs 的 active。',
      disabled: '是否禁用该 Tab。',
      children: 'Tab 内容。',
    },
    demo: {
      line: 'Line 模式',
      scrollable: '横向滚动',
      jsxTitle: 'JSX 标题',
      card: 'Card 模式',
      color: '自定义颜色',
      controlled: '受控模式',
      disabled: '禁用',
    },
    demoDesc: {
      line: "type='line' 默认风格，底部指示条跟随切换。",
      scrollable: '标签数量超出容器宽度时可横向滚动。',
      jsxTitle: 'title 支持传入任意 JSX，如图标+文字。',
      card: "type='card' 卡片式标签栏。",
      color: '通过 color / titleActiveColor 自定义主题色。',
      controlled: '通过 active + onChange 外部控制。',
      disabled: 'disabled 禁用单个 Tab，不可点击。',
    },
    intro: '标签页切换组件。支持 line / card 两种风格、懒加载、JSX 标题、受控模式、禁用选项。',
  },
};
