export default {
  dialog: {
    props: {
      show: 'Whether dialog is visible (controlled, required).',
      title: 'Title. String or JSX.',
      message: 'Content. Supports line breaks and JSX.',
      width: 'Dialog width, default 320px.',
      messageAlign: 'Text align: left / center / right, default center.',
      showConfirmButton: 'Show confirm button, default true.',
      showCancelButton: 'Show cancel button, default false.',
      confirmText: 'Confirm button text.',
      cancelText: 'Cancel button text.',
      confirmDisabled: 'Disable confirm button.',
      cancelDisabled: 'Disable cancel button.',
      zIndex: 'Stack level, default 2000.',
      overlay: 'Show overlay, default true.',
      closeOnClickOverlay: 'Close on overlay click, default false.',
      lockScroll: 'Lock background scroll, default true.',
      beforeClose: 'Guard callback. Return false to prevent close.',
      onConfirm: 'Confirm callback.',
      onCancel: 'Cancel callback.',
      onClose: 'Close callback.',
      teleport: 'Portal mount target.',
      destroyOnClose: 'Destroy content on close.',
      lazyRender: 'Lazy render, default true.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    methods: {
      alert: 'Dialog.alert(options) — Confirm-only dialog.',
      confirm: 'Dialog.confirm(options) — Dialog with cancel button.',
      show: 'Dialog.show(options) — Full config dialog.',
      dismissAll: 'Dialog.dismissAll() — Close all dialogs.',
    },
    cssVars: {
      '--sc-dialog-bg': 'Dialog background.',
      '--sc-dialog-radius': 'Dialog border radius.',
      '--sc-dialog-shadow': 'Dialog shadow.',
      '--sc-dialog-header-size': 'Title font size.',
      '--sc-dialog-header-color': 'Title color.',
      '--sc-dialog-body-size': 'Body font size.',
      '--sc-dialog-body-color': 'Body color.',
      '--sc-dialog-btn-height': 'Button height.',
      '--sc-dialog-confirm-color': 'Confirm button color.',
      '--sc-dialog-cancel-color': 'Cancel button color.',
    },
    demo: {
      basic: 'Basic',
      advanced: 'Advanced',
    },
    demoDesc: {
      basic: 'Alert (confirm only), Confirm (with cancel), No title, Multiline.',
      advanced: 'Custom button text, JSX content, async submit, prevent close.',
    },
    intro: 'Centered modal dialog. Supports declarative component and imperative API.',
  },
};
