export default {
  dialog: {
    props: {
      show: '是否显示（受控模式，必填）。',
      title: '标题，支持 string 或 JSX。',
      message: '内容，支持换行和 JSX。',
      width: '弹窗宽度，默认 320px。',
      messageAlign: '内容对齐：left / center / right，默认 center。',
      showConfirmButton: '显示确认按钮，默认 true。',
      showCancelButton: '显示取消按钮，默认 false。',
      confirmText: '确认按钮文字。',
      cancelText: '取消按钮文字。',
      confirmDisabled: '禁用确认按钮。',
      cancelDisabled: '禁用取消按钮。',
      zIndex: '层级，默认 2000。',
      overlay: '显示遮罩，默认 true。',
      closeOnClickOverlay: '点击遮罩关闭，默认 false。',
      lockScroll: '锁定背景滚动，默认 true。',
      beforeClose: '关闭前回调，返回 false 阻止关闭。',
      onConfirm: '确认回调。',
      onCancel: '取消回调。',
      onClose: '关闭回调。',
      teleport: 'Portal 挂载目标。',
      destroyOnClose: '关闭时销毁内容。',
      lazyRender: '懒渲染，默认 true。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    methods: {
      alert: 'Dialog.alert(options) — 仅确认按钮的提示弹窗。',
      confirm: 'Dialog.confirm(options) — 带取消按钮的确认弹窗。',
      show: 'Dialog.show(options) — 完整配置弹窗。',
      dismissAll: 'Dialog.dismissAll() — 关闭所有弹窗。',
    },
    cssVars: {
      '--sc-dialog-bg': '弹窗背景色。',
      '--sc-dialog-radius': '弹窗圆角。',
      '--sc-dialog-shadow': '弹窗阴影。',
      '--sc-dialog-header-size': '标题字号。',
      '--sc-dialog-header-color': '标题颜色。',
      '--sc-dialog-body-size': '正文字号。',
      '--sc-dialog-body-color': '正文颜色。',
      '--sc-dialog-btn-height': '按钮高度。',
      '--sc-dialog-confirm-color': '确认按钮颜色。',
      '--sc-dialog-cancel-color': '取消按钮颜色。',
    },
    demo: {
      basic: '基础弹窗',
      advanced: '高级用法',
    },
    demoDesc: {
      basic: 'Alert（仅确认）、Confirm（含取消）、无标题、多行文本。',
      advanced: '自定义按钮文字、JSX 内容、异步提交、阻止关闭。',
    },
    demoAlert: '提示弹窗',
    demoConfirm: '确认弹窗',
    demoNoTitle: '无标题',
    demoMultiline: '多行文本',
    demoCustomBtns: '自定义按钮',
    demoJsx: 'JSX 内容',
    demoAsync: '异步提交',
    demoPrevent: '阻止关闭',
    descAlert: '仅确认按钮的基础提示。',
    descConfirm: '带取消按钮，用于删除等确认场景。',
    descNoTitle: '不传 title 时只展示内容。',
    descMultiline: 'message 中 \\n 自动换行。',
    descCustomBtns: '通过 confirmText / cancelText 自定义按钮文字。',
    descJsx: 'message 支持传入 JSX，实现富文本布局。',
    descAsync: 'onConfirm 返回 Promise 时自动展示 Loading。',
    descPrevent: 'beforeClose 返回 false 阻止关闭。',
    intro: '居中模态对话框。支持声明式组件和命令式 API 两种调用方式。',
  },
};
