export default {
  switch: {
    note: 'Note: SolidJS has a built-in <Switch> control-flow component. Import with alias: import { Switch as Toggle } from "solid-component".',
    props: {
      checked: 'Whether on (controlled). value is an alias.',
      value: "Alias for checked.",
      defaultChecked: 'Default state (uncontrolled), default false.',
      onChange: 'Change callback: (checked: boolean) => void.',
      disabled: 'Disabled.',
      size: 'Size, numbers auto-suffixed with px, default 28.',
      activeColor: 'Background color when on.',
      inactiveColor: 'Background color when off.',
      activeText: 'Text shown when on.',
      inactiveText: 'Text shown when off.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
      id: 'DOM id.',
    },
    cssVars: {
      '--sc-switch-width': 'Switch width, default 2em (relative to size).',
      '--sc-switch-height': 'Switch height, default 1em.',
      '--sc-switch-node-size': 'Node size, default 0.8em.',
      '--sc-switch-bg': 'Off background.',
      '--sc-switch-checked-bg': 'On background.',
      '--sc-switch-node-bg': 'Node background, default #fff.',
      '--sc-switch-disabled-opacity': 'Disabled opacity, default 0.5.',
      '--sc-switch-transition': 'Transition duration, default 0.3s.',
    },
    demo: {
      basic: 'Basic',
      disabled: 'Disabled',
      color: 'Custom Color',
      size: 'Size',
      text: 'Text',
      form: 'Form Integration',
    },
    demoDesc: {
      basic: 'checked + onChange (controlled) or defaultChecked (uncontrolled).',
      disabled: 'disabled state.',
      color: 'activeColor + inactiveColor customizes the switch colors.',
      size: 'size controls dimensions: 28 (default), 36, 48.',
      text: 'activeText / inactiveText shows text on the switch knob.',
      form: 'Inside FormItem auto-binds via useFormField().',
    },
    intro: 'Toggle switch between two states. Controlled/uncontrolled, custom colors and sizes, text labels, Form integration. ⚠ Use import alias to avoid SolidJS built-in <Switch>.',
  },
};
