export default {
  switch: {
    note: '注意：SolidJS 内置了 <Switch> 控制流组件，导入时请使用别名：import { Switch as Toggle } from "solid-component"。',
    props: {
      checked: '是否打开（受控）。value 为别名，二选一。',
      value: 'checked 的别名。',
      defaultChecked: '默认是否打开（非受控），默认 false。',
      onChange: '状态变化回调 (checked: boolean) => void。',
      disabled: '是否禁用。',
      size: '尺寸，数字自动补 px，默认 28（约 28px 高）。',
      activeColor: '打开时的背景色。',
      inactiveColor: '关闭时的背景色。',
      activeText: '打开时显示的文案。',
      inactiveText: '关闭时显示的文案。',
      class: '自定义 CSS class。',
      style: '内联样式。',
      id: 'DOM id。',
    },
    cssVars: {
      '--sc-switch-width': '开关宽度，默认 2em（相对 size）。',
      '--sc-switch-height': '开关高度，默认 1em。',
      '--sc-switch-node-size': '滑块大小，默认 0.8em。',
      '--sc-switch-bg': '关闭态背景色。',
      '--sc-switch-checked-bg': '打开态背景色。',
      '--sc-switch-node-bg': '滑块背景色，默认 #fff。',
      '--sc-switch-disabled-opacity': '禁用态透明度，默认 0.5。',
      '--sc-switch-transition': '过渡动画时长，默认 0.3s。',
    },
    demo: {
      basic: '基础用法',
      disabled: '禁用',
      color: '自定义颜色',
      size: '尺寸',
      text: '内置文案',
      form: '表单集成',
    },
    demoDesc: {
      basic: 'checked + onChange 受控模式，或 defaultChecked 非受控。',
      disabled: 'disabled 禁用态。',
      color: 'activeColor + inactiveColor 自定义开关颜色。',
      size: 'size 控制尺寸：28（默认）/ 36 / 48。',
      text: 'activeText / inactiveText 在滑块上显示开关文案。',
      form: '放入 FormItem，通过 useFormField() 自动双向绑定。',
    },
    intro: '开关组件，在两种状态间切换。支持受控/非受控、自定义颜色和尺寸、内置文案、表单集成。⚠ 注意：需用别名导入避开 SolidJS 内置 <Switch>。',
  },
};
