export default {
  datepicker: {
    props: {
      value: 'Current value: YYYY-MM-DD (date/year-month) or YYYY-MM-DD HH:mm:ss (datetime).',
      onChange: 'Value change callback.',
      onConfirm: 'Confirm button callback.',
      onCancel: 'Cancel button callback.',
      startDate: 'Start of selectable range, default 2014-01-01.',
      endDate: 'End of selectable range, default 2034-12-31.',
      type: 'Selection type: date (YMD), year-month (YM), datetime (YMD HMS).',
      placeholder: 'Placeholder text when no value.',
      disabledDate: 'Disable specific dates. (year, month, day) => boolean returns true to disable.',
      show: 'Controlled: show the picker panel. Auto-managed with Cell trigger when not provided.',
      onUpdateShow: 'Panel visibility callback for controlled mode.',
      title: 'Panel title.',
      cancelText: 'Cancel button text.',
      confirmText: 'Confirm button text.',
      visibleItemCount: 'Picker visible item count.',
      optionHeight: 'Picker option height.',
      teleport: 'Picker portal mount target.',
      zIndex: 'Custom z-index.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-picker-bg': 'Panel background (inherits Picker).',
      '--sc-picker-header-height': 'Header height.',
      '--sc-picker-item-height': 'Item height.',
      '--sc-picker-visible-height': 'Visible area height.',
      '--sc-picker-radius': 'Panel top border radius.',
      '--sc-picker-border-color': 'Divider color.',
    },
    demo: {
      basic: 'Basic Date',
      yearMonth: 'Year-Month',
      disabledDate: 'Disable Weekends',
      dateRange: 'Date Range',
      dateTime: 'Date & Time',
    },
    demoDesc: {
      basic: 'Auto mode — DatePicker renders its own Cell trigger, tap to open the date picker.',
      yearMonth: 'type=year-month, select year and month only, no day column.',
      disabledDate: 'disabledDate callback disables Sat/Sun — they appear grayed out.',
      dateRange: 'startDate + endDate constrain selection to the year 2025.',
      dateTime: 'type=datetime, six scroll columns: year, month, day, hour, minute, second.',
    },
    intro: 'Date picker built on Picker. Supports date, year-month, and datetime modes. Auto mode includes a built-in Cell trigger; also works in controlled mode.',
  },
};
