export default {
  datepicker: {
    props: {
      value: '当前值，格式 YYYY-MM-DD（date / year-month）或 YYYY-MM-DD HH:mm:ss（datetime）。',
      onChange: '值变化回调。',
      onConfirm: '确认按钮点击回调。',
      onCancel: '取消按钮点击回调。',
      startDate: '可选范围起点，默认 2014-01-01。',
      endDate: '可选范围终点，默认 2034-12-31。',
      type: "选择类型：date（年月日）、year-month（年月）、datetime（日期+时间）。",
      placeholder: '未选中时的占位文字。',
      disabledDate: '禁用特定日期。(year, month, day) => boolean，返回 true 则该日不可选。',
      show: '受控模式：是否显示面板。不传时 DatePicker 自动管理展开/收起，渲染 Cell 触发器。',
      onUpdateShow: '面板显示状态回调（受控模式）。',
      title: '面板标题。',
      cancelText: '取消按钮文字。',
      confirmText: '确认按钮文字。',
      visibleItemCount: 'Picker 可见选项数量。',
      optionHeight: 'Picker 选项高度。',
      teleport: 'Picker Portal 挂载目标。',
      zIndex: '自定义层级。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-picker-bg': '面板背景色（继承 Picker）。',
      '--sc-picker-header-height': '头部高度。',
      '--sc-picker-item-height': '选项高度。',
      '--sc-picker-visible-height': '可见区域高度。',
      '--sc-picker-radius': '面板顶部圆角。',
      '--sc-picker-border-color': '分割线颜色。',
    },
    demo: {
      basic: '基础日期',
      yearMonth: '年月选择',
      disabledDate: '禁用周末',
      dateRange: '日期范围',
      dateTime: '日期+时间',
    },
    demoDesc: {
      basic: 'auto 模式 — DatePicker 自带 Cell 触发器，点击弹出日期滚轮。',
      yearMonth: 'type=year-month，只选年月，不选日。',
      disabledDate: 'disabledDate 禁用周末（周六/日），灰色不可选。',
      dateRange: 'startDate + endDate 限制可选范围到 2025 年内。',
      dateTime: 'type=datetime，年月日 + 时分秒六列滚轮选择。',
    },
    intro: '日期选择器，基于 Picker 封装。支持 date、year-month、datetime 三种模式，自动模式自带 Cell 触发器，也可受控使用。',
  },
};
