export default {
  navbar: {
    props: {
      title: 'Title. String or JSX.',
      left: 'Custom left content.',
      right: 'Custom right content.',
      backArrow: 'Show back arrow, default false.',
      onBack: 'Back arrow click callback.',
      onLeftClick: 'Left area click callback.',
      onRightClick: 'Right area click callback.',
      fixed: 'Fix at top.',
      placeholder: 'Generate placeholder when fixed.',
      border: 'Show bottom border.',
      zIndex: 'z-index.',
      background: 'Background color.',
      color: 'Text color.',
      height: 'Nav bar height, default 46.',
      class: 'Custom CSS class.',
      style: 'Inline styles.',
    },
    cssVars: {
      '--sc-navbar-height': 'Nav bar height.',
      '--sc-navbar-bg': 'Background color.',
      '--sc-navbar-color': 'Text color.',
      '--sc-navbar-font-size': 'Title font size.',
      '--sc-navbar-border': 'Border color.',
      '--sc-navbar-padding': 'Horizontal padding.',
      '--sc-navbar-title-weight': 'Title font weight.',
    },
    demo: {
      basic: 'Basic Title',
      back: 'Back Arrow',
      sides: 'Left & Right',
      style: 'Custom Style',
      fixed: 'Fixed Mode',
    },
    demoDesc: {
      basic: 'Simplest navbar with centered title.',
      back: 'Show back arrow via backArrow prop.',
      sides: 'Custom left and right areas with icons or text.',
      style: 'Customize background and color for branding.',
      fixed: 'Fixed to top with placeholder to prevent overlap.',
    },
    intro: 'Top navigation bar with left/center/right layout. Supports back arrow, fixed positioning, and placeholder.',
  },
};
