export default {
  navbar: {
    props: {
      title: '标题，支持字符串或 JSX。',
      left: '左侧自定义内容。',
      right: '右侧自定义内容。',
      backArrow: '是否显示返回箭头，默认 false。',
      onBack: '返回箭头点击回调。',
      onLeftClick: '左侧区域点击回调。',
      onRightClick: '右侧区域点击回调。',
      fixed: '是否固定在顶部。',
      placeholder: 'fixed 时生成等高占位，避免内容被遮挡。',
      border: '是否显示底部边框。',
      zIndex: 'z-index。',
      background: '背景色。',
      color: '文字颜色。',
      height: '导航栏高度，默认 46。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-navbar-height': '导航栏高度。',
      '--sc-navbar-bg': '背景色。',
      '--sc-navbar-color': '文字颜色。',
      '--sc-navbar-font-size': '标题字号。',
      '--sc-navbar-border': '分割线颜色。',
      '--sc-navbar-padding': '水平内边距。',
      '--sc-navbar-title-weight': '标题字重。',
    },
    demo: {
      basic: '基础标题',
      back: '返回箭头',
      sides: '左右内容',
      style: '自定义样式',
      fixed: '固定模式',
    },
    demoDesc: {
      basic: '最简单的导航栏，仅有标题居中。',
      back: 'backArrow 显示返回箭头，onBack 处理点击。',
      sides: 'left 和 right 可传入任意 JSX，如图标或文字按钮。',
      style: '通过 background / color 自定义主题色。',
      fixed: 'fixed + placeholder 固定在顶部并占位。',
    },
    intro: '顶部导航条，提供左/中/右三区域布局，支持返回箭头、固定定位和占位元素。',
  },
};
