export default {
  slider: {
    props: {
      value: '当前值。count=1 时为 number，count>1 时为 number[]。',
      onChange: '值变化回调 (value: number | number[]) => void。',
      min: '最小值，默认 0。',
      max: '最大值，默认 100。',
      step: '步长，默认 1。',
      count: '滑块数量（理论上支持任意数量），默认 1。count=2 双滑块范围选择，更大即多滑块。',
      barHeight: '进度条高度。',
      buttonSize: '滑块按钮大小。',
      activeColor: '进度条激活态颜色。',
      inactiveColor: '进度条非激活态颜色。',
      reverse: '是否反转方向。',
      disabled: '禁用。',
      readonly: '只读。',
      thumbRender: '自定义滑块按钮渲染 (value, index) => JSX|null。',
      class: '自定义 CSS class。',
      style: '内联样式。',
    },
    cssVars: {
      '--sc-slider-bar-height': '进度条高度，默认 4px。',
      '--sc-slider-button-size': '滑块按钮大小，默认 24px。',
      '--sc-slider-active-color': '激活态颜色。',
      '--sc-slider-inactive-color': '非激活态颜色。',
      '--sc-slider-disabled-opacity': '禁用态透明度，默认 0.4。',
    },
    demo: {
      basic: '基础用法',
      range: '范围选择',
      step: '步长',
      color: '自定义颜色',
      disabled: '禁用',
      form: '表单集成',
    },
    demoDesc: {
      basic: 'value + onChange 单滑块。',
      range: 'count={2} 双滑块范围选择。理论上 count 可以为任意值，但多于 2 个滑块很少用到。',
      step: 'step={10} 离散步进。',
      color: 'activeColor + inactiveColor 自定义配色。',
      disabled: 'disabled / readonly 两种不可交互态。',
      form: 'Slider 通过 useFormField() 接入 FormItem。',
    },
    intro: '滑动选择器，支持单滑块和范围选择（双滑块）。可自定义颜色、步长、进度条/按钮尺寸。',
  },
};
